package com.gbicc.person.monitor.entity;
// Generated 2011-11-6 21:15:24 by Hibernate Tools 3.2.2.GA



/**
 * TPlDqMonitor generated by hbm2java
 */
public class TPlDqMonitor extends TPlTask implements java.io.Serializable {


    /**
	 * 
	 */
	private static final long serialVersionUID = 955000545039642732L;
	/*
    */
    private String id;

    public TPlDqMonitor() {
    }

    public TPlDqMonitor(String id) {
       this.id = id;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }




}


