package com.gbicc.person.monitor.entity;
// Generated 2015-12-22 16:30:58 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * TPlDqReportJyGuarant generated by hbm2java
 */
public class TPlDqReportJyGuarant  implements java.io.Serializable {

	private static final long serialVersionUID = 4594712924516550356L;
	
	/*
    * ID主键.
    */
    private String id;
    /*
    * 借款人.
    */
    private String custname;
    /*
    * 合同编号.
    */
    private String contno;
    /*
    * 担保方式.
    */
    private String assukind;
    /*
    * 货款金额.
    */
    private BigDecimal tcapi;
    /*
    * 货款余额.
    */
    private BigDecimal bal;
    /*
    * 发放日期.
    */
    private Date begindate;
    /*
    * 到期日期.
    */
    private Date enddate;
    /*
    * 五级分类.
    */
    private String riskflag;
    /*
     * 公用TASK表ID.
     */
    private String businessid;

    public TPlDqReportJyGuarant() {
    }

	
    public TPlDqReportJyGuarant(String id) {
        this.id = id;
    }
	/**
    * Get the ID主键
    */	
    public String getId() {
        return this.id;
    }
	/**
    * Set the ID主键
    */	
    public void setId(String id) {
        this.id = id;
    }
	/**
    * Get the 借款人
    */	
    public String getCustname() {
        return this.custname;
    }
	/**
    * Set the 借款人
    */	
    public void setCustname(String custname) {
        this.custname = custname;
    }
	/**
    * Get the 合同编号
    */	
    public String getContno() {
        return this.contno;
    }
	/**
    * Set the 合同编号
    */	
    public void setContno(String contno) {
        this.contno = contno;
    }
	/**
    * Get the 担保方式
    */	
    public String getAssukind() {
        return this.assukind;
    }
	/**
    * Set the 担保方式
    */	
    public void setAssukind(String assukind) {
        this.assukind = assukind;
    }
	/**
    * Get the 货款金额
    */	
    public BigDecimal getTcapi() {
        return this.tcapi;
    }
	/**
    * Set the 货款金额
    */	
    public void setTcapi(BigDecimal tcapi) {
        this.tcapi = tcapi;
    }
	/**
    * Get the 货款余额
    */	
    public BigDecimal getBal() {
        return this.bal;
    }
	/**
    * Set the 货款余额
    */	
    public void setBal(BigDecimal bal) {
        this.bal = bal;
    }
	/**
    * Get the 发放日期
    */	
    public Date getBegindate() {
        return this.begindate;
    }
	/**
    * Set the 发放日期
    */	
    public void setBegindate(Date begindate) {
        this.begindate = begindate;
    }
	/**
    * Get the 到期日期
    */	
    public Date getEnddate() {
        return this.enddate;
    }
	/**
    * Set the 到期日期
    */	
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
	/**
    * Get the 五级分类
    */	
    public String getRiskflag() {
        return this.riskflag;
    }
	/**
    * Set the 五级分类
    */	
    public void setRiskflag(String riskflag) {
        this.riskflag = riskflag;
    }
    /**
     * Get the 公用TASK表ID
     */	
	public String getBusinessid() {
		return businessid;
	}
	/**
    * Set the 公用TASK表ID
    */	
	public void setBusinessid(String businessid) {
		this.businessid = businessid;
	}
}