package com.gbicc.person.monitor.entity;
// Generated 2015-12-22 14:03:22 by Hibernate Tools 3.2.2.GA



/**
 * TPlDqReportJyPartner generated by hbm2java
 */
@SuppressWarnings("serial")
public class TPlDqReportJyPartner  implements java.io.Serializable {

    /*
    * ID主键.
    */
    private String id;
    /*
    * 股东编号.
    */
    private String holdcustid;
    /*
    * 股东名称.
    */
    private String holdcustname;
    /*
    * 股东证件类型.
    */
    private String paperkind;
    /*
    * 股东证件号码.
    */
    private String paperid;
    /*
    * 出资金额.
    */
    private Double inveamt;
    /*
    * 出资比例.
    */
    private Double stockperc;
    /*
     * 公用TASK表ID.
     */
    private String businessid;

    public TPlDqReportJyPartner() {
    }

    public TPlDqReportJyPartner(String id) {
        this.id = id;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getHoldcustid() {
        return this.holdcustid;
    }
    
    public void setHoldcustid(String holdcustid) {
        this.holdcustid = holdcustid;
    }
    public String getHoldcustname() {
        return this.holdcustname;
    }
    
    public void setHoldcustname(String holdcustname) {
        this.holdcustname = holdcustname;
    }
    public String getPaperkind() {
        return this.paperkind;
    }
    
    public void setPaperkind(String paperkind) {
        this.paperkind = paperkind;
    }
    public String getPaperid() {
        return this.paperid;
    }
    
    public void setPaperid(String paperid) {
        this.paperid = paperid;
    }
    public Double getInveamt() {
        return this.inveamt;
    }
    
    public void setInveamt(Double inveamt) {
        this.inveamt = inveamt;
    }
    public Double getStockperc() {
        return this.stockperc;
    }
    
    public void setStockperc(Double stockperc) {
        this.stockperc = stockperc;
    }

	public String getBusinessid() {
		return businessid;
	}

	public void setBusinessid(String businessid) {
		this.businessid = businessid;
	}
}