package com.gbicc.person.customer.entity;
// Generated 2015-11-24 10:47:45 by Hibernate Tools 3.2.2.GA



/**
 * TPlCustGreatEventDtl generated by hbm2java
 */
public class TPlCustGreatEventDtl  implements java.io.Serializable {

	private static final long serialVersionUID = 5095394362277322874L;
	
	/*
    */
    private String id;
    /*
    * 主表ID.
    */
    private String eventId;
    /*
    * 事件名称.
    */
    private String eventName;
    /*
    * 事件值.
    */
    private String eventValue;
    /*
    * 事件说明.
    */
    private String eventDesc;
    /*
    * 事件级别.
    */
    private String eventLevel;

    public TPlCustGreatEventDtl() {
    }

	
    public TPlCustGreatEventDtl(String id) {
        this.id = id;
    }
    public TPlCustGreatEventDtl(String id, String eventId, String eventName, String eventValue, String eventDesc, String eventLevel) {
       this.id = id;
       this.eventId = eventId;
       this.eventName = eventName;
       this.eventValue = eventValue;
       this.eventDesc = eventDesc;
       this.eventLevel = eventLevel;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getEventId() {
        return this.eventId;
    }
    
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }
    
	public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    public String getEventValue() {
        return this.eventValue;
    }
    
    public void setEventValue(String eventValue) {
        this.eventValue = eventValue;
    }
    public String getEventDesc() {
        return this.eventDesc;
    }
    
    public void setEventDesc(String eventDesc) {
        this.eventDesc = eventDesc;
    }
    public String getEventLevel() {
        return this.eventLevel;
    }
    
    public void setEventLevel(String eventLevel) {
        this.eventLevel = eventLevel;
    }
}