package com.gbicc.person.frequency.entity;
// Generated 2016-1-20 10:29:58 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * TPlTrigFrequencyAcctVId generated by hbm2java
 */
public class TPlTrigFrequencyAcctV  implements java.io.Serializable {


    /*
    */
    private String productCode;
    /*
    */
    private String loanAccount;
    /*
    */
    private String custcode;
    /*
    */
    private String custname;
    /*
    */
    private BigDecimal loanAmount;
    /*
    */
    private BigDecimal loanBalance;
    /*
    */
    private BigDecimal floatinterate;
    /*
    */
    private Integer loanPeriod;
    /*
    */
    private String operator;
    /*
    */
    private String operBank;
    /*
    */
    private Double trigRate;
    /*
    */
    private Integer rankFinal;

    public TPlTrigFrequencyAcctV() {
    }

	
    public TPlTrigFrequencyAcctV(String loanAccount) {
        this.loanAccount = loanAccount;
    }
    public TPlTrigFrequencyAcctV(String productCode, String loanAccount, String custcode, String custname, BigDecimal loanAmount, BigDecimal loanBalance, BigDecimal floatinterate, Integer loanPeriod, String operator, String operBank, Double trigRate, Integer rankFinal) {
       this.productCode = productCode;
       this.loanAccount = loanAccount;
       this.custcode = custcode;
       this.custname = custname;
       this.loanAmount = loanAmount;
       this.loanBalance = loanBalance;
       this.floatinterate = floatinterate;
       this.loanPeriod = loanPeriod;
       this.operator = operator;
       this.operBank = operBank;
       this.trigRate = trigRate;
       this.rankFinal = rankFinal;
    }
   
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
    public String getLoanAccount() {
        return this.loanAccount;
    }
    
    public void setLoanAccount(String loanAccount) {
        this.loanAccount = loanAccount;
    }
    public String getCustcode() {
        return this.custcode;
    }
    
    public void setCustcode(String custcode) {
        this.custcode = custcode;
    }
    public String getCustname() {
        return this.custname;
    }
    
    public void setCustname(String custname) {
        this.custname = custname;
    }
    public BigDecimal getLoanAmount() {
        return this.loanAmount;
    }
    
    public void setLoanAmount(BigDecimal loanAmount) {
        this.loanAmount = loanAmount;
    }
    public BigDecimal getLoanBalance() {
        return this.loanBalance;
    }
    
    public void setLoanBalance(BigDecimal loanBalance) {
        this.loanBalance = loanBalance;
    }
    public BigDecimal getFloatinterate() {
        return this.floatinterate;
    }
    
    public void setFloatinterate(BigDecimal floatinterate) {
        this.floatinterate = floatinterate;
    }
    public Integer getLoanPeriod() {
        return this.loanPeriod;
    }
    
    public void setLoanPeriod(Integer loanPeriod) {
        this.loanPeriod = loanPeriod;
    }
    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }
    public String getOperBank() {
        return this.operBank;
    }
    
    public void setOperBank(String operBank) {
        this.operBank = operBank;
    }
    public Double getTrigRate() {
        return this.trigRate;
    }
    
    public void setTrigRate(Double trigRate) {
        this.trigRate = trigRate;
    }
    public Integer getRankFinal() {
        return this.rankFinal;
    }
    
    public void setRankFinal(Integer rankFinal) {
        this.rankFinal = rankFinal;
    }


  
}


