package com.gbicc.company.financial.analysis.entity;
// Generated 2015-12-5 15:32:56 by Hibernate Tools 3.2.2.GA



/**
 * TCmFinanceStatementCode generated by hbm2java
 */
public class TCmFinanceStatementCode  implements java.io.Serializable {


    /*
    * 项目代码 .
    */
    private String projectCd;
    /*
    * 项目名称 .
    */
    private String projectName;
    /*
    * 财务报表类别代码 .
    */
    private String financeReportSortCd;
    /*
    * 报表类型（资产、利润、现金）.
    */
    private String reportType;

    public TCmFinanceStatementCode() {
    }

	
    public TCmFinanceStatementCode(String projectCd) {
        this.projectCd = projectCd;
    }
    public TCmFinanceStatementCode(String projectCd, String projectName, String financeReportSortCd, String reportType) {
       this.projectCd = projectCd;
       this.projectName = projectName;
       this.financeReportSortCd = financeReportSortCd;
       this.reportType = reportType;
    }
   
    public String getProjectCd() {
        return this.projectCd;
    }
    
    public void setProjectCd(String projectCd) {
        this.projectCd = projectCd;
    }
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    public String getFinanceReportSortCd() {
        return this.financeReportSortCd;
    }
    
    public void setFinanceReportSortCd(String financeReportSortCd) {
        this.financeReportSortCd = financeReportSortCd;
    }
    public String getReportType() {
        return this.reportType;
    }
    
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }




}


