package com.gbicc.personCommon.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 评分信息表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TEdwPlsScore implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 业务编号. */
	private String loanid;

	/** 账户ID. */
	private String loanacno;

	/** 客户编号. */
	private String custid;

	/** 客户名称. */
	private String custname;

	/** 评分类型. */
	private String gradetype;

	/** 实时评分结果. */
	private Integer cograderesult;

	/** 实时评分日期. */
	private Date cogradedate;

	/** 批量评分结果. */
	private Integer plgraderesult;

	/** 批量评分日期. */
	private Date gradedate;

	/** 评分对象状态. */
	private String gradestat;

	/** 违约时间. */
	private Date fouldate;

	/**
	 * Constructor.
	 */
	public TEdwPlsScore() {
	}

	/**
	 * Set the 业务编号.
	 * 
	 * @param loanid
	 *            业务编号
	 */
	public void setLoanid(String loanid) {
		this.loanid = loanid;
	}

	/**
	 * Get the 业务编号.
	 * 
	 * @return 业务编号
	 */
	public String getLoanid() {
		return this.loanid;
	}

	/**
	 * Set the 账户ID.
	 * 
	 * @param loanacno
	 *            账户ID
	 */
	public void setLoanacno(String loanacno) {
		this.loanacno = loanacno;
	}

	/**
	 * Get the 账户ID.
	 * 
	 * @return 账户ID
	 */
	public String getLoanacno() {
		return this.loanacno;
	}

	/**
	 * Set the 客户编号.
	 * 
	 * @param custid
	 *            客户编号
	 */
	public void setCustid(String custid) {
		this.custid = custid;
	}

	/**
	 * Get the 客户编号.
	 * 
	 * @return 客户编号
	 */
	public String getCustid() {
		return this.custid;
	}

	/**
	 * Set the 客户名称.
	 * 
	 * @param custname
	 *            客户名称
	 */
	public void setCustname(String custname) {
		this.custname = custname;
	}

	/**
	 * Get the 客户名称.
	 * 
	 * @return 客户名称
	 */
	public String getCustname() {
		return this.custname;
	}

	/**
	 * Set the 评分类型.
	 * 
	 * @param gradetype
	 *            评分类型
	 */
	public void setGradetype(String gradetype) {
		this.gradetype = gradetype;
	}

	/**
	 * Get the 评分类型.
	 * 
	 * @return 评分类型
	 */
	public String getGradetype() {
		return this.gradetype;
	}

	/**
	 * Set the 实时评分结果.
	 * 
	 * @param cograderesult
	 *            实时评分结果
	 */
	public void setCograderesult(Integer cograderesult) {
		this.cograderesult = cograderesult;
	}

	/**
	 * Get the 实时评分结果.
	 * 
	 * @return 实时评分结果
	 */
	public Integer getCograderesult() {
		return this.cograderesult;
	}

	/**
	 * Set the 实时评分日期.
	 * 
	 * @param cogradedate
	 *            实时评分日期
	 */
	public void setCogradedate(Date cogradedate) {
		this.cogradedate = cogradedate;
	}

	/**
	 * Get the 实时评分日期.
	 * 
	 * @return 实时评分日期
	 */
	public Date getCogradedate() {
		return this.cogradedate;
	}

	/**
	 * Set the 批量评分结果.
	 * 
	 * @param plgraderesult
	 *            批量评分结果
	 */
	public void setPlgraderesult(Integer plgraderesult) {
		this.plgraderesult = plgraderesult;
	}

	/**
	 * Get the 批量评分结果.
	 * 
	 * @return 批量评分结果
	 */
	public Integer getPlgraderesult() {
		return this.plgraderesult;
	}

	/**
	 * Set the 批量评分日期.
	 * 
	 * @param gradedate
	 *            批量评分日期
	 */
	public void setGradedate(Date gradedate) {
		this.gradedate = gradedate;
	}

	/**
	 * Get the 批量评分日期.
	 * 
	 * @return 批量评分日期
	 */
	public Date getGradedate() {
		return this.gradedate;
	}

	/**
	 * Set the 评分对象状态.
	 * 
	 * @param gradestat
	 *            评分对象状态
	 */
	public void setGradestat(String gradestat) {
		this.gradestat = gradestat;
	}

	/**
	 * Get the 评分对象状态.
	 * 
	 * @return 评分对象状态
	 */
	public String getGradestat() {
		return this.gradestat;
	}

	/**
	 * Set the 违约时间.
	 * 
	 * @param fouldate
	 *            违约时间
	 */
	public void setFouldate(Date fouldate) {
		this.fouldate = fouldate;
	}

	/**
	 * Get the 违约时间.
	 * 
	 * @return 违约时间
	 */
	public Date getFouldate() {
		return this.fouldate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((loanid == null) ? 0 : loanid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TEdwPlsScore other = (TEdwPlsScore) obj;
		if (loanid == null) {
			if (other.loanid != null) {
				return false;
			}
		} else if (!loanid.equals(other.loanid)) {
			return false;
		}
		return true;
	}

}
