package com.gbicc.personCommon.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 核心存款账户表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TEdwCorePayAcc implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 银行号. */
	private String socNo;

	/** 旧账号. */
	private String oldAcctNo;

	/** 账号. */
	private String membCustAc;

	/** 开户行机构. */
	private String branchNo;

	/** 账户当前状态. */
	private String currStatus;

	/** 账户所属产品主类. */
	private String acctType;

	/** 账户所属产品子类. */
	private String intCat;

	/** 账户所属的客户号. */
	private String customerNo;

	/** 账户所属的客户名称. */
	private String customerName;

	/** 账户当前余额. */
	private Double currBal;

	/** 冻结金额. */
	private Double holdVal;

	/** 账户最近维护日期. */
	private Date lstMntDt;

	/** 账户的状态. */
	private Boolean currCond;

	/** 账户开户日期. */
	private Date acctOpenDt;

	/**
	 * Constructor.
	 */
	public TEdwCorePayAcc() {
	}

	/**
	 * Set the 银行号.
	 * 
	 * @param socNo
	 *            银行号
	 */
	public void setSocNo(String socNo) {
		this.socNo = socNo;
	}

	/**
	 * Get the 银行号.
	 * 
	 * @return 银行号
	 */
	public String getSocNo() {
		return this.socNo;
	}

	/**
	 * Set the 旧账号.
	 * 
	 * @param oldAcctNo
	 *            旧账号
	 */
	public void setOldAcctNo(String oldAcctNo) {
		this.oldAcctNo = oldAcctNo;
	}

	/**
	 * Get the 旧账号.
	 * 
	 * @return 旧账号
	 */
	public String getOldAcctNo() {
		return this.oldAcctNo;
	}

	/**
	 * Set the 账号.
	 * 
	 * @param membCustAc
	 *            账号
	 */
	public void setMembCustAc(String membCustAc) {
		this.membCustAc = membCustAc;
	}

	/**
	 * Get the 账号.
	 * 
	 * @return 账号
	 */
	public String getMembCustAc() {
		return this.membCustAc;
	}

	/**
	 * Set the 开户行机构.
	 * 
	 * @param branchNo
	 *            开户行机构
	 */
	public void setBranchNo(String branchNo) {
		this.branchNo = branchNo;
	}

	/**
	 * Get the 开户行机构.
	 * 
	 * @return 开户行机构
	 */
	public String getBranchNo() {
		return this.branchNo;
	}

	/**
	 * Set the 账户当前状态.
	 * 
	 * @param currStatus
	 *            账户当前状态
	 */
	public void setCurrStatus(String currStatus) {
		this.currStatus = currStatus;
	}

	/**
	 * Get the 账户当前状态.
	 * 
	 * @return 账户当前状态
	 */
	public String getCurrStatus() {
		return this.currStatus;
	}

	/**
	 * Set the 账户所属产品主类.
	 * 
	 * @param acctType
	 *            账户所属产品主类
	 */
	public void setAcctType(String acctType) {
		this.acctType = acctType;
	}

	/**
	 * Get the 账户所属产品主类.
	 * 
	 * @return 账户所属产品主类
	 */
	public String getAcctType() {
		return this.acctType;
	}

	/**
	 * Set the 账户所属产品子类.
	 * 
	 * @param intCat
	 *            账户所属产品子类
	 */
	public void setIntCat(String intCat) {
		this.intCat = intCat;
	}

	/**
	 * Get the 账户所属产品子类.
	 * 
	 * @return 账户所属产品子类
	 */
	public String getIntCat() {
		return this.intCat;
	}

	/**
	 * Set the 账户所属的客户号.
	 * 
	 * @param customerNo
	 *            账户所属的客户号
	 */
	public void setCustomerNo(String customerNo) {
		this.customerNo = customerNo;
	}

	/**
	 * Get the 账户所属的客户号.
	 * 
	 * @return 账户所属的客户号
	 */
	public String getCustomerNo() {
		return this.customerNo;
	}

	/**
	 * Set the 账户所属的客户名称.
	 * 
	 * @param customerName
	 *            账户所属的客户名称
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/**
	 * Get the 账户所属的客户名称.
	 * 
	 * @return 账户所属的客户名称
	 */
	public String getCustomerName() {
		return this.customerName;
	}

	/**
	 * Set the 账户当前余额.
	 * 
	 * @param currBal
	 *            账户当前余额
	 */
	public void setCurrBal(Double currBal) {
		this.currBal = currBal;
	}

	/**
	 * Get the 账户当前余额.
	 * 
	 * @return 账户当前余额
	 */
	public Double getCurrBal() {
		return this.currBal;
	}

	/**
	 * Set the 冻结金额.
	 * 
	 * @param holdVal
	 *            冻结金额
	 */
	public void setHoldVal(Double holdVal) {
		this.holdVal = holdVal;
	}

	/**
	 * Get the 冻结金额.
	 * 
	 * @return 冻结金额
	 */
	public Double getHoldVal() {
		return this.holdVal;
	}

	/**
	 * Set the 账户最近维护日期.
	 * 
	 * @param lstMntDt
	 *            账户最近维护日期
	 */
	public void setLstMntDt(Date lstMntDt) {
		this.lstMntDt = lstMntDt;
	}

	/**
	 * Get the 账户最近维护日期.
	 * 
	 * @return 账户最近维护日期
	 */
	public Date getLstMntDt() {
		return this.lstMntDt;
	}

	/**
	 * Set the 账户的状态.
	 * 
	 * @param currCond
	 *            账户的状态
	 */
	public void setCurrCond(Boolean currCond) {
		this.currCond = currCond;
	}

	/**
	 * Get the 账户的状态.
	 * 
	 * @return 账户的状态
	 */
	public Boolean getCurrCond() {
		return this.currCond;
	}

	/**
	 * Set the 账户开户日期.
	 * 
	 * @param acctOpenDt
	 *            账户开户日期
	 */
	public void setAcctOpenDt(Date acctOpenDt) {
		this.acctOpenDt = acctOpenDt;
	}

	/**
	 * Get the 账户开户日期.
	 * 
	 * @return 账户开户日期
	 */
	public Date getAcctOpenDt() {
		return this.acctOpenDt;
	}


}
