package com.gbicc.personCommon.entity;

import java.io.Serializable;

/**
 * Model class of 楼盘信息表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TEdwPlsBuilding implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 项目编号. */
	private String projid;

	/** 合作方编号. */
	private String corpid;

	/** 合作商名称. */
	private String corpname;

	/** 项目名称. */
	private String projname;

	/** 销售许可证. */
	private String liceno;

	/**
	 * Constructor.
	 */
	public TEdwPlsBuilding() {
	}

	/**
	 * Set the 项目编号.
	 * 
	 * @param projid
	 *            项目编号
	 */
	public void setProjid(String projid) {
		this.projid = projid;
	}

	/**
	 * Get the 项目编号.
	 * 
	 * @return 项目编号
	 */
	public String getProjid() {
		return this.projid;
	}

	/**
	 * Set the 合作方编号.
	 * 
	 * @param corpid
	 *            合作方编号
	 */
	public void setCorpid(String corpid) {
		this.corpid = corpid;
	}

	/**
	 * Get the 合作方编号.
	 * 
	 * @return 合作方编号
	 */
	public String getCorpid() {
		return this.corpid;
	}

	/**
	 * Set the 合作商名称.
	 * 
	 * @param corpname
	 *            合作商名称
	 */
	public void setCorpname(String corpname) {
		this.corpname = corpname;
	}

	/**
	 * Get the 合作商名称.
	 * 
	 * @return 合作商名称
	 */
	public String getCorpname() {
		return this.corpname;
	}

	/**
	 * Set the 项目名称.
	 * 
	 * @param projname
	 *            项目名称
	 */
	public void setProjname(String projname) {
		this.projname = projname;
	}

	/**
	 * Get the 项目名称.
	 * 
	 * @return 项目名称
	 */
	public String getProjname() {
		return this.projname;
	}

	/**
	 * Set the 销售许可证.
	 * 
	 * @param liceno
	 *            销售许可证
	 */
	public void setLiceno(String liceno) {
		this.liceno = liceno;
	}

	/**
	 * Get the 销售许可证.
	 * 
	 * @return 销售许可证
	 */
	public String getLiceno() {
		return this.liceno;
	}


}
