package com.gbicc.personCommon.entity;

import java.io.Serializable;

/**
 * Model class of 保证人信息表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TEdwPlsGuarantor implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 保证编号. */
	private String assuid;

	/** 保证方式. */
	private String ensutype;

	/** 保证类型. */
	private String ensukind;

	/** 保证人编号. */
	private String assucustid;

	/** 保证人. */
	private String assucustname;

	/** 保证类型2. */
	private String ensukind2;

	/** 我行贷款余额. */
	private Double ourloanbal;

	/** 我行不良贷款额度. */
	private Double ourbadbal;

	/** 他行贷款余额. */
	private Double otherloanbal;

	/** 他行不良贷款额度. */
	private Double otherbadbal;

	/**
	 * Constructor.
	 */
	public TEdwPlsGuarantor() {
	}

	/**
	 * Set the 保证编号.
	 * 
	 * @param assuid
	 *            保证编号
	 */
	public void setAssuid(String assuid) {
		this.assuid = assuid;
	}

	/**
	 * Get the 保证编号.
	 * 
	 * @return 保证编号
	 */
	public String getAssuid() {
		return this.assuid;
	}

	/**
	 * Set the 保证方式.
	 * 
	 * @param ensutype
	 *            保证方式
	 */
	public void setEnsutype(String ensutype) {
		this.ensutype = ensutype;
	}

	/**
	 * Get the 保证方式.
	 * 
	 * @return 保证方式
	 */
	public String getEnsutype() {
		return this.ensutype;
	}

	/**
	 * Set the 保证类型.
	 * 
	 * @param ensukind
	 *            保证类型
	 */
	public void setEnsukind(String ensukind) {
		this.ensukind = ensukind;
	}

	/**
	 * Get the 保证类型.
	 * 
	 * @return 保证类型
	 */
	public String getEnsukind() {
		return this.ensukind;
	}

	/**
	 * Set the 保证人编号.
	 * 
	 * @param assucustid
	 *            保证人编号
	 */
	public void setAssucustid(String assucustid) {
		this.assucustid = assucustid;
	}

	/**
	 * Get the 保证人编号.
	 * 
	 * @return 保证人编号
	 */
	public String getAssucustid() {
		return this.assucustid;
	}

	/**
	 * Set the 保证人.
	 * 
	 * @param assucustname
	 *            保证人
	 */
	public void setAssucustname(String assucustname) {
		this.assucustname = assucustname;
	}

	/**
	 * Get the 保证人.
	 * 
	 * @return 保证人
	 */
	public String getAssucustname() {
		return this.assucustname;
	}

	/**
	 * Set the 保证类型2.
	 * 
	 * @param ensukind2
	 *            保证类型2
	 */
	public void setEnsukind2(String ensukind2) {
		this.ensukind2 = ensukind2;
	}

	/**
	 * Get the 保证类型2.
	 * 
	 * @return 保证类型2
	 */
	public String getEnsukind2() {
		return this.ensukind2;
	}

	/**
	 * Set the 我行贷款余额.
	 * 
	 * @param ourloanbal
	 *            我行贷款余额
	 */
	public void setOurloanbal(Double ourloanbal) {
		this.ourloanbal = ourloanbal;
	}

	/**
	 * Get the 我行贷款余额.
	 * 
	 * @return 我行贷款余额
	 */
	public Double getOurloanbal() {
		return this.ourloanbal;
	}

	/**
	 * Set the 我行不良贷款额度.
	 * 
	 * @param ourbadbal
	 *            我行不良贷款额度
	 */
	public void setOurbadbal(Double ourbadbal) {
		this.ourbadbal = ourbadbal;
	}

	/**
	 * Get the 我行不良贷款额度.
	 * 
	 * @return 我行不良贷款额度
	 */
	public Double getOurbadbal() {
		return this.ourbadbal;
	}

	/**
	 * Set the 他行贷款余额.
	 * 
	 * @param otherloanbal
	 *            他行贷款余额
	 */
	public void setOtherloanbal(Double otherloanbal) {
		this.otherloanbal = otherloanbal;
	}

	/**
	 * Get the 他行贷款余额.
	 * 
	 * @return 他行贷款余额
	 */
	public Double getOtherloanbal() {
		return this.otherloanbal;
	}

	/**
	 * Set the 他行不良贷款额度.
	 * 
	 * @param otherbadbal
	 *            他行不良贷款额度
	 */
	public void setOtherbadbal(Double otherbadbal) {
		this.otherbadbal = otherbadbal;
	}

	/**
	 * Get the 他行不良贷款额度.
	 * 
	 * @return 他行不良贷款额度
	 */
	public Double getOtherbadbal() {
		return this.otherbadbal;
	}


}
