package com.gbicc.personCommon.entity;

import java.io.Serializable;

/**
 * Model class of 担保关联表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TEdwPlsGuarantCustMortgageRel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 业务编号. */
	private String loanid;

	/** 担保编号. */
	private String assuid;

	/** 担保物名称. */
	private String assuname;

	/** 关联类型. */
	private String regikind;

	/** 抵押类型. */
	private String assusort;

	/** 本次担保金额. */
	private Double assuamt;

	/** 担保率. */
	private Double assurate;

	/** 抵质押率. */
	private Double assurate2;

	/** 担保合同编号. */
	private String assucontno;

	/** 客户名称. */
	private String custname;

	/**
	 * Constructor.
	 */
	public TEdwPlsGuarantCustMortgageRel() {
	}

	/**
	 * Set the 业务编号.
	 * 
	 * @param loanid
	 *            业务编号
	 */
	public void setLoanid(String loanid) {
		this.loanid = loanid;
	}

	/**
	 * Get the 业务编号.
	 * 
	 * @return 业务编号
	 */
	public String getLoanid() {
		return this.loanid;
	}

	/**
	 * Set the 担保编号.
	 * 
	 * @param assuid
	 *            担保编号
	 */
	public void setAssuid(String assuid) {
		this.assuid = assuid;
	}

	/**
	 * Get the 担保编号.
	 * 
	 * @return 担保编号
	 */
	public String getAssuid() {
		return this.assuid;
	}

	/**
	 * Set the 担保物名称.
	 * 
	 * @param assuname
	 *            担保物名称
	 */
	public void setAssuname(String assuname) {
		this.assuname = assuname;
	}

	/**
	 * Get the 担保物名称.
	 * 
	 * @return 担保物名称
	 */
	public String getAssuname() {
		return this.assuname;
	}

	/**
	 * Set the 关联类型.
	 * 
	 * @param regikind
	 *            关联类型
	 */
	public void setRegikind(String regikind) {
		this.regikind = regikind;
	}

	/**
	 * Get the 关联类型.
	 * 
	 * @return 关联类型
	 */
	public String getRegikind() {
		return this.regikind;
	}

	/**
	 * Set the 抵押类型.
	 * 
	 * @param assusort
	 *            抵押类型
	 */
	public void setAssusort(String assusort) {
		this.assusort = assusort;
	}

	/**
	 * Get the 抵押类型.
	 * 
	 * @return 抵押类型
	 */
	public String getAssusort() {
		return this.assusort;
	}

	/**
	 * Set the 本次担保金额.
	 * 
	 * @param assuamt
	 *            本次担保金额
	 */
	public void setAssuamt(Double assuamt) {
		this.assuamt = assuamt;
	}

	/**
	 * Get the 本次担保金额.
	 * 
	 * @return 本次担保金额
	 */
	public Double getAssuamt() {
		return this.assuamt;
	}

	/**
	 * Set the 担保率.
	 * 
	 * @param assurate
	 *            担保率
	 */
	public void setAssurate(Double assurate) {
		this.assurate = assurate;
	}

	/**
	 * Get the 担保率.
	 * 
	 * @return 担保率
	 */
	public Double getAssurate() {
		return this.assurate;
	}

	/**
	 * Set the 抵质押率.
	 * 
	 * @param assurate2
	 *            抵质押率
	 */
	public void setAssurate2(Double assurate2) {
		this.assurate2 = assurate2;
	}

	/**
	 * Get the 抵质押率.
	 * 
	 * @return 抵质押率
	 */
	public Double getAssurate2() {
		return this.assurate2;
	}

	/**
	 * Set the 担保合同编号.
	 * 
	 * @param assucontno
	 *            担保合同编号
	 */
	public void setAssucontno(String assucontno) {
		this.assucontno = assucontno;
	}

	/**
	 * Get the 担保合同编号.
	 * 
	 * @return 担保合同编号
	 */
	public String getAssucontno() {
		return this.assucontno;
	}

	/**
	 * Set the 客户名称.
	 * 
	 * @param custname
	 *            客户名称
	 */
	public void setCustname(String custname) {
		this.custname = custname;
	}

	/**
	 * Get the 客户名称.
	 * 
	 * @return 客户名称
	 */
	public String getCustname() {
		return this.custname;
	}


}
