package com.gbicc.personCommon.entity;

import java.io.Serializable;

/**
 * Model class of 客户担保关系表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TEdwPlsGuarantCustAccRel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 账户ID. */
	private String loanacno;

	/** 客户编号. */
	private String custid;

	/** 客户名称. */
	private String custname;

	/** 担保客户编号. */
	private String guaranteecustid;

	/** 担保客户名称. */
	private String guaranteecustname;

	/** 是否相互担保. */
	private Boolean mutual;

	/**
	 * Constructor.
	 */
	public TEdwPlsGuarantCustAccRel() {
	}

	/**
	 * Set the 账户ID.
	 * 
	 * @param loanacno
	 *            账户ID
	 */
	public void setLoanacno(String loanacno) {
		this.loanacno = loanacno;
	}

	/**
	 * Get the 账户ID.
	 * 
	 * @return 账户ID
	 */
	public String getLoanacno() {
		return this.loanacno;
	}

	/**
	 * Set the 客户编号.
	 * 
	 * @param custid
	 *            客户编号
	 */
	public void setCustid(String custid) {
		this.custid = custid;
	}

	/**
	 * Get the 客户编号.
	 * 
	 * @return 客户编号
	 */
	public String getCustid() {
		return this.custid;
	}

	/**
	 * Set the 客户名称.
	 * 
	 * @param custname
	 *            客户名称
	 */
	public void setCustname(String custname) {
		this.custname = custname;
	}

	/**
	 * Get the 客户名称.
	 * 
	 * @return 客户名称
	 */
	public String getCustname() {
		return this.custname;
	}

	/**
	 * Set the 担保客户编号.
	 * 
	 * @param guaranteecustid
	 *            担保客户编号
	 */
	public void setGuaranteecustid(String guaranteecustid) {
		this.guaranteecustid = guaranteecustid;
	}

	/**
	 * Get the 担保客户编号.
	 * 
	 * @return 担保客户编号
	 */
	public String getGuaranteecustid() {
		return this.guaranteecustid;
	}

	/**
	 * Set the 担保客户名称.
	 * 
	 * @param guaranteecustname
	 *            担保客户名称
	 */
	public void setGuaranteecustname(String guaranteecustname) {
		this.guaranteecustname = guaranteecustname;
	}

	/**
	 * Get the 担保客户名称.
	 * 
	 * @return 担保客户名称
	 */
	public String getGuaranteecustname() {
		return this.guaranteecustname;
	}

	/**
	 * Set the 是否相互担保.
	 * 
	 * @param mutual
	 *            是否相互担保
	 */
	public void setMutual(Boolean mutual) {
		this.mutual = mutual;
	}

	/**
	 * Get the 是否相互担保.
	 * 
	 * @return 是否相互担保
	 */
	public Boolean getMutual() {
		return this.mutual;
	}


}
