package com.gbicc.personCommon.entity;

import java.io.Serializable;

/**
 * Model class of 实际控制人信息表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TEdwPlsController implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/*
    * 法人客户编号.
    */
    private String corpcustid;
    /*
    * 实际控制人编号.
    */
    private String controlid;
    /*
    * 实际控制人名称.
    */
    private String controlname;
    /*
    * 证件类型.
    */
    private String paperkind;
    /*
    * 证件号码.
    */
    private String paperid;

    public TEdwPlsController() {
    }

	
    public TEdwPlsController(String corpcustid) {
        this.corpcustid = corpcustid;
    }
    public TEdwPlsController(String corpcustid, String controlid, String controlname, String paperkind, String paperid) {
       this.corpcustid = corpcustid;
       this.controlid = controlid;
       this.controlname = controlname;
       this.paperkind = paperkind;
       this.paperid = paperid;
    }
   
	/**
    * Get the 法人客户编号
    */	
    public String getCorpcustid() {
        return this.corpcustid;
    }
	/**
    * Set the 法人客户编号
    */	
    public void setCorpcustid(String corpcustid) {
        this.corpcustid = corpcustid;
    }
	/**
    * Get the 实际控制人编号
    */	
    public String getControlid() {
        return this.controlid;
    }
	/**
    * Set the 实际控制人编号
    */	
    public void setControlid(String controlid) {
        this.controlid = controlid;
    }
	/**
    * Get the 实际控制人名称
    */	
    public String getControlname() {
        return this.controlname;
    }
	/**
    * Set the 实际控制人名称
    */	
    public void setControlname(String controlname) {
        this.controlname = controlname;
    }
	/**
    * Get the 证件类型
    */	
    public String getPaperkind() {
        return this.paperkind;
    }
	/**
    * Set the 证件类型
    */	
    public void setPaperkind(String paperkind) {
        this.paperkind = paperkind;
    }
	/**
    * Get the 证件号码
    */	
    public String getPaperid() {
        return this.paperid;
    }
	/**
    * Set the 证件号码
    */	
    public void setPaperid(String paperid) {
        this.paperid = paperid;
    }

}
