package com.gbicc.personCommon.entity;

import java.io.Serializable;

/**
 * Model class of 征信指标表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TPlCreditKpi implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/**
	 * Constructor.
	 */
	public TPlCreditKpi() {
	}


}
