package com.gbicc.personCommon.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 预警处置任务触发规则表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TPlTaskRuleTrig implements Serializable {


    /*
    * ID.
    */
    private String id;
    /*
     * 账户ID.
     */
    private String accId;
    /*
    * 规则标示.
    */
    private String ruleId;
    /*
    * 规则代码.
    */
    private String ruleCode;
    /*
    * 规则名称.
    */
    private String ruleName;
    /*
    * 规则描述.
    */
    private String ruleDesc;
    /*
    * 规则等级.
    */
    private String ruleRank;
    /*
    * 规则类型.
    */
    private String ruleType;
    /*
    * 规则适用对象.
    */
    private String ruleFor;
    /*
    * 规则触发类型.
    */
    private String ruleTrigType;
    /*
    * 规则触发周期.
    */
    private Integer ruleTrigPeriod;
    /*
    * 规则触发周期单位.
    */
    private String ruleTrigUnit;
    /*
    * 任务实际触发日期.
    */
    private Date trigDate;
    /*
    * 任务触发类型.
    */
    private Integer trigType;
    /*
    * 数据处理日期.
    */
    private Date processDate;

    public TPlTaskRuleTrig() {
    }

    public TPlTaskRuleTrig(String id,String accId, String ruleId, String ruleCode, String ruleName, String ruleDesc, String ruleRank, String ruleType, String ruleFor, String ruleTrigType, Integer ruleTrigPeriod, String ruleTrigUnit, Date trigDate, Integer trigType, Date processDate) {
       this.id = id;
       this.accId = accId;
       this.ruleId = ruleId;
       this.ruleCode = ruleCode;
       this.ruleName = ruleName;
       this.ruleDesc = ruleDesc;
       this.ruleRank = ruleRank;
       this.ruleType = ruleType;
       this.ruleFor = ruleFor;
       this.ruleTrigType = ruleTrigType;
       this.ruleTrigPeriod = ruleTrigPeriod;
       this.ruleTrigUnit = ruleTrigUnit;
       this.trigDate = trigDate;
       this.trigType = trigType;
       this.processDate = processDate;
    }
   
    public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAccId() {
        return this.accId;
    }
    
    public void setAccId(String accId) {
        this.accId = accId;
    }
    public String getRuleId() {
        return this.ruleId;
    }
    
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId;
    }
    public String getRuleCode() {
        return this.ruleCode;
    }
    
    public void setRuleCode(String ruleCode) {
        this.ruleCode = ruleCode;
    }
    public String getRuleName() {
        return this.ruleName;
    }
    
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }
    public String getRuleDesc() {
        return this.ruleDesc;
    }
    
    public void setRuleDesc(String ruleDesc) {
        this.ruleDesc = ruleDesc;
    }
    public String getRuleRank() {
        return this.ruleRank;
    }
    
    public void setRuleRank(String ruleRank) {
        this.ruleRank = ruleRank;
    }
    public String getRuleType() {
        return this.ruleType;
    }
    
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType;
    }
    public String getRuleFor() {
        return this.ruleFor;
    }
    
    public void setRuleFor(String ruleFor) {
        this.ruleFor = ruleFor;
    }
    public String getRuleTrigType() {
        return this.ruleTrigType;
    }
    
    public void setRuleTrigType(String ruleTrigType) {
        this.ruleTrigType = ruleTrigType;
    }
    public Integer getRuleTrigPeriod() {
        return this.ruleTrigPeriod;
    }
    
    public void setRuleTrigPeriod(Integer ruleTrigPeriod) {
        this.ruleTrigPeriod = ruleTrigPeriod;
    }
    public String getRuleTrigUnit() {
        return this.ruleTrigUnit;
    }
    
    public void setRuleTrigUnit(String ruleTrigUnit) {
        this.ruleTrigUnit = ruleTrigUnit;
    }
    public Date getTrigDate() {
        return this.trigDate;
    }
    
    public void setTrigDate(Date trigDate) {
        this.trigDate = trigDate;
    }
    public Integer getTrigType() {
        return this.trigType;
    }
    
    public void setTrigType(Integer trigType) {
        this.trigType = trigType;
    }
    public Date getProcessDate() {
        return this.processDate;
    }
    
    public void setProcessDate(Date processDate) {
        this.processDate = processDate;
    }


 

}
