package com.gbicc.personCommon.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 用途监控任务表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TPlTaskUsage implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 借据ID. */
	private String fdIouId;

	/** 借据发放日期. */
	private Date fdIouDisDate;

	/** 任务预计触发日期. */
	private Date fdTrigDateExpect;

	/** 任务实际触发日期. */
	private Date fdTrigDate;

	/** 借据额度使用标志. */
	private Integer fdUsedFlag;

	/** 任务触发类型. */
	private Integer fdTaskTrigType;

	/** 数据处理日期. */
	private Date fdProcessDate;

	/**
	 * Constructor.
	 */
	public TPlTaskUsage() {
	}

	/**
	 * Set the 借据ID.
	 * 
	 * @param fdIouId
	 *            借据ID
	 */
	public void setFdIouId(String fdIouId) {
		this.fdIouId = fdIouId;
	}

	/**
	 * Get the 借据ID.
	 * 
	 * @return 借据ID
	 */
	public String getFdIouId() {
		return this.fdIouId;
	}

	/**
	 * Set the 借据发放日期.
	 * 
	 * @param fdIouDisDate
	 *            借据发放日期
	 */
	public void setFdIouDisDate(Date fdIouDisDate) {
		this.fdIouDisDate = fdIouDisDate;
	}

	/**
	 * Get the 借据发放日期.
	 * 
	 * @return 借据发放日期
	 */
	public Date getFdIouDisDate() {
		return this.fdIouDisDate;
	}

	/**
	 * Set the 任务预计触发日期.
	 * 
	 * @param fdTrigDateExpect
	 *            任务预计触发日期
	 */
	public void setFdTrigDateExpect(Date fdTrigDateExpect) {
		this.fdTrigDateExpect = fdTrigDateExpect;
	}

	/**
	 * Get the 任务预计触发日期.
	 * 
	 * @return 任务预计触发日期
	 */
	public Date getFdTrigDateExpect() {
		return this.fdTrigDateExpect;
	}

	/**
	 * Set the 任务实际触发日期.
	 * 
	 * @param fdTrigDate
	 *            任务实际触发日期
	 */
	public void setFdTrigDate(Date fdTrigDate) {
		this.fdTrigDate = fdTrigDate;
	}

	/**
	 * Get the 任务实际触发日期.
	 * 
	 * @return 任务实际触发日期
	 */
	public Date getFdTrigDate() {
		return this.fdTrigDate;
	}

	/**
	 * Set the 借据额度使用标志.
	 * 
	 * @param fdUsedFlag
	 *            借据额度使用标志
	 */
	public void setFdUsedFlag(Integer fdUsedFlag) {
		this.fdUsedFlag = fdUsedFlag;
	}

	/**
	 * Get the 借据额度使用标志.
	 * 
	 * @return 借据额度使用标志
	 */
	public Integer getFdUsedFlag() {
		return this.fdUsedFlag;
	}

	/**
	 * Set the 任务触发类型.
	 * 
	 * @param fdTaskTrigType
	 *            任务触发类型
	 */
	public void setFdTaskTrigType(Integer fdTaskTrigType) {
		this.fdTaskTrigType = fdTaskTrigType;
	}

	/**
	 * Get the 任务触发类型.
	 * 
	 * @return 任务触发类型
	 */
	public Integer getFdTaskTrigType() {
		return this.fdTaskTrigType;
	}

	/**
	 * Set the 数据处理日期.
	 * 
	 * @param fdProcessDate
	 *            数据处理日期
	 */
	public void setFdProcessDate(Date fdProcessDate) {
		this.fdProcessDate = fdProcessDate;
	}

	/**
	 * Get the 数据处理日期.
	 * 
	 * @return 数据处理日期
	 */
	public Date getFdProcessDate() {
		return this.fdProcessDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fdIouId == null) ? 0 : fdIouId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TPlTaskUsage other = (TPlTaskUsage) obj;
		if (fdIouId == null) {
			if (other.fdIouId != null) {
				return false;
			}
		} else if (!fdIouId.equals(other.fdIouId)) {
			return false;
		}
		return true;
	}

}
