package com.gbicc.personCommon.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 催收任务表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TPlTaskDebtCollect implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 账户ID. */
	private String fdAccId;

	/** 账户状态. */
	private Integer fdAccStatus;

	/** 逾期开始日期. */
	private Date fdOverStartDate;

	/** 产品代码. */
	private String fdProductCode;

	/** 账龄. */
	private Integer fdAccAge;

	/** 催收级别. */
	private Integer fdCollectRank;

	/** 催收次数. */
	private Integer fdCollectCount;

	/** 预计还款日期. */
	private Date fdExpPayDate;

	/** 任务实际触发日期. */
	private Date fdTrigDate;

	/** 数据处理日期. */
	private Date fdProcessDate;

	/**
	 * Constructor.
	 */
	public TPlTaskDebtCollect() {
	}

	/**
	 * Set the 账户ID.
	 * 
	 * @param fdAccId
	 *            账户ID
	 */
	public void setFdAccId(String fdAccId) {
		this.fdAccId = fdAccId;
	}

	/**
	 * Get the 账户ID.
	 * 
	 * @return 账户ID
	 */
	public String getFdAccId() {
		return this.fdAccId;
	}

	/**
	 * Set the 账户状态.
	 * 
	 * @param fdAccStatus
	 *            账户状态
	 */
	public void setFdAccStatus(Integer fdAccStatus) {
		this.fdAccStatus = fdAccStatus;
	}

	/**
	 * Get the 账户状态.
	 * 
	 * @return 账户状态
	 */
	public Integer getFdAccStatus() {
		return this.fdAccStatus;
	}

	/**
	 * Set the 逾期开始日期.
	 * 
	 * @param fdOverStartDate
	 *            逾期开始日期
	 */
	public void setFdOverStartDate(Date fdOverStartDate) {
		this.fdOverStartDate = fdOverStartDate;
	}

	/**
	 * Get the 逾期开始日期.
	 * 
	 * @return 逾期开始日期
	 */
	public Date getFdOverStartDate() {
		return this.fdOverStartDate;
	}

	/**
	 * Set the 产品代码.
	 * 
	 * @param fdProductCode
	 *            产品代码
	 */
	public void setFdProductCode(String fdProductCode) {
		this.fdProductCode = fdProductCode;
	}

	/**
	 * Get the 产品代码.
	 * 
	 * @return 产品代码
	 */
	public String getFdProductCode() {
		return this.fdProductCode;
	}

	/**
	 * Set the 账龄.
	 * 
	 * @param fdAccAge
	 *            账龄
	 */
	public void setFdAccAge(Integer fdAccAge) {
		this.fdAccAge = fdAccAge;
	}

	/**
	 * Get the 账龄.
	 * 
	 * @return 账龄
	 */
	public Integer getFdAccAge() {
		return this.fdAccAge;
	}

	/**
	 * Set the 催收级别.
	 * 
	 * @param fdCollectRank
	 *            催收级别
	 */
	public void setFdCollectRank(Integer fdCollectRank) {
		this.fdCollectRank = fdCollectRank;
	}

	/**
	 * Get the 催收级别.
	 * 
	 * @return 催收级别
	 */
	public Integer getFdCollectRank() {
		return this.fdCollectRank;
	}

	/**
	 * Set the 催收次数.
	 * 
	 * @param fdCollectCount
	 *            催收次数
	 */
	public void setFdCollectCount(Integer fdCollectCount) {
		this.fdCollectCount = fdCollectCount;
	}

	/**
	 * Get the 催收次数.
	 * 
	 * @return 催收次数
	 */
	public Integer getFdCollectCount() {
		return this.fdCollectCount;
	}

	/**
	 * Set the 预计还款日期.
	 * 
	 * @param fdExpPayDate
	 *            预计还款日期
	 */
	public void setFdExpPayDate(Date fdExpPayDate) {
		this.fdExpPayDate = fdExpPayDate;
	}

	/**
	 * Get the 预计还款日期.
	 * 
	 * @return 预计还款日期
	 */
	public Date getFdExpPayDate() {
		return this.fdExpPayDate;
	}

	/**
	 * Set the 任务实际触发日期.
	 * 
	 * @param fdTrigDate
	 *            任务实际触发日期
	 */
	public void setFdTrigDate(Date fdTrigDate) {
		this.fdTrigDate = fdTrigDate;
	}

	/**
	 * Get the 任务实际触发日期.
	 * 
	 * @return 任务实际触发日期
	 */
	public Date getFdTrigDate() {
		return this.fdTrigDate;
	}

	/**
	 * Set the 数据处理日期.
	 * 
	 * @param fdProcessDate
	 *            数据处理日期
	 */
	public void setFdProcessDate(Date fdProcessDate) {
		this.fdProcessDate = fdProcessDate;
	}

	/**
	 * Get the 数据处理日期.
	 * 
	 * @return 数据处理日期
	 */
	public Date getFdProcessDate() {
		return this.fdProcessDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fdAccId == null) ? 0 : fdAccId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TPlTaskDebtCollect other = (TPlTaskDebtCollect) obj;
		if (fdAccId == null) {
			if (other.fdAccId != null) {
				return false;
			}
		} else if (!fdAccId.equals(other.fdAccId)) {
			return false;
		}
		return true;
	}

}
