package com.gbicc.bpm.entity;
// Generated 2015-11-20 10:40:44 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.huateng.ebank.entity.data.mng.Bctl;
import com.huateng.ebank.entity.data.mng.TlrInfo;

/**
 * TTaskDivert generated by hbm2java
 */
public class TTaskDivert  implements java.io.Serializable {

	private static final long serialVersionUID = 4039952522431602359L;
	
	/*
    * ID主键.
    */
    private String id;
    /*
    * 申请时间.
    */
    private Date aplDate;
    /*
    * 申请人.
    */
    private TlrInfo aplPer;
    /*
    * 现任务处理人.
    */
    private TlrInfo assignee;
    /*
    * 原任务处理人.
    */
    private TlrInfo oldAssignee;
    /*
    * 审批通过时间.
    */
    private Date passDate;
    /*
    * 状态（0：审核中，1审核通过）.
    */
    private String status;
    
    private Bctl assigneeOrg;
    private Bctl oldAssigneeOrg;

    public TTaskDivert() {
    }

	
    public TTaskDivert(String id) {
        this.id = id;
    }
    public TTaskDivert(String id, Date aplDate, TlrInfo aplPer, TlrInfo assignee, TlrInfo oldAssignee, Date passDate, String status) {
       this.id = id;
       this.aplDate = aplDate;
       this.aplPer = aplPer;
       this.assignee = assignee;
       this.oldAssignee = oldAssignee;
       this.passDate = passDate;
       this.status = status;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Date getAplDate() {
        return this.aplDate;
    }
    
    public void setAplDate(Date aplDate) {
        this.aplDate = aplDate;
    }
    public TlrInfo getAplPer() {
        return this.aplPer;
    }
    
    public void setAplPer(TlrInfo aplPer) {
        this.aplPer = aplPer;
    }
    public TlrInfo getAssignee() {
        return this.assignee;
    }
    
    public void setAssignee(TlrInfo assignee) {
        this.assignee = assignee;
    }
    public TlrInfo getOldAssignee() {
        return this.oldAssignee;
    }
    
    public void setOldAssignee(TlrInfo oldAssignee) {
        this.oldAssignee = oldAssignee;
    }
    public Date getPassDate() {
        return this.passDate;
    }
    
    public void setPassDate(Date passDate) {
        this.passDate = passDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

	public Bctl getAssigneeOrg() {
		return assigneeOrg;
	}
	public void setAssigneeOrg(Bctl assigneeOrg) {
		this.assigneeOrg = assigneeOrg;
	}

	public Bctl getOldAssigneeOrg() {
		return oldAssigneeOrg;
	}
	public void setOldAssigneeOrg(Bctl oldAssigneeOrg) {
		this.oldAssigneeOrg = oldAssigneeOrg;
	}
}