package com.gbicc.company.view.accountpage.entity;

import java.math.BigDecimal;
import java.util.Date;

// default package
// Generated 2016-8-16 8:24:36 by Hibernate Tools 3.4.0.CR1

/**
 * TOdsEdwDepositAcctTxnDtlInfo generated by hbm2java
 */
public class TOdsEdwDepositAcctTxnDtlInfo implements java.io.Serializable {

	private TOdsEdwDepositAcctTxnDtlInfoId id;
	private String txnDt;
	private String inacctDt;
	private String txnTm;
	private String acctId;
	private String aioAccntAcctId;
	private String cardId;
	private String cardTypeSelfServEquip;
	private String custId;
	private String prodId;
	private String itemId;
	private String acctOrg;
	private BigDecimal bal;
	private String acctAttri;
	private BigDecimal cardBal;
	private String oppoAcctId;
	private String oppoCustNm;
	private String oppoBank;
	private String oppoTxnCcy;
	private String txnOrg;
	private String txnTlr;
	private String authTlr;
	private String tmlId;
	private String txnCateg;
	private String txnSrcSelfServEquip;
	private String txnChn;
	private String txnCd;
	private String ccy;
	private BigDecimal txnAmt;
	private BigDecimal txnAftrBal;
	private BigDecimal txnInt;
	private BigDecimal fee;
	private String txnAbstr;
	private String rvsAcctInd;
	private String validInd;
	private String debCrdInd;
	private String curTransInd;
	private String txnSucceInd;
	private String uuid;
	private String outSysCd;
	private String chnSerialId;
	private String outSerialId;
	private String agentBank;
	private String nonCardPayInd;
	private String withdrInd;
	private String fincInd;
	private String merchantTypeCd;
	private Date etlProcDt;
	private String chineseName;
	private String txnSerialId;
	public TOdsEdwDepositAcctTxnDtlInfo() {
	}

	public TOdsEdwDepositAcctTxnDtlInfo(TOdsEdwDepositAcctTxnDtlInfoId id) {
		this.id = id;
	}

	public TOdsEdwDepositAcctTxnDtlInfoId getId() {
		return this.id;
	}

	public void setId(TOdsEdwDepositAcctTxnDtlInfoId id) {
		this.id = id;
	}

	public String getTxnDt() {
		return txnDt;
	}

	public void setTxnDt(String txnDt) {
		this.txnDt = txnDt;
	}

	public String getInacctDt() {
		return inacctDt;
	}

	public void setInacctDt(String inacctDt) {
		this.inacctDt = inacctDt;
	}

	public String getTxnTm() {
		return txnTm;
	}

	public void setTxnTm(String txnTm) {
		this.txnTm = txnTm;
	}

	public String getAcctId() {
		return acctId;
	}

	public void setAcctId(String acctId) {
		this.acctId = acctId;
	}

	public String getAioAccntAcctId() {
		return aioAccntAcctId;
	}

	public void setAioAccntAcctId(String aioAccntAcctId) {
		this.aioAccntAcctId = aioAccntAcctId;
	}

	public String getCardId() {
		return cardId;
	}

	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

	public String getCardTypeSelfServEquip() {
		return cardTypeSelfServEquip;
	}

	public void setCardTypeSelfServEquip(String cardTypeSelfServEquip) {
		this.cardTypeSelfServEquip = cardTypeSelfServEquip;
	}

	public String getCustId() {
		return custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	public String getProdId() {
		return prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	public String getItemId() {
		return itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	public String getAcctOrg() {
		return acctOrg;
	}

	public void setAcctOrg(String acctOrg) {
		this.acctOrg = acctOrg;
	}

	public BigDecimal getBal() {
		return bal;
	}

	public void setBal(BigDecimal bal) {
		this.bal = bal;
	}

	public String getAcctAttri() {
		return acctAttri;
	}

	public void setAcctAttri(String acctAttri) {
		this.acctAttri = acctAttri;
	}

	public BigDecimal getCardBal() {
		return cardBal;
	}

	public void setCardBal(BigDecimal cardBal) {
		this.cardBal = cardBal;
	}

	public String getOppoAcctId() {
		return oppoAcctId;
	}

	public void setOppoAcctId(String oppoAcctId) {
		this.oppoAcctId = oppoAcctId;
	}

	public String getOppoCustNm() {
		return oppoCustNm;
	}

	public void setOppoCustNm(String oppoCustNm) {
		this.oppoCustNm = oppoCustNm;
	}

	public String getOppoBank() {
		return oppoBank;
	}

	public void setOppoBank(String oppoBank) {
		this.oppoBank = oppoBank;
	}

	public String getOppoTxnCcy() {
		return oppoTxnCcy;
	}

	public void setOppoTxnCcy(String oppoTxnCcy) {
		this.oppoTxnCcy = oppoTxnCcy;
	}

	public String getTxnOrg() {
		return txnOrg;
	}

	public void setTxnOrg(String txnOrg) {
		this.txnOrg = txnOrg;
	}

	public String getTxnTlr() {
		return txnTlr;
	}

	public void setTxnTlr(String txnTlr) {
		this.txnTlr = txnTlr;
	}

	public String getAuthTlr() {
		return authTlr;
	}

	public void setAuthTlr(String authTlr) {
		this.authTlr = authTlr;
	}

	public String getTmlId() {
		return tmlId;
	}

	public void setTmlId(String tmlId) {
		this.tmlId = tmlId;
	}

	public String getTxnCateg() {
		return txnCateg;
	}

	public void setTxnCateg(String txnCateg) {
		this.txnCateg = txnCateg;
	}

	public String getTxnSrcSelfServEquip() {
		return txnSrcSelfServEquip;
	}

	public void setTxnSrcSelfServEquip(String txnSrcSelfServEquip) {
		this.txnSrcSelfServEquip = txnSrcSelfServEquip;
	}

	public String getTxnChn() {
		return txnChn;
	}

	public void setTxnChn(String txnChn) {
		this.txnChn = txnChn;
	}

	public String getTxnCd() {
		return txnCd;
	}

	public void setTxnCd(String txnCd) {
		this.txnCd = txnCd;
	}

	public String getCcy() {
		return ccy;
	}

	public void setCcy(String ccy) {
		this.ccy = ccy;
	}

	public BigDecimal getTxnAmt() {
		return txnAmt;
	}

	public void setTxnAmt(BigDecimal txnAmt) {
		this.txnAmt = txnAmt;
	}

	public BigDecimal getTxnAftrBal() {
		return txnAftrBal;
	}

	public void setTxnAftrBal(BigDecimal txnAftrBal) {
		this.txnAftrBal = txnAftrBal;
	}

	public BigDecimal getTxnInt() {
		return txnInt;
	}

	public void setTxnInt(BigDecimal txnInt) {
		this.txnInt = txnInt;
	}

	public BigDecimal getFee() {
		return fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	public String getTxnAbstr() {
		return txnAbstr;
	}

	public void setTxnAbstr(String txnAbstr) {
		this.txnAbstr = txnAbstr;
	}

	public String getRvsAcctInd() {
		return rvsAcctInd;
	}

	public void setRvsAcctInd(String rvsAcctInd) {
		this.rvsAcctInd = rvsAcctInd;
	}

	public String getValidInd() {
		return validInd;
	}

	public void setValidInd(String validInd) {
		this.validInd = validInd;
	}

	public String getDebCrdInd() {
		return debCrdInd;
	}

	public void setDebCrdInd(String debCrdInd) {
		this.debCrdInd = debCrdInd;
	}

	public String getCurTransInd() {
		return curTransInd;
	}

	public void setCurTransInd(String curTransInd) {
		this.curTransInd = curTransInd;
	}

	public String getTxnSucceInd() {
		return txnSucceInd;
	}

	public void setTxnSucceInd(String txnSucceInd) {
		this.txnSucceInd = txnSucceInd;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getOutSysCd() {
		return outSysCd;
	}

	public void setOutSysCd(String outSysCd) {
		this.outSysCd = outSysCd;
	}

	public String getChnSerialId() {
		return chnSerialId;
	}

	public void setChnSerialId(String chnSerialId) {
		this.chnSerialId = chnSerialId;
	}

	public String getOutSerialId() {
		return outSerialId;
	}

	public void setOutSerialId(String outSerialId) {
		this.outSerialId = outSerialId;
	}

	public String getAgentBank() {
		return agentBank;
	}

	public void setAgentBank(String agentBank) {
		this.agentBank = agentBank;
	}

	public String getNonCardPayInd() {
		return nonCardPayInd;
	}

	public void setNonCardPayInd(String nonCardPayInd) {
		this.nonCardPayInd = nonCardPayInd;
	}

	public String getWithdrInd() {
		return withdrInd;
	}

	public void setWithdrInd(String withdrInd) {
		this.withdrInd = withdrInd;
	}

	public String getFincInd() {
		return fincInd;
	}

	public void setFincInd(String fincInd) {
		this.fincInd = fincInd;
	}

	public String getMerchantTypeCd() {
		return merchantTypeCd;
	}

	public void setMerchantTypeCd(String merchantTypeCd) {
		this.merchantTypeCd = merchantTypeCd;
	}

	public Date getEtlProcDt() {
		return etlProcDt;
	}

	public void setEtlProcDt(Date etlProcDt) {
		this.etlProcDt = etlProcDt;
	}

	public String getChineseName() {
		return chineseName;
	}

	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	public String getTxnSerialId() {
		return id.getTxnSerialId();
	}

	public void setTxnSerialId(String txnSerialId) {
		this.txnSerialId = id.getTxnSerialId();
	}


}
