package com.gbicc.person.eliminate.entity;
// Generated 2015-11-13 15:16:27 by Hibernate Tools 3.2.2.GA



/**
 * TPlRuleEliminateDtl generated by hbm2java
 */
public class TPlRuleEliminateDtl  implements java.io.Serializable {

	private static final long serialVersionUID = 2062708409902572714L;
	
	/*
    * ID主键.
    */
    private String id;
    /*
    * 规则排除表ID.
    */
    private String ruleElimId;
    /*
    * 规则ID.
    */
    private String ruleId;
    /*
     * 标识
     */
     private String flag;

    public TPlRuleEliminateDtl() {
    }
	
    public TPlRuleEliminateDtl(String id) {
        this.id = id;
    }
    public TPlRuleEliminateDtl(String id, String ruleElimId, String ruleId) {
       this.id = id;
       this.ruleElimId = ruleElimId;
       this.ruleId = ruleId;
    }
   
    public String getId() {
        return this.id;
    }
    public void setId(String id) {
        this.id = id;
    }
    
    public String getRuleElimId() {
        return this.ruleElimId;
    }
    public void setRuleElimId(String ruleElimId) {
        this.ruleElimId = ruleElimId;
    }
    
    public String getRuleId() {
        return this.ruleId;
    }
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId;
    }

	public String getFlag() {
		return flag;
	}
	public void setFlag(String flag) {
		this.flag = flag;
	}
}


