package com.gbicc.company.view.externaldata.entity;

import java.util.Date;

// default package
// Generated 2016-5-31 9:15:50 by Hibernate Tools 3.4.0.CR1

/**
 * TDataGsxtIcPunishment generated by hbm2java
 */
public class TDataGsxtIcPunishment implements java.io.Serializable {
	
	private String id;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	private int fdEntId;
	private Integer fdSequence;
	private String fdPunishmentDocNum;
	private String fdPunishmentType;
	private String fdPunishmentContent;
	private String fdPunishmentOrg;
	private String fdPunishmentDate;
	private Date fdUpdateTime;
	private String fdJbkId;
	private String fdRegNum;
	private String fdName;
	private String fdType;
	private String fdLecalPerson;
	private String fdRegCapital;
	private String fdSetUpDate;
	private String fdEntAddress;
	private String fdBusinessTermStart;
	private String fdBusinessTermEnd;
	private String fdBusinessScope;
	private String fdRegOrg;
	private String fdApprovalDate;
	private String fdRegStatus;
	public int getFdEntId() {
		return fdEntId;
	}
	public void setFdEntId(int fdEntId) {
		this.fdEntId = fdEntId;
	}
	public Integer getFdSequence() {
		return fdSequence;
	}
	public void setFdSequence(Integer fdSequence) {
		this.fdSequence = fdSequence;
	}
	public String getFdPunishmentDocNum() {
		return fdPunishmentDocNum;
	}
	public void setFdPunishmentDocNum(String fdPunishmentDocNum) {
		this.fdPunishmentDocNum = fdPunishmentDocNum;
	}
	public String getFdPunishmentType() {
		return fdPunishmentType;
	}
	public void setFdPunishmentType(String fdPunishmentType) {
		this.fdPunishmentType = fdPunishmentType;
	}
	public String getFdPunishmentContent() {
		return fdPunishmentContent;
	}
	public void setFdPunishmentContent(String fdPunishmentContent) {
		this.fdPunishmentContent = fdPunishmentContent;
	}
	public String getFdPunishmentOrg() {
		return fdPunishmentOrg;
	}
	public void setFdPunishmentOrg(String fdPunishmentOrg) {
		this.fdPunishmentOrg = fdPunishmentOrg;
	}
	public String getFdPunishmentDate() {
		return fdPunishmentDate;
	}
	public void setFdPunishmentDate(String fdPunishmentDate) {
		this.fdPunishmentDate = fdPunishmentDate;
	}
	public Date getFdUpdateTime() {
		return fdUpdateTime;
	}
	public void setFdUpdateTime(Date fdUpdateTime) {
		this.fdUpdateTime = fdUpdateTime;
	}
	public String getFdJbkId() {
		return fdJbkId;
	}
	public void setFdJbkId(String fdJbkId) {
		this.fdJbkId = fdJbkId;
	}
	public String getFdRegNum() {
		return fdRegNum;
	}
	public void setFdRegNum(String fdRegNum) {
		this.fdRegNum = fdRegNum;
	}
	public String getFdName() {
		return fdName;
	}
	public void setFdName(String fdName) {
		this.fdName = fdName;
	}
	public String getFdType() {
		return fdType;
	}
	public void setFdType(String fdType) {
		this.fdType = fdType;
	}
	public String getFdLecalPerson() {
		return fdLecalPerson;
	}
	public void setFdLecalPerson(String fdLecalPerson) {
		this.fdLecalPerson = fdLecalPerson;
	}
	public String getFdRegCapital() {
		return fdRegCapital;
	}
	public void setFdRegCapital(String fdRegCapital) {
		this.fdRegCapital = fdRegCapital;
	}
	public String getFdSetUpDate() {
		return fdSetUpDate;
	}
	public void setFdSetUpDate(String fdSetUpDate) {
		this.fdSetUpDate = fdSetUpDate;
	}
	public String getFdEntAddress() {
		return fdEntAddress;
	}
	public void setFdEntAddress(String fdEntAddress) {
		this.fdEntAddress = fdEntAddress;
	}
	public String getFdBusinessTermStart() {
		return fdBusinessTermStart;
	}
	public void setFdBusinessTermStart(String fdBusinessTermStart) {
		this.fdBusinessTermStart = fdBusinessTermStart;
	}
	public String getFdBusinessTermEnd() {
		return fdBusinessTermEnd;
	}
	public void setFdBusinessTermEnd(String fdBusinessTermEnd) {
		this.fdBusinessTermEnd = fdBusinessTermEnd;
	}
	public String getFdBusinessScope() {
		return fdBusinessScope;
	}
	public void setFdBusinessScope(String fdBusinessScope) {
		this.fdBusinessScope = fdBusinessScope;
	}
	public String getFdRegOrg() {
		return fdRegOrg;
	}
	public void setFdRegOrg(String fdRegOrg) {
		this.fdRegOrg = fdRegOrg;
	}
	public String getFdApprovalDate() {
		return fdApprovalDate;
	}
	public void setFdApprovalDate(String fdApprovalDate) {
		this.fdApprovalDate = fdApprovalDate;
	}
	public String getFdRegStatus() {
		return fdRegStatus;
	}
	public void setFdRegStatus(String fdRegStatus) {
		this.fdRegStatus = fdRegStatus;
	}

}
