package com.gbicc.company.single.entity;
// Generated 2015-12-2 15:44:31 by Hibernate Tools 3.2.2.GA



/**
 * TCmSingleRulInveRelWarning generated by hbm2java
 */
public class TCmSingleRulInveRelWarning  implements java.io.Serializable {

	private static final long serialVersionUID = -4322543034249834035L;
	
	/*
    * ID主键.
    */
    private String id;
    /*
    * 协查任务ID.
    */
    private String inveId;
    /*
    * 预警信号ID.
    */
    private String warningId;

    public TCmSingleRulInveRelWarning() {
    }

    public TCmSingleRulInveRelWarning(String id) {
        this.id = id;
    }
    public TCmSingleRulInveRelWarning(String id, String inveId, String warningId) {
       this.id = id;
       this.inveId = inveId;
       this.warningId = warningId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getInveId() {
        return this.inveId;
    }
    
    public void setInveId(String inveId) {
        this.inveId = inveId;
    }
    public String getWarningId() {
        return this.warningId;
    }
    
    public void setWarningId(String warningId) {
        this.warningId = warningId;
    }
}