package com.gbicc.company.single.entity;
// Generated 2015-12-1 17:43:52 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import com.huateng.ebank.entity.data.mng.Bctl;
import com.huateng.ebank.entity.data.mng.TlrInfo;

/**
 * TCmSingleRulInvestigation generated by hbm2java
 */
public class TCmSingleRulInvestigation  implements java.io.Serializable {

	private static final long serialVersionUID = -2075761880530590541L;
	
	/*
    * ID主键.
    */
    private String id;
    /*
    * 协查任务编号.
    */
    private String inveCode;
    /*
    * 协查任务名称.
    */
    private String inveName;
    /*
    * 协查机构.
    */
    private Bctl inveOrg;
    /*
    * 协查内容.
    */
    private String inveCont;
    /*
    * 协查任务状态.
    */
    private String status;
    /*
    * 案例表ID.
    */
    private String casesId;
    /*
    * 核查重点.
    */
    private String checkEmph;
    /*
    * 协查方式.
    */
    private String inveWay;
    /*
    * 协查结论.
    */
    private String inveConc;
    /*
    * 协查反馈时间.
    */
    private Date inveFeedDt;
    /*
    * 协查意见.
    */
    private String inveOpin;
    /*
    * 创建时间.
    */
    private Date createDt;
    /*
    * 创建机构.
    */
    private Bctl createOrg;
    /*
    * 创建人.
    */
    private TlrInfo createUser;
    /*
    * 协查人员.
    */
    private TlrInfo inveUser;
    /*
    * 参与协查人员.
    */
    private String partUser;
    /*
    * 任务到期日.
    */
    private Date matureDt;
    /*
     * 协查次数
     */
    private Integer inveNumb;
    /*
     * 重调查发起日期
     */
    private Date againCreateDt;
    /*
     * 重调查任务到期日期
     */
    private Date againMatureDt;
    /*
     * 重调查发起人
     */
    private TlrInfo againCreateUser;
    /*
     * 重调查意见
     */
    private String againOpinion;
    /*
     * 保存标记
     */
    private String saveFlag;
    
    public TCmSingleRulInvestigation() {
    }

    public TCmSingleRulInvestigation(String id) {
        this.id = id;
    }
    public TCmSingleRulInvestigation(String id, String inveCode, String inveName, Bctl inveOrg, String inveCont, String status, String casesId, String checkEmph, String inveWay, String inveConc, Date inveFeedDt, String inveOpin, Date createDt, Bctl createOrg, TlrInfo createUser, TlrInfo inveUser, String partUser, Date matureDt) {
       this.id = id;
       this.inveCode = inveCode;
       this.inveName = inveName;
       this.inveOrg = inveOrg;
       this.inveCont = inveCont;
       this.status = status;
       this.casesId = casesId;
       this.checkEmph = checkEmph;
       this.inveWay = inveWay;
       this.inveConc = inveConc;
       this.inveFeedDt = inveFeedDt;
       this.inveOpin = inveOpin;
       this.createDt = createDt;
       this.createOrg = createOrg;
       this.createUser = createUser;
       this.inveUser = inveUser;
       this.partUser = partUser;
       this.matureDt = matureDt;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getInveCode() {
        return this.inveCode;
    }
    
    public void setInveCode(String inveCode) {
        this.inveCode = inveCode;
    }
    public String getInveName() {
        return this.inveName;
    }
    
    public void setInveName(String inveName) {
        this.inveName = inveName;
    }
    public Bctl getInveOrg() {
        return this.inveOrg;
    }
    
    public void setInveOrg(Bctl inveOrg) {
        this.inveOrg = inveOrg;
    }
    public String getInveCont() {
        return this.inveCont;
    }
    
    public void setInveCont(String inveCont) {
        this.inveCont = inveCont;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getCasesId() {
        return this.casesId;
    }
    
    public void setCasesId(String casesId) {
        this.casesId = casesId;
    }
    public String getCheckEmph() {
        return this.checkEmph;
    }
    
    public void setCheckEmph(String checkEmph) {
        this.checkEmph = checkEmph;
    }
    public String getInveWay() {
        return this.inveWay;
    }
    
    public void setInveWay(String inveWay) {
        this.inveWay = inveWay;
    }
    public String getInveConc() {
        return this.inveConc;
    }
    
    public void setInveConc(String inveConc) {
        this.inveConc = inveConc;
    }
    public Date getInveFeedDt() {
        return this.inveFeedDt;
    }
    
    public void setInveFeedDt(Date inveFeedDt) {
        this.inveFeedDt = inveFeedDt;
    }
    public String getInveOpin() {
        return this.inveOpin;
    }
    
    public void setInveOpin(String inveOpin) {
        this.inveOpin = inveOpin;
    }
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }
    public Bctl getCreateOrg() {
        return this.createOrg;
    }
    
    public void setCreateOrg(Bctl createOrg) {
        this.createOrg = createOrg;
    }
    public TlrInfo getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(TlrInfo createUser) {
        this.createUser = createUser;
    }
    public TlrInfo getInveUser() {
        return this.inveUser;
    }
    
    public void setInveUser(TlrInfo inveUser) {
        this.inveUser = inveUser;
    }
    public String getPartUser() {
        return this.partUser;
    }
    
    public void setPartUser(String partUser) {
        this.partUser = partUser;
    }
    public Date getMatureDt() {
        return this.matureDt;
    }
    
    public void setMatureDt(Date matureDt) {
        this.matureDt = matureDt;
    }

	public Integer getInveNumb() {
		return inveNumb;
	}
	public void setInveNumb(Integer inveNumb) {
		this.inveNumb = inveNumb;
	}

	public Date getAgainCreateDt() {
		return againCreateDt;
	}

	public void setAgainCreateDt(Date againCreateDt) {
		this.againCreateDt = againCreateDt;
	}

	public Date getAgainMatureDt() {
		return againMatureDt;
	}

	public void setAgainMatureDt(Date againMatureDt) {
		this.againMatureDt = againMatureDt;
	}

	public TlrInfo getAgainCreateUser() {
		return againCreateUser;
	}

	public void setAgainCreateUser(TlrInfo againCreateUser) {
		this.againCreateUser = againCreateUser;
	}

	public String getAgainOpinion() {
		return againOpinion;
	}

	public void setAgainOpinion(String againOpinion) {
		this.againOpinion = againOpinion;
	}

	public String getSaveFlag() {
		return saveFlag;
	}

	public void setSaveFlag(String saveFlag) {
		this.saveFlag = saveFlag;
	}
}


