package com.gbicc.company.single.entity;
// Generated 2015-12-1 17:43:52 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * TCmSingleRulInvestigation generated by hbm2java
 */
public class TCmSingleRulInveHist  implements java.io.Serializable {

	private static final long serialVersionUID = -2075761880530590541L;
	
	/**
    * ID主键.
    */
    private String id;
    /**
     * 协查ID
     */
    private String inveId;
    /**
     * 核查重点
     */
    private String checkEmph;
    /**
     * 协查方式
     */
    private String inveWay;
    /**
     * 参与协查人员
     */
    private String partUser;
    /**
     * 协查反馈时间
     */
    private Date inveFeedDt;
    /**
     * 协查结论
     */
    private String inveConc;
    
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	public String getInveId() {
		return inveId;
	}
	public void setInveId(String inveId) {
		this.inveId = inveId;
	}
	
	public String getCheckEmph() {
		return checkEmph;
	}
	public void setCheckEmph(String checkEmph) {
		this.checkEmph = checkEmph;
	}
	
	public String getInveWay() {
		return inveWay;
	}
	public void setInveWay(String inveWay) {
		this.inveWay = inveWay;
	}
	
	public String getPartUser() {
		return partUser;
	}
	public void setPartUser(String partUser) {
		this.partUser = partUser;
	}
	
	public Date getInveFeedDt() {
		return inveFeedDt;
	}
	public void setInveFeedDt(Date inveFeedDt) {
		this.inveFeedDt = inveFeedDt;
	}
	
	public String getInveConc() {
		return inveConc;
	}
	public void setInveConc(String inveConc) {
		this.inveConc = inveConc;
	}
}