package com.gbicc.personCommon.entity;
// Generated 2016-1-8 9:37:26 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * TEdwPlsAccount generated by hbm2java
 */
public class TEdwPlsAccount  implements java.io.Serializable {

	private static final long serialVersionUID = 7878095355761945289L;
	
	/*
	    * 账户ID.
	    */
	    private String loanacno;
	    /*
	    * 业务编号.
	    */
	    private String loanid;
	    /*
	    * 客户编号.
	    */
	    private String custid;
	    /*
	    * 客户名称.
	    */
	    private String custname;
	    /*
	    * 法人客户编号.
	    */
	    private String corpcustid;
	    /*
	    * 产品类型.
	    */
	    private String prodid;
	    /*
	    * 产品名称.
	    */
	    private String prodname;
	    /*
	    * 贷款金额.
	    */
	    private BigDecimal tcapi;
	    /*
	    * 贷款期限.
	    */
	    private Integer tterm;
	    /*
	    * 还款方式.
	    */
	    private String retukind;
	    /*
	    * 凭证编号.
	    */
	    private String warrno;
	    /*
	    * 入库编号.
	    */
	    private String enstroid;
	    /*
	    * 权证入库日期.
	    */
	    private Date warrbusidate;
	    /*
	    * 总押品价值.
	    */
	    private BigDecimal totalMortgageValue;
	    /*
	    * 是否结清.
	    */
	    private String payoffflag;
	    /*
	    * 联保小组名称.
	    */
	    private String unprofname;
	    /*
	    * 开户日期.
	    */
	    private Date begindate;
	    /*
	    * 到期日期.
	    */
	    private Date enddate;
	    /*
	    * 经办人.
	    */
	    private String operid;
	    /*
	    * 经办人名称.
	    */
	    private String opername;
	    /*
	    * 经办行.
	    */
	    private String bankid;
	    /*
	    * 经办行名称.
	    */
	    private String bankname;
	    /*
	    * 担保方式.
	    */
	    private String assukind;
	    /*
	    * 浮动比例.
	    */
	    private BigDecimal floatinterate;
	    /*
	    * 账户状态.
	    */
	    private String acflag;
	    /*
	    * 账户状态2.
	    */
	    private String acflag2;
	    /*
	    * 风险分类.
	    */
	    private String riskflag;
	    /*
	    * 合同编号.
	    */
	    private String contno;
	    /*
	    * 检查人编号.
	    */
	    private String dutyid;
	    /*
	    * 催收人编号.
	    */
	    private String dutyid2;
	    /*
	    * 账单日.
	    */
	    private Integer reckday;
	    /*
	    * 每期还款日.
	    */
	    private Integer retuday;
	    /*
	    * 合作方编号.
	    */
	    private String corpid;
	    /*
	    * 合作方名称.
	    */
	    private String corpname;
	    /*
	    * 合作项目编号.
	    */
	    private String projid;
	    /*
	    * 合作项目额度编号.
	    */
	    private String corpappid;
	    /*
	    * 基准利率.
	    */
	    private BigDecimal basicinterate;
	    /*
	    * 贷款利率.
	    */
	    private BigDecimal interate;
	    /*
	    * 全额价款.
	    */
	    private BigDecimal goodsamt;
	    /*
	    * 贷款购置住房套数.
	    */
	    private Integer loanhousecount;
	    /*
	    * 家庭所购房套数.
	    */
	    private Integer familyhousecount;
	    /*
	    * 配偶客户编号.
	    */
	    private String spousecustid;
	    /*
	    * 贷款余额.
	    */
	    private BigDecimal bal;
	    /*
	    * 拖欠本金.
	    */
	    private BigDecimal overbal;
	    /*
	    * 拖欠利息.
	    */
	    private BigDecimal overinte;
	    /*
	    * 累计发放金额.
	    */
	    private BigDecimal sumtcapi;
	    /*
	    * 是否逾期.
	    */
	    private String isOver;
	    /*
	    * 逾期开始日.
	    */
	    private Date overStartDate;
	    /*
	    * 当前逾期天数.
	    */
	    private Integer overDays;
	    /*
	    * 当前逾期期数.
	    */
	    private Integer overCount;
	    /*
	    * _12个月内逾期期数.
	    */
	    private Integer overCountLast12M;
	    /*
	    * 历史最高逾期期数.
	    */
	    private Integer overCountMaxHis;
	    /*
	    * 历史累计逾期期数.
	    */
	    private Integer overCountSumHis;
	    /*
	    * 是否违约.
	    */
	    private String isDefault;
	    /*
	    * 违约开始日期.
	    */
	    private Date defaultStartDate;
	    /*
	    * 当前违约次数.
	    */
	    private Integer defaultCount;
	    /*
	    * 历史累计违约次数.
	    */
	    private Integer defaultCountHis;
	    
	    /**
		 * 责任人信息(临时字段,不存在数据库中)
		 */
		private String dutyInfo;
		/**
		 * 催收人(临时字段,不存在数据库)
		 */
		private String collInfo;

	    public TEdwPlsAccount() {
	    }

	    public TEdwPlsAccount(String loanacno) {
	        this.loanacno = loanacno;
	    }
	   
		/**
	    * Get the 账户ID
	    */	
	    public String getLoanacno() {
	        return this.loanacno;
	    }
		/**
	    * Set the 账户ID
	    */	
	    public void setLoanacno(String loanacno) {
	        this.loanacno = loanacno;
	    }
		/**
	    * Get the 业务编号
	    */	
	    public String getLoanid() {
	        return this.loanid;
	    }
		/**
	    * Set the 业务编号
	    */	
	    public void setLoanid(String loanid) {
	        this.loanid = loanid;
	    }
		/**
	    * Get the 客户编号
	    */	
	    public String getCustid() {
	        return this.custid;
	    }
		/**
	    * Set the 客户编号
	    */	
	    public void setCustid(String custid) {
	        this.custid = custid;
	    }
		/**
	    * Get the 客户名称
	    */	
	    public String getCustname() {
	        return this.custname;
	    }
		/**
	    * Set the 客户名称
	    */	
	    public void setCustname(String custname) {
	        this.custname = custname;
	    }
		/**
	    * Get the 法人客户编号
	    */	
	    public String getCorpcustid() {
	        return this.corpcustid;
	    }
		/**
	    * Set the 法人客户编号
	    */	
	    public void setCorpcustid(String corpcustid) {
	        this.corpcustid = corpcustid;
	    }
		/**
	    * Get the 产品类型
	    */	
	    public String getProdid() {
	        return this.prodid;
	    }
		/**
	    * Set the 产品类型
	    */	
	    public void setProdid(String prodid) {
	        this.prodid = prodid;
	    }
		/**
	    * Get the 产品名称
	    */	
	    public String getProdname() {
	        return this.prodname;
	    }
		/**
	    * Set the 产品名称
	    */	
	    public void setProdname(String prodname) {
	        this.prodname = prodname;
	    }
		/**
	    * Get the 贷款金额
	    */	
	    public BigDecimal getTcapi() {
	        return this.tcapi;
	    }
		/**
	    * Set the 贷款金额
	    */	
	    public void setTcapi(BigDecimal tcapi) {
	        this.tcapi = tcapi;
	    }
		/**
	    * Get the 贷款期限
	    */	
	    public Integer getTterm() {
	        return this.tterm;
	    }
		/**
	    * Set the 贷款期限
	    */	
	    public void setTterm(Integer tterm) {
	        this.tterm = tterm;
	    }
		/**
	    * Get the 还款方式
	    */	
	    public String getRetukind() {
	        return this.retukind;
	    }
		/**
	    * Set the 还款方式
	    */	
	    public void setRetukind(String retukind) {
	        this.retukind = retukind;
	    }
		/**
	    * Get the 凭证编号
	    */	
	    public String getWarrno() {
	        return this.warrno;
	    }
		/**
	    * Set the 凭证编号
	    */	
	    public void setWarrno(String warrno) {
	        this.warrno = warrno;
	    }
		/**
	    * Get the 入库编号
	    */	
	    public String getEnstroid() {
	        return this.enstroid;
	    }
		/**
	    * Set the 入库编号
	    */	
	    public void setEnstroid(String enstroid) {
	        this.enstroid = enstroid;
	    }
		/**
	    * Get the 权证入库日期
	    */	
	    public Date getWarrbusidate() {
	        return this.warrbusidate;
	    }
		/**
	    * Set the 权证入库日期
	    */	
	    public void setWarrbusidate(Date warrbusidate) {
	        this.warrbusidate = warrbusidate;
	    }
		/**
	    * Get the 总押品价值
	    */	
	    public BigDecimal getTotalMortgageValue() {
	        return this.totalMortgageValue;
	    }
		/**
	    * Set the 总押品价值
	    */	
	    public void setTotalMortgageValue(BigDecimal totalMortgageValue) {
	        this.totalMortgageValue = totalMortgageValue;
	    }
		/**
	    * Get the 是否结清
	    */	
	    public String getPayoffflag() {
	        return this.payoffflag;
	    }
		/**
	    * Set the 是否结清
	    */	
	    public void setPayoffflag(String payoffflag) {
	        this.payoffflag = payoffflag;
	    }
		/**
	    * Get the 联保小组名称
	    */	
	    public String getUnprofname() {
	        return this.unprofname;
	    }
		/**
	    * Set the 联保小组名称
	    */	
	    public void setUnprofname(String unprofname) {
	        this.unprofname = unprofname;
	    }
		/**
	    * Get the 开户日期
	    */	
	    public Date getBegindate() {
	        return this.begindate;
	    }
		/**
	    * Set the 开户日期
	    */	
	    public void setBegindate(Date begindate) {
	        this.begindate = begindate;
	    }
		/**
	    * Get the 到期日期
	    */	
	    public Date getEnddate() {
	        return this.enddate;
	    }
		/**
	    * Set the 到期日期
	    */	
	    public void setEnddate(Date enddate) {
	        this.enddate = enddate;
	    }
		/**
	    * Get the 经办人
	    */	
	    public String getOperid() {
	        return this.operid;
	    }
		/**
	    * Set the 经办人
	    */	
	    public void setOperid(String operid) {
	        this.operid = operid;
	    }
		/**
	    * Get the 经办人名称
	    */	
	    public String getOpername() {
	        return this.opername;
	    }
		/**
	    * Set the 经办人名称
	    */	
	    public void setOpername(String opername) {
	        this.opername = opername;
	    }
		/**
	    * Get the 经办行
	    */	
	    public String getBankid() {
	        return this.bankid;
	    }
		/**
	    * Set the 经办行
	    */	
	    public void setBankid(String bankid) {
	        this.bankid = bankid;
	    }
		/**
	    * Get the 经办行名称
	    */	
	    public String getBankname() {
	        return this.bankname;
	    }
		/**
	    * Set the 经办行名称
	    */	
	    public void setBankname(String bankname) {
	        this.bankname = bankname;
	    }
		/**
	    * Get the 担保方式
	    */	
	    public String getAssukind() {
	        return this.assukind;
	    }
		/**
	    * Set the 担保方式
	    */	
	    public void setAssukind(String assukind) {
	        this.assukind = assukind;
	    }
		/**
	    * Get the 浮动比例
	    */	
	    public BigDecimal getFloatinterate() {
	        return this.floatinterate;
	    }
		/**
	    * Set the 浮动比例
	    */	
	    public void setFloatinterate(BigDecimal floatinterate) {
	        this.floatinterate = floatinterate;
	    }
		/**
	    * Get the 账户状态
	    */	
	    public String getAcflag() {
	        return this.acflag;
	    }
		/**
	    * Set the 账户状态
	    */	
	    public void setAcflag(String acflag) {
	        this.acflag = acflag;
	    }
		/**
	    * Get the 账户状态2
	    */	
	    public String getAcflag2() {
	        return this.acflag2;
	    }
		/**
	    * Set the 账户状态2
	    */	
	    public void setAcflag2(String acflag2) {
	        this.acflag2 = acflag2;
	    }
		/**
	    * Get the 风险分类
	    */	
	    public String getRiskflag() {
	        return this.riskflag;
	    }
		/**
	    * Set the 风险分类
	    */	
	    public void setRiskflag(String riskflag) {
	        this.riskflag = riskflag;
	    }
		/**
	    * Get the 合同编号
	    */	
	    public String getContno() {
	        return this.contno;
	    }
		/**
	    * Set the 合同编号
	    */	
	    public void setContno(String contno) {
	        this.contno = contno;
	    }
		/**
	    * Get the 检查人编号
	    */	
	    public String getDutyid() {
	        return this.dutyid;
	    }
		/**
	    * Set the 检查人编号
	    */	
	    public void setDutyid(String dutyid) {
	        this.dutyid = dutyid;
	    }
		/**
	    * Get the 催收人编号
	    */	
	    public String getDutyid2() {
	        return this.dutyid2;
	    }
		/**
	    * Set the 催收人编号
	    */	
	    public void setDutyid2(String dutyid2) {
	        this.dutyid2 = dutyid2;
	    }
		/**
	    * Get the 账单日
	    */	
	    public Integer getReckday() {
	        return this.reckday;
	    }
		/**
	    * Set the 账单日
	    */	
	    public void setReckday(Integer reckday) {
	        this.reckday = reckday;
	    }
		/**
	    * Get the 每期还款日
	    */	
	    public Integer getRetuday() {
	        return this.retuday;
	    }
		/**
	    * Set the 每期还款日
	    */	
	    public void setRetuday(Integer retuday) {
	        this.retuday = retuday;
	    }
		/**
	    * Get the 合作方编号
	    */	
	    public String getCorpid() {
	        return this.corpid;
	    }
		/**
	    * Set the 合作方编号
	    */	
	    public void setCorpid(String corpid) {
	        this.corpid = corpid;
	    }
		/**
	    * Get the 合作方名称
	    */	
	    public String getCorpname() {
	        return this.corpname;
	    }
		/**
	    * Set the 合作方名称
	    */	
	    public void setCorpname(String corpname) {
	        this.corpname = corpname;
	    }
		/**
	    * Get the 合作项目编号
	    */	
	    public String getProjid() {
	        return this.projid;
	    }
		/**
	    * Set the 合作项目编号
	    */	
	    public void setProjid(String projid) {
	        this.projid = projid;
	    }
		/**
	    * Get the 合作项目额度编号
	    */	
	    public String getCorpappid() {
	        return this.corpappid;
	    }
		/**
	    * Set the 合作项目额度编号
	    */	
	    public void setCorpappid(String corpappid) {
	        this.corpappid = corpappid;
	    }
		/**
	    * Get the 基准利率
	    */	
	    public BigDecimal getBasicinterate() {
	        return this.basicinterate;
	    }
		/**
	    * Set the 基准利率
	    */	
	    public void setBasicinterate(BigDecimal basicinterate) {
	        this.basicinterate = basicinterate;
	    }
		/**
	    * Get the 贷款利率
	    */	
	    public BigDecimal getInterate() {
	        return this.interate;
	    }
		/**
	    * Set the 贷款利率
	    */	
	    public void setInterate(BigDecimal interate) {
	        this.interate = interate;
	    }
		/**
	    * Get the 全额价款
	    */	
	    public BigDecimal getGoodsamt() {
	        return this.goodsamt;
	    }
		/**
	    * Set the 全额价款
	    */	
	    public void setGoodsamt(BigDecimal goodsamt) {
	        this.goodsamt = goodsamt;
	    }
		/**
	    * Get the 贷款购置住房套数
	    */	
	    public Integer getLoanhousecount() {
	        return this.loanhousecount;
	    }
		/**
	    * Set the 贷款购置住房套数
	    */	
	    public void setLoanhousecount(Integer loanhousecount) {
	        this.loanhousecount = loanhousecount;
	    }
		/**
	    * Get the 家庭所购房套数
	    */	
	    public Integer getFamilyhousecount() {
	        return this.familyhousecount;
	    }
		/**
	    * Set the 家庭所购房套数
	    */	
	    public void setFamilyhousecount(Integer familyhousecount) {
	        this.familyhousecount = familyhousecount;
	    }
		/**
	    * Get the 配偶客户编号
	    */	
	    public String getSpousecustid() {
	        return this.spousecustid;
	    }
		/**
	    * Set the 配偶客户编号
	    */	
	    public void setSpousecustid(String spousecustid) {
	        this.spousecustid = spousecustid;
	    }
		/**
	    * Get the 贷款余额
	    */	
	    public BigDecimal getBal() {
	        return this.bal;
	    }
		/**
	    * Set the 贷款余额
	    */	
	    public void setBal(BigDecimal bal) {
	        this.bal = bal;
	    }
		/**
	    * Get the 拖欠本金
	    */	
	    public BigDecimal getOverbal() {
	        return this.overbal;
	    }
		/**
	    * Set the 拖欠本金
	    */	
	    public void setOverbal(BigDecimal overbal) {
	        this.overbal = overbal;
	    }
		/**
	    * Get the 拖欠利息
	    */	
	    public BigDecimal getOverinte() {
	        return this.overinte;
	    }
		/**
	    * Set the 拖欠利息
	    */	
	    public void setOverinte(BigDecimal overinte) {
	        this.overinte = overinte;
	    }
		/**
	    * Get the 累计发放金额
	    */	
	    public BigDecimal getSumtcapi() {
	        return this.sumtcapi;
	    }
		/**
	    * Set the 累计发放金额
	    */	
	    public void setSumtcapi(BigDecimal sumtcapi) {
	        this.sumtcapi = sumtcapi;
	    }
		/**
	    * Get the 是否逾期
	    */	
	    public String getIsOver() {
	        return this.isOver;
	    }
		/**
	    * Set the 是否逾期
	    */	
	    public void setIsOver(String isOver) {
	        this.isOver = isOver;
	    }
		/**
	    * Get the 逾期开始日
	    */	
	    public Date getOverStartDate() {
	        return this.overStartDate;
	    }
		/**
	    * Set the 逾期开始日
	    */	
	    public void setOverStartDate(Date overStartDate) {
	        this.overStartDate = overStartDate;
	    }
		/**
	    * Get the 当前逾期天数
	    */	
	    public Integer getOverDays() {
	        return this.overDays;
	    }
		/**
	    * Set the 当前逾期天数
	    */	
	    public void setOverDays(Integer overDays) {
	        this.overDays = overDays;
	    }
		/**
	    * Get the 当前逾期期数
	    */	
	    public Integer getOverCount() {
	        return this.overCount;
	    }
		/**
	    * Set the 当前逾期期数
	    */	
	    public void setOverCount(Integer overCount) {
	        this.overCount = overCount;
	    }
		/**
	    * Get the _12个月内逾期期数
	    */	
	    public Integer getOverCountLast12M() {
	        return this.overCountLast12M;
	    }
		/**
	    * Set the _12个月内逾期期数
	    */	
	    public void setOverCountLast12M(Integer overCountLast12M) {
	        this.overCountLast12M = overCountLast12M;
	    }
		/**
	    * Get the 历史最高逾期期数
	    */	
	    public Integer getOverCountMaxHis() {
	        return this.overCountMaxHis;
	    }
		/**
	    * Set the 历史最高逾期期数
	    */	
	    public void setOverCountMaxHis(Integer overCountMaxHis) {
	        this.overCountMaxHis = overCountMaxHis;
	    }
		/**
	    * Get the 历史累计逾期期数
	    */	
	    public Integer getOverCountSumHis() {
	        return this.overCountSumHis;
	    }
		/**
	    * Set the 历史累计逾期期数
	    */	
	    public void setOverCountSumHis(Integer overCountSumHis) {
	        this.overCountSumHis = overCountSumHis;
	    }
		/**
	    * Get the 是否违约
	    */	
	    public String getIsDefault() {
	        return this.isDefault;
	    }
		/**
	    * Set the 是否违约
	    */	
	    public void setIsDefault(String isDefault) {
	        this.isDefault = isDefault;
	    }
		/**
	    * Get the 违约开始日期
	    */	
	    public Date getDefaultStartDate() {
	        return this.defaultStartDate;
	    }
		/**
	    * Set the 违约开始日期
	    */	
	    public void setDefaultStartDate(Date defaultStartDate) {
	        this.defaultStartDate = defaultStartDate;
	    }
		/**
	    * Get the 当前违约次数
	    */	
	    public Integer getDefaultCount() {
	        return this.defaultCount;
	    }
		/**
	    * Set the 当前违约次数
	    */	
	    public void setDefaultCount(Integer defaultCount) {
	        this.defaultCount = defaultCount;
	    }
		/**
	    * Get the 历史累计违约次数
	    */	
	    public Integer getDefaultCountHis() {
	        return this.defaultCountHis;
	    }
		/**
	    * Set the 历史累计违约次数
	    */	
	    public void setDefaultCountHis(Integer defaultCountHis) {
	        this.defaultCountHis = defaultCountHis;
	    }

		public String getDutyInfo() {
			return dutyInfo;
		}

		public void setDutyInfo(String dutyInfo) {
			this.dutyInfo = dutyInfo;
		}

		public String getCollInfo() {
			return collInfo;
		}

		public void setCollInfo(String collInfo) {
			this.collInfo = collInfo;
		}
}