package com.gbicc.company.single.entity;
// Generated 2016-1-22 15:18:57 by Hibernate Tools 3.2.2.GA



/**
 * TCmSingleRulCasesDutyinfo generated by hbm2java
 */
public class TCmSingleRulCasesDutyinfo  implements java.io.Serializable {

	private static final long serialVersionUID = 5358436152891566696L;
	
	/*
    * ID主键.
    */
    private String id;
    /*
    * 案例ID.
    */
    private String casesId;
    /*
    * 责任人.
    */
    private String duty;
    /*
     * 责任人名称（临时字段）.
     */
    private String tempDutyName;
    /*
    * 责任机构.
    */
    private String dutyOrg;
    /*
     * 责任机构名称（临时字段）.
     */
     private String tempDutyOrgName;
    /*
    * 详细说明.
    */
    private String desc;

    public TCmSingleRulCasesDutyinfo() {
    }

    public TCmSingleRulCasesDutyinfo(String id) {
        this.id = id;
    }
   
	/**
    * Get the ID主键
    */	
    public String getId() {
        return this.id;
    }
	/**
    * Set the ID主键
    */	
    public void setId(String id) {
        this.id = id;
    }
	/**
    * Get the 案例ID
    */	
    public String getCasesId() {
        return this.casesId;
    }
	/**
    * Set the 案例ID
    */	
    public void setCasesId(String casesId) {
        this.casesId = casesId;
    }
	/**
    * Get the 责任人
    */	
    public String getDuty() {
        return this.duty;
    }
	/**
    * Set the 责任人
    */	
    public void setDuty(String duty) {
        this.duty = duty;
    }
	/**
    * Get the 责任机构
    */	
    public String getDutyOrg() {
        return this.dutyOrg;
    }
	/**
    * Set the 责任机构
    */	
    public void setDutyOrg(String dutyOrg) {
        this.dutyOrg = dutyOrg;
    }
	/**
    * Get the 详细说明
    */	
    public String getDesc() {
        return this.desc;
    }
	/**
    * Set the 详细说明
    */	
    public void setDesc(String desc) {
        this.desc = desc;
    }

	public String getTempDutyName() {
		return tempDutyName;
	}

	public void setTempDutyName(String tempDutyName) {
		this.tempDutyName = tempDutyName;
	}

	public String getTempDutyOrgName() {
		return tempDutyOrgName;
	}

	public void setTempDutyOrgName(String tempDutyOrgName) {
		this.tempDutyOrgName = tempDutyOrgName;
	}
}