package com.gbicc.company.single.outputentity;
// Generated 2016-1-12 19:22:04 by Hibernate Tools 3.2.2.GA



/**
 * TRewJ16TbassetaccId generated by hbm2java
 */
public class J16  implements java.io.Serializable {

	private static final long serialVersionUID = 6596161135781133061L;
	
	/*
    */
    private String eventkey;
    /*
    */
    private String clientNo;
    /*
    */
    private String taCode;
    /*
    */
    private String assetAcc;
    /*
    */
    private String clientManager;
    /*
    */
    private String bankAcc;
    /*
    */
    private String branchNo;
    /*
    */
    private String openDate;
    /*
    */
    private String sendFreq;
    /*
    */
    private String sendMode;
    /*
    */
    private String divMode;
    /*
    */
    private String status;
    /*
    */
    private String openFlag;
    /*
    */
    private String reserve1;
    /*
    */
    private String taClient;
    /*
    */
    private String clientType;
    /*
    */
    private String prdType;
    /*
    * 预警表ID.
    */
    private String warnId;
    /*
    * 数据日期.
    */
    private String dataDt;
    private String custName;

    public J16() {
    }

	/**
    */	
    public String getEventkey() {
        return this.eventkey;
    }
	/**
    */	
    public void setEventkey(String eventkey) {
        this.eventkey = eventkey;
    }
	/**
    */	
    public String getClientNo() {
        return this.clientNo;
    }
	/**
    */	
    public void setClientNo(String clientNo) {
        this.clientNo = clientNo;
    }
	/**
    */	
    public String getTaCode() {
        return this.taCode;
    }
	/**
    */	
    public void setTaCode(String taCode) {
        this.taCode = taCode;
    }
	/**
    */	
    public String getAssetAcc() {
        return this.assetAcc;
    }
	/**
    */	
    public void setAssetAcc(String assetAcc) {
        this.assetAcc = assetAcc;
    }
	/**
    */	
    public String getClientManager() {
        return this.clientManager;
    }
	/**
    */	
    public void setClientManager(String clientManager) {
        this.clientManager = clientManager;
    }
	/**
    */	
    public String getBankAcc() {
        return this.bankAcc;
    }
	/**
    */	
    public void setBankAcc(String bankAcc) {
        this.bankAcc = bankAcc;
    }
	/**
    */	
    public String getBranchNo() {
        return this.branchNo;
    }
	/**
    */	
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo;
    }
	/**
    */	
    public String getOpenDate() {
        return this.openDate;
    }
	/**
    */	
    public void setOpenDate(String openDate) {
        this.openDate = openDate;
    }
	/**
    */	
    public String getSendFreq() {
        return this.sendFreq;
    }
	/**
    */	
    public void setSendFreq(String sendFreq) {
        this.sendFreq = sendFreq;
    }
	/**
    */	
    public String getSendMode() {
        return this.sendMode;
    }
	/**
    */	
    public void setSendMode(String sendMode) {
        this.sendMode = sendMode;
    }
	/**
    */	
    public String getDivMode() {
        return this.divMode;
    }
	/**
    */	
    public void setDivMode(String divMode) {
        this.divMode = divMode;
    }
	/**
    */	
    public String getStatus() {
        return this.status;
    }
	/**
    */	
    public void setStatus(String status) {
        this.status = status;
    }
	/**
    */	
    public String getOpenFlag() {
        return this.openFlag;
    }
	/**
    */	
    public void setOpenFlag(String openFlag) {
        this.openFlag = openFlag;
    }
	/**
    */	
    public String getReserve1() {
        return this.reserve1;
    }
	/**
    */	
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1;
    }
	/**
    */	
    public String getTaClient() {
        return this.taClient;
    }
	/**
    */	
    public void setTaClient(String taClient) {
        this.taClient = taClient;
    }
	/**
    */	
    public String getClientType() {
        return this.clientType;
    }
	/**
    */	
    public void setClientType(String clientType) {
        this.clientType = clientType;
    }
	/**
    */	
    public String getPrdType() {
        return this.prdType;
    }
	/**
    */	
    public void setPrdType(String prdType) {
        this.prdType = prdType;
    }
	/**
    * Get the 预警表ID
    */	
    public String getWarnId() {
        return this.warnId;
    }
	/**
    * Set the 预警表ID
    */	
    public void setWarnId(String warnId) {
        this.warnId = warnId;
    }
	/**
    * Get the 数据日期
    */	
    public String getDataDt() {
        return this.dataDt;
    }
	/**
    * Set the 数据日期
    */	
    public void setDataDt(String dataDt) {
        this.dataDt = dataDt;
    }

	public String getCustName() {
		return custName;
	}
	public void setCustName(String custName) {
		this.custName = custName;
	}
}