package com.gbicc.company.single.outputentity;
// Generated 2016-1-15 16:51:03 by Hibernate Tools 3.2.2.GA



/**
 * TRewL03IndPunishDetailId generated by hbm2java
 */
public class L03  implements java.io.Serializable {

	private static final long serialVersionUID = 6472194324352463729L;
	
	/*
    * ID.
    */
    private String id;
    /*
    * 决定书文号.
    */
    private String decideWrit;
    /*
    * 违法类型.
    */
    private String breakType;
    /*
    * 处罚内容.
    */
    private String punishContent;
    /*
    * 决定机关.
    */
    private String decideOrg;
    /*
    * 关联基本信息主键.
    */
    private String baseId;
    /*
    * 预警表ID.
    */
    private String warnId;
    /*
    * 数据日期.
    */
    private String dataDt;

    public L03() {
    }

	/**
    * Get the ID
    */	
    public String getId() {
        return this.id;
    }
	/**
    * Set the ID
    */	
    public void setId(String id) {
        this.id = id;
    }
	/**
    * Get the 决定书文号
    */	
    public String getDecideWrit() {
        return this.decideWrit;
    }
	/**
    * Set the 决定书文号
    */	
    public void setDecideWrit(String decideWrit) {
        this.decideWrit = decideWrit;
    }
	/**
    * Get the 违法类型
    */	
    public String getBreakType() {
        return this.breakType;
    }
	/**
    * Set the 违法类型
    */	
    public void setBreakType(String breakType) {
        this.breakType = breakType;
    }
	/**
    * Get the 处罚内容
    */	
    public String getPunishContent() {
        return this.punishContent;
    }
	/**
    * Set the 处罚内容
    */	
    public void setPunishContent(String punishContent) {
        this.punishContent = punishContent;
    }
	/**
    * Get the 决定机关
    */	
    public String getDecideOrg() {
        return this.decideOrg;
    }
	/**
    * Set the 决定机关
    */	
    public void setDecideOrg(String decideOrg) {
        this.decideOrg = decideOrg;
    }
	/**
    * Get the 关联基本信息主键
    */	
    public String getBaseId() {
        return this.baseId;
    }
	/**
    * Set the 关联基本信息主键
    */	
    public void setBaseId(String baseId) {
        this.baseId = baseId;
    }
	/**
    * Get the 预警表ID
    */	
    public String getWarnId() {
        return this.warnId;
    }
	/**
    * Set the 预警表ID
    */	
    public void setWarnId(String warnId) {
        this.warnId = warnId;
    }
	/**
    * Get the 数据日期
    */	
    public String getDataDt() {
        return this.dataDt;
    }
	/**
    * Set the 数据日期
    */	
    public void setDataDt(String dataDt) {
        this.dataDt = dataDt;
    }
}