package com.gbicc.user.entity;

//default package
//Generated 2016-7-20 8:37:50 by Hibernate Tools 3.4.0.CR1

/**
* TModifiedRoleid generated by hbm2java
*/
public class TModifiedRoleid implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String fdId;
	private String fdOperid;
	private String fdUserid;
	private String fdRoleidb;
	private String fdRoleida;
	private String fdChangedate;
	private String fdOrgid;
	private String fdOrgname;
	private String fdUsername;
	private String fdOpername;

	public TModifiedRoleid() {
	}

	public TModifiedRoleid(String fdId) {
		this.fdId = fdId;
	}

	public TModifiedRoleid(String fdId, String fdOperid, String fdUserid,
			String fdRoleidb, String fdRoleida, String fdChangedate,
			String fdOrgid) {
		this.fdId = fdId;
		this.fdOperid = fdOperid;
		this.fdUserid = fdUserid;
		this.fdRoleidb = fdRoleidb;
		this.fdRoleida = fdRoleida;
		this.fdChangedate = fdChangedate;
		this.fdOrgid = fdOrgid;
	}

	public String getFdId() {
		return this.fdId;
	}

	public void setFdId(String fdId) {
		this.fdId = fdId;
	}

	public String getFdOperid() {
		return this.fdOperid;
	}

	public void setFdOperid(String fdOperid) {
		this.fdOperid = fdOperid;
	}

	public String getFdUserid() {
		return this.fdUserid;
	}

	public void setFdUserid(String fdUserid) {
		this.fdUserid = fdUserid;
	}

	public String getFdRoleidb() {
		return this.fdRoleidb;
	}

	public void setFdRoleidb(String fdRoleidb) {
		this.fdRoleidb = fdRoleidb;
	}

	public String getFdRoleida() {
		return this.fdRoleida;
	}

	public void setFdRoleida(String fdRoleida) {
		this.fdRoleida = fdRoleida;
	}

	public String getFdChangedate() {
		return this.fdChangedate;
	}

	public void setFdChangedate(String fdChangedate) {
		this.fdChangedate = fdChangedate;
	}

	public String getFdOrgid() {
		return this.fdOrgid;
	}

	public void setFdOrgid(String fdOrgid) {
		this.fdOrgid = fdOrgid;
	}

	public String getFdOrgname() {
		return fdOrgname;
	}

	public void setFdOrgname(String fdOrgname) {
		this.fdOrgname = fdOrgname;
	}

	public String getFdUsername() {
		return fdUsername;
	}

	public void setFdUsername(String fdUsername) {
		this.fdUsername = fdUsername;
	}

	public String getFdOpername() {
		return fdOpername;
	}

	public void setFdOpername(String fdOpername) {
		this.fdOpername = fdOpername;
	}

}
