package com.gbicc.company.financial.analysis.entity;

import java.math.BigDecimal;

import com.huateng.ebank.business.common.bean.TreeNode;
// Generated 2015-12-7 14:12:42 by Hibernate Tools 3.2.2.GA



/**
 * TCmFinanceIndexData generated by hbm2java
 */
public class FinanceIndexData extends TreeNode  implements java.io.Serializable {
	


   
	  /*
	    */
	    private String indexName;
	    private String indexCd;
	    private String indexTypeName;
	    private String indexType;
	    private String chineseName;
	    /*
	    */
	    private String indexDisp;
	    /*
	    */
	    private BigDecimal stringType;
	    /*
	    */
	    private String sStringType;
	    /*
	    */
	    private String ssStringType;
	    /*
	    */
	    private String avgStringType;
	    private String upDown;
		public String getIndexName() {
			return indexName;
		}
		public void setIndexName(String indexName) {
			this.indexName = indexName;
		}
		
		public String getIndexCd() {
			return indexCd;
		}
		public void setIndexCd(String indexCd) {
			this.indexCd = indexCd;
		}
		public String getIndexTypeName() {
			return indexTypeName;
		}
		public void setIndexTypeName(String indexTypeName) {
			this.indexTypeName = indexTypeName;
		}
		public String getIndexType() {
			return indexType;
		}
		public void setIndexType(String indexType) {
			this.indexType = indexType;
		}
		public String getIndexDisp() {
			return indexDisp;
		}
		public void setIndexDisp(String indexDisp) {
			this.indexDisp = indexDisp;
		}
		public BigDecimal getStringType() {
			return stringType;
		}
		public void setStringType(BigDecimal stringType) {
			this.stringType = stringType;
		}
		public String getsStringType() {
			return sStringType;
		}
		public void setsStringType(String sStringType) {
			this.sStringType = sStringType;
		}
		public String getSsStringType() {
			return ssStringType;
		}
		public void setSsStringType(String ssStringType) {
			this.ssStringType = ssStringType;
		}
		public String getAvgStringType() {
			return avgStringType;
		}
		public void setAvgStringType(String avgStringType) {
			this.avgStringType = avgStringType;
		}
		public String getUpDown() {
			return upDown;
		}
		public void setUpDown(String upDown) {
			this.upDown = upDown;
		}
		public String getChineseName() {
			return chineseName;
		}
		public void setChineseName(String chineseName) {
			this.chineseName = chineseName;
		}

    


}


