package com.gbicc.person.great.entity;
// Generated 2016-1-8 9:37:26 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import com.huateng.ebank.entity.data.mng.TlrInfo;

/**
 * TPlGreatEvent generated by hbm2java
 */
public class TPlGreatEvent  implements java.io.Serializable {

	private static final long serialVersionUID = 5494872883063372030L;
	
	/*
    * ID主键.
    */
    private String id;
    /*
    * 登记用户.
    */
    private TlrInfo regiUser;
    /*
    * 登记时间.
    */
    private Date regiDate;
    /*
    * 关注主体.
    */
    private String atteMain;
    /*
    * 主体对象.
    */
    private String mainObj;
    /**
     * 主体对象名称
     */
    private String mainObjName;
    /*
    * 重大事件内容.
    */
    private String content;
    /**
     * 重大事件内容描述（临时字段）
     */
    private String contentDesc;
    /*
    * 说明.
    */
    private String explain;
    /**
     * 级别
     */
    private String level;
    /**
     * 内容编号
     */
    private String contentCode;

    public TPlGreatEvent() {
    }

    public TPlGreatEvent(String id) {
        this.id = id;
    }
   
	/**
    * Get the ID主键
    */	
    public String getId() {
        return this.id;
    }
	/**
    * Set the ID主键
    */	
    public void setId(String id) {
        this.id = id;
    }
	/**
    * Get the 登记用户
    */	
    public TlrInfo getRegiUser() {
        return this.regiUser;
    }
	/**
    * Set the 登记用户
    */	
    public void setRegiUser(TlrInfo regiUser) {
        this.regiUser = regiUser;
    }
	/**
    * Get the 登记时间
    */	
    public Date getRegiDate() {
        return this.regiDate;
    }
	/**
    * Set the 登记时间
    */	
    public void setRegiDate(Date regiDate) {
        this.regiDate = regiDate;
    }
	/**
    * Get the 关注主体
    */	
    public String getAtteMain() {
        return this.atteMain;
    }
	/**
    * Set the 关注主体
    */	
    public void setAtteMain(String atteMain) {
        this.atteMain = atteMain;
    }
	/**
    * Get the 主体对象
    */	
    public String getMainObj() {
        return this.mainObj;
    }
	/**
    * Set the 主体对象
    */	
    public void setMainObj(String mainObj) {
        this.mainObj = mainObj;
    }
    /**
     * Get the 主体对象名称
     */
	public String getMainObjName() {
		return mainObjName;
	}
	/**
     * Set the 主体对象名称
     */
	public void setMainObjName(String mainObjName) {
		this.mainObjName = mainObjName;
	}
	/**
    * Get the 重大事件内容
    */	
    public String getContent() {
        return this.content;
    }
	/**
    * Set the 重大事件内容
    */	
    public void setContent(String content) {
        this.content = content;
    }
	/**
    * Get the 说明
    */	
    public String getExplain() {
        return this.explain;
    }
	/**
    * Set the 说明
    */	
    public void setExplain(String explain) {
        this.explain = explain;
    }
    /**
     * Get the 级别
     */	
	public String getLevel() {
		return level;
	}
	/**
    * Set the 级别
    */	
	public void setLevel(String level) {
		this.level = level;
	}
	/**
     * Get the 内容编号
     */	
	public String getContentCode() {
		return contentCode;
	}
	/**
    * Set the 内容编号
    */	
	public void setContentCode(String contentCode) {
		this.contentCode = contentCode;
	}
	/**
     * Get the 重大事件内容描述（临时字段）
     */	
	public String getContentDesc() {
		return contentDesc;
	}
	/**
     * Set the 重大事件内容描述（临时字段）
     */	
	public void setContentDesc(String contentDesc) {
		this.contentDesc = contentDesc;
	}
}