package com.gbicc.bpm.entity;
// Generated 2015-11-20 10:40:44 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.huateng.ebank.entity.data.mng.TlrInfo;

/**
 * TTaskDivertDtl generated by hbm2java
 */
public class TTaskDivertDtl  implements java.io.Serializable {

	private static final long serialVersionUID = 2645159476014644743L;
	
	/*
    * ID主键.
    */
    private String id;
    /*
    * 主表ID.
    */
    private String taskDivertId;
    /*
    * 业务主键.
    */
    private String businessKey;
    /*
    * 流程实例ID.
    */
    private String procInstId;
    /*
    * 流程名称.
    */
    private String procName;
    /*
    * 业务描述.
    */
    private String taskDesc;
    /*
    * 任务名称.
    */
    private String taskName;
    /*
    * 任务ID.
    */
    private String taskId;
    /*
    * 任务处理人.
    */
    private TlrInfo assignee;
    /*
    * 任务接收时间.
    */
    private Date createTime;
    /*
     * 流程关键字
     */
    private String procKey;

    public TTaskDivertDtl() {
    }

    public TTaskDivertDtl(String id) {
        this.id = id;
    }
    public TTaskDivertDtl(String id, String taskDivertId, String businessKey, String procInstId, String procName, String taskDesc, String taskName, String taskId, TlrInfo assignee, Date createTime) {
       this.id = id;
       this.taskDivertId = taskDivertId;
       this.businessKey = businessKey;
       this.procInstId = procInstId;
       this.procName = procName;
       this.taskDesc = taskDesc;
       this.taskName = taskName;
       this.taskId = taskId;
       this.assignee = assignee;
       this.createTime = createTime;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getTaskDivertId() {
        return this.taskDivertId;
    }
    
    public void setTaskDivertId(String taskDivertId) {
        this.taskDivertId = taskDivertId;
    }
    public String getBusinessKey() {
        return this.businessKey;
    }
    
    public void setBusinessKey(String businessKey) {
        this.businessKey = businessKey;
    }
    public String getProcInstId() {
        return this.procInstId;
    }
    
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId;
    }
    public String getProcName() {
        return this.procName;
    }
    
    public void setProcName(String procName) {
        this.procName = procName;
    }
    public String getTaskDesc() {
        return this.taskDesc;
    }
    
    public void setTaskDesc(String taskDesc) {
        this.taskDesc = taskDesc;
    }
    public String getTaskName() {
        return this.taskName;
    }
    
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }
    public String getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }
    public TlrInfo getAssignee() {
        return this.assignee;
    }
    
    public void setAssignee(TlrInfo assignee) {
        this.assignee = assignee;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public String getProcKey() {
		return procKey;
	}
	public void setProcKey(String procKey) {
		this.procKey = procKey;
	}
}