package com.gbicc.company.single.outputentity;
// Generated 2016-1-12 19:22:04 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * TRewC01BorrSummaryId generated by hbm2java
 */
public class C01  implements java.io.Serializable {

	private static final long serialVersionUID = -8494488811558123393L;
	
	/*
    */
    private String payoutAcctSummaryId;
    /*
    */
    private String payoutInfoDetailId;
    /*
    */
    private String payoutAppFormNum;
    /*
    */
    private String borrowNum;
    /*
    */
    private String contractNum;
    /*
    */
    private String customerNum;
    /*
    */
    private BigDecimal lastRequitalSum;
    /*
    */
    private String expirationDate;
    /*
    */
    private String brNo;
    /*
    */
    private String stat;
    /*
    */
    private String operateBrch;
    /*
    */
    private String balanceAccounts;
    /*
    */
    private BigDecimal storeRate;
    /*
    */
    private String actType;
    /*
    */
    private String actCat;
    /*
    */
    private String loanAcct;
    /*
    */
    private BigDecimal advBal;
    /*
    */
    private BigDecimal loanBal;
    /*
    */
    private BigDecimal theoLoanBal;
    /*
    */
    private BigDecimal bucketP;
    /*
    */
    private BigDecimal bocketI;
    /*
    */
    private BigDecimal bocketW;
    /*
    */
    private BigDecimal bocketA;
    /*
    */
    private BigDecimal bocketE;
    /*
    */
    private BigDecimal unpdBocketI;
    /*
    */
    private BigDecimal unpdBocketW;
    /*
    */
    private BigDecimal unpdBocketA;
    /*
    */
    private BigDecimal unpdBocketE;
    /*
    */
    private String badDebtInd;
    /*
    */
    private BigDecimal inOweAccounts;
    /*
    */
    private BigDecimal outOweAccounts;
    /*
    */
    private BigDecimal totalReturnPrp;
    /*
    */
    private BigDecimal totalBefRetnPrp;
    /*
    */
    private BigDecimal totalShouldRetnInt;
    /*
    */
    private BigDecimal totalRelRetnInt;
    /*
    */
    private BigDecimal totalWriteoffPrp;
    /*
    */
    private BigDecimal totalWriteoffInInt;
    /*
    */
    private BigDecimal totalWriteoffOutInt;
    /*
    */
    private BigDecimal totalOvdueAmt;
    /*
    */
    private BigDecimal totalPrimnessAmt;
    /*
    */
    private BigDecimal totalBadDebtAmt;
    /*
    */
    private String firstOvdueDate;
    /*
    */
    private String firstPrimnessDate;
    /*
    */
    private String firstBadDebtDate;
    /*
    */
    private String discountSign;
    /*
    */
    private String bankGuaranteeType;
    /*
    */
    private String bankGuaranteeState;
    /*
    */
    private BigDecimal refundSum;
    /*
    */
    private BigDecimal reSponsionWithodrawalSum;
    /*
    */
    private BigDecimal undertakePaySum;
    /*
    */
    private BigDecimal untreadSum;
    /*
    */
    private String addPeriodDate;
    /*
    */
    private String replacementSign;
    /*
    */
    private BigDecimal commissionChargeRatio;
    /*
    */
    private BigDecimal bailSum;
    /*
    */
    private BigDecimal replacementBalance;
    /*
    */
    private String financingInd;
    /*
    */
    private String letterOfCreditState;
    /*
    */
    private String qxRevertDate;
    /*
    */
    private String lastMaintainDate;
    /*
    */
    private BigDecimal creditBalance;
    /*
    */
    private BigDecimal tmpAmt;
    /*
    */
    private String postalOrderState;
    /*
    */
    private String fourLevel;
    /*
    */
    private String fiveLevel;
    /*
    */
    private String status;
    /*
    */
    private String currencyCd;
    /*
    */
    private String recState;
    /*
    */
    private String writeOffDate;
    /*
    */
    private String advAcctNo;
    /*
    */
    private BigDecimal advAmt;
    /*
    */
    private BigDecimal advOutBa;
    /*
    */
    private BigDecimal advInt;
    /*
    */
    private String borrowStatus;
    /*
    */
    private String billStatus;
    /*
    * 预警表ID.
    */
    private String warnId;
    /*
    * 数据日期.
    */
    private String dataDt;

    public C01() {
    }

	
    public C01(String payoutAcctSummaryId) {
        this.payoutAcctSummaryId = payoutAcctSummaryId;
    }
   
	/**
    */	
    public String getPayoutAcctSummaryId() {
        return this.payoutAcctSummaryId;
    }
	/**
    */	
    public void setPayoutAcctSummaryId(String payoutAcctSummaryId) {
        this.payoutAcctSummaryId = payoutAcctSummaryId;
    }
	/**
    */	
    public String getPayoutInfoDetailId() {
        return this.payoutInfoDetailId;
    }
	/**
    */	
    public void setPayoutInfoDetailId(String payoutInfoDetailId) {
        this.payoutInfoDetailId = payoutInfoDetailId;
    }
	/**
    */	
    public String getPayoutAppFormNum() {
        return this.payoutAppFormNum;
    }
	/**
    */	
    public void setPayoutAppFormNum(String payoutAppFormNum) {
        this.payoutAppFormNum = payoutAppFormNum;
    }
	/**
    */	
    public String getBorrowNum() {
        return this.borrowNum;
    }
	/**
    */	
    public void setBorrowNum(String borrowNum) {
        this.borrowNum = borrowNum;
    }
	/**
    */	
    public String getContractNum() {
        return this.contractNum;
    }
	/**
    */	
    public void setContractNum(String contractNum) {
        this.contractNum = contractNum;
    }
	/**
    */	
    public String getCustomerNum() {
        return this.customerNum;
    }
	/**
    */	
    public void setCustomerNum(String customerNum) {
        this.customerNum = customerNum;
    }
	/**
    */	
    public BigDecimal getLastRequitalSum() {
        return this.lastRequitalSum;
    }
	/**
    */	
    public void setLastRequitalSum(BigDecimal lastRequitalSum) {
        this.lastRequitalSum = lastRequitalSum;
    }
	/**
    */	
    public String getExpirationDate() {
        return this.expirationDate;
    }
	/**
    */	
    public void setExpirationDate(String expirationDate) {
        this.expirationDate = expirationDate;
    }
	/**
    */	
    public String getBrNo() {
        return this.brNo;
    }
	/**
    */	
    public void setBrNo(String brNo) {
        this.brNo = brNo;
    }
	/**
    */	
    public String getStat() {
        return this.stat;
    }
	/**
    */	
    public void setStat(String stat) {
        this.stat = stat;
    }
	/**
    */	
    public String getOperateBrch() {
        return this.operateBrch;
    }
	/**
    */	
    public void setOperateBrch(String operateBrch) {
        this.operateBrch = operateBrch;
    }
	/**
    */	
    public String getBalanceAccounts() {
        return this.balanceAccounts;
    }
	/**
    */	
    public void setBalanceAccounts(String balanceAccounts) {
        this.balanceAccounts = balanceAccounts;
    }
	/**
    */	
    public BigDecimal getStoreRate() {
        return this.storeRate;
    }
	/**
    */	
    public void setStoreRate(BigDecimal storeRate) {
        this.storeRate = storeRate;
    }
	/**
    */	
    public String getActType() {
        return this.actType;
    }
	/**
    */	
    public void setActType(String actType) {
        this.actType = actType;
    }
	/**
    */	
    public String getActCat() {
        return this.actCat;
    }
	/**
    */	
    public void setActCat(String actCat) {
        this.actCat = actCat;
    }
	/**
    */	
    public String getLoanAcct() {
        return this.loanAcct;
    }
	/**
    */	
    public void setLoanAcct(String loanAcct) {
        this.loanAcct = loanAcct;
    }
	/**
    */	
    public BigDecimal getAdvBal() {
        return this.advBal;
    }
	/**
    */	
    public void setAdvBal(BigDecimal advBal) {
        this.advBal = advBal;
    }
	/**
    */	
    public BigDecimal getLoanBal() {
        return this.loanBal;
    }
	/**
    */	
    public void setLoanBal(BigDecimal loanBal) {
        this.loanBal = loanBal;
    }
	/**
    */	
    public BigDecimal getTheoLoanBal() {
        return this.theoLoanBal;
    }
	/**
    */	
    public void setTheoLoanBal(BigDecimal theoLoanBal) {
        this.theoLoanBal = theoLoanBal;
    }
	/**
    */	
    public BigDecimal getBucketP() {
        return this.bucketP;
    }
	/**
    */	
    public void setBucketP(BigDecimal bucketP) {
        this.bucketP = bucketP;
    }
	/**
    */	
    public BigDecimal getBocketI() {
        return this.bocketI;
    }
	/**
    */	
    public void setBocketI(BigDecimal bocketI) {
        this.bocketI = bocketI;
    }
	/**
    */	
    public BigDecimal getBocketW() {
        return this.bocketW;
    }
	/**
    */	
    public void setBocketW(BigDecimal bocketW) {
        this.bocketW = bocketW;
    }
	/**
    */	
    public BigDecimal getBocketA() {
        return this.bocketA;
    }
	/**
    */	
    public void setBocketA(BigDecimal bocketA) {
        this.bocketA = bocketA;
    }
	/**
    */	
    public BigDecimal getBocketE() {
        return this.bocketE;
    }
	/**
    */	
    public void setBocketE(BigDecimal bocketE) {
        this.bocketE = bocketE;
    }
	/**
    */	
    public BigDecimal getUnpdBocketI() {
        return this.unpdBocketI;
    }
	/**
    */	
    public void setUnpdBocketI(BigDecimal unpdBocketI) {
        this.unpdBocketI = unpdBocketI;
    }
	/**
    */	
    public BigDecimal getUnpdBocketW() {
        return this.unpdBocketW;
    }
	/**
    */	
    public void setUnpdBocketW(BigDecimal unpdBocketW) {
        this.unpdBocketW = unpdBocketW;
    }
	/**
    */	
    public BigDecimal getUnpdBocketA() {
        return this.unpdBocketA;
    }
	/**
    */	
    public void setUnpdBocketA(BigDecimal unpdBocketA) {
        this.unpdBocketA = unpdBocketA;
    }
	/**
    */	
    public BigDecimal getUnpdBocketE() {
        return this.unpdBocketE;
    }
	/**
    */	
    public void setUnpdBocketE(BigDecimal unpdBocketE) {
        this.unpdBocketE = unpdBocketE;
    }
	/**
    */	
    public String getBadDebtInd() {
        return this.badDebtInd;
    }
	/**
    */	
    public void setBadDebtInd(String badDebtInd) {
        this.badDebtInd = badDebtInd;
    }
	/**
    */	
    public BigDecimal getInOweAccounts() {
        return this.inOweAccounts;
    }
	/**
    */	
    public void setInOweAccounts(BigDecimal inOweAccounts) {
        this.inOweAccounts = inOweAccounts;
    }
	/**
    */	
    public BigDecimal getOutOweAccounts() {
        return this.outOweAccounts;
    }
	/**
    */	
    public void setOutOweAccounts(BigDecimal outOweAccounts) {
        this.outOweAccounts = outOweAccounts;
    }
	/**
    */	
    public BigDecimal getTotalReturnPrp() {
        return this.totalReturnPrp;
    }
	/**
    */	
    public void setTotalReturnPrp(BigDecimal totalReturnPrp) {
        this.totalReturnPrp = totalReturnPrp;
    }
	/**
    */	
    public BigDecimal getTotalBefRetnPrp() {
        return this.totalBefRetnPrp;
    }
	/**
    */	
    public void setTotalBefRetnPrp(BigDecimal totalBefRetnPrp) {
        this.totalBefRetnPrp = totalBefRetnPrp;
    }
	/**
    */	
    public BigDecimal getTotalShouldRetnInt() {
        return this.totalShouldRetnInt;
    }
	/**
    */	
    public void setTotalShouldRetnInt(BigDecimal totalShouldRetnInt) {
        this.totalShouldRetnInt = totalShouldRetnInt;
    }
	/**
    */	
    public BigDecimal getTotalRelRetnInt() {
        return this.totalRelRetnInt;
    }
	/**
    */	
    public void setTotalRelRetnInt(BigDecimal totalRelRetnInt) {
        this.totalRelRetnInt = totalRelRetnInt;
    }
	/**
    */	
    public BigDecimal getTotalWriteoffPrp() {
        return this.totalWriteoffPrp;
    }
	/**
    */	
    public void setTotalWriteoffPrp(BigDecimal totalWriteoffPrp) {
        this.totalWriteoffPrp = totalWriteoffPrp;
    }
	/**
    */	
    public BigDecimal getTotalWriteoffInInt() {
        return this.totalWriteoffInInt;
    }
	/**
    */	
    public void setTotalWriteoffInInt(BigDecimal totalWriteoffInInt) {
        this.totalWriteoffInInt = totalWriteoffInInt;
    }
	/**
    */	
    public BigDecimal getTotalWriteoffOutInt() {
        return this.totalWriteoffOutInt;
    }
	/**
    */	
    public void setTotalWriteoffOutInt(BigDecimal totalWriteoffOutInt) {
        this.totalWriteoffOutInt = totalWriteoffOutInt;
    }
	/**
    */	
    public BigDecimal getTotalOvdueAmt() {
        return this.totalOvdueAmt;
    }
	/**
    */	
    public void setTotalOvdueAmt(BigDecimal totalOvdueAmt) {
        this.totalOvdueAmt = totalOvdueAmt;
    }
	/**
    */	
    public BigDecimal getTotalPrimnessAmt() {
        return this.totalPrimnessAmt;
    }
	/**
    */	
    public void setTotalPrimnessAmt(BigDecimal totalPrimnessAmt) {
        this.totalPrimnessAmt = totalPrimnessAmt;
    }
	/**
    */	
    public BigDecimal getTotalBadDebtAmt() {
        return this.totalBadDebtAmt;
    }
	/**
    */	
    public void setTotalBadDebtAmt(BigDecimal totalBadDebtAmt) {
        this.totalBadDebtAmt = totalBadDebtAmt;
    }
	/**
    */	
    public String getFirstOvdueDate() {
        return this.firstOvdueDate;
    }
	/**
    */	
    public void setFirstOvdueDate(String firstOvdueDate) {
        this.firstOvdueDate = firstOvdueDate;
    }
	/**
    */	
    public String getFirstPrimnessDate() {
        return this.firstPrimnessDate;
    }
	/**
    */	
    public void setFirstPrimnessDate(String firstPrimnessDate) {
        this.firstPrimnessDate = firstPrimnessDate;
    }
	/**
    */	
    public String getFirstBadDebtDate() {
        return this.firstBadDebtDate;
    }
	/**
    */	
    public void setFirstBadDebtDate(String firstBadDebtDate) {
        this.firstBadDebtDate = firstBadDebtDate;
    }
	/**
    */	
    public String getDiscountSign() {
        return this.discountSign;
    }
	/**
    */	
    public void setDiscountSign(String discountSign) {
        this.discountSign = discountSign;
    }
	/**
    */	
    public String getBankGuaranteeType() {
        return this.bankGuaranteeType;
    }
	/**
    */	
    public void setBankGuaranteeType(String bankGuaranteeType) {
        this.bankGuaranteeType = bankGuaranteeType;
    }
	/**
    */	
    public String getBankGuaranteeState() {
        return this.bankGuaranteeState;
    }
	/**
    */	
    public void setBankGuaranteeState(String bankGuaranteeState) {
        this.bankGuaranteeState = bankGuaranteeState;
    }
	/**
    */	
    public BigDecimal getRefundSum() {
        return this.refundSum;
    }
	/**
    */	
    public void setRefundSum(BigDecimal refundSum) {
        this.refundSum = refundSum;
    }
	/**
    */	
    public BigDecimal getReSponsionWithodrawalSum() {
        return this.reSponsionWithodrawalSum;
    }
	/**
    */	
    public void setReSponsionWithodrawalSum(BigDecimal reSponsionWithodrawalSum) {
        this.reSponsionWithodrawalSum = reSponsionWithodrawalSum;
    }
	/**
    */	
    public BigDecimal getUndertakePaySum() {
        return this.undertakePaySum;
    }
	/**
    */	
    public void setUndertakePaySum(BigDecimal undertakePaySum) {
        this.undertakePaySum = undertakePaySum;
    }
	/**
    */	
    public BigDecimal getUntreadSum() {
        return this.untreadSum;
    }
	/**
    */	
    public void setUntreadSum(BigDecimal untreadSum) {
        this.untreadSum = untreadSum;
    }
	/**
    */	
    public String getAddPeriodDate() {
        return this.addPeriodDate;
    }
	/**
    */	
    public void setAddPeriodDate(String addPeriodDate) {
        this.addPeriodDate = addPeriodDate;
    }
	/**
    */	
    public String getReplacementSign() {
        return this.replacementSign;
    }
	/**
    */	
    public void setReplacementSign(String replacementSign) {
        this.replacementSign = replacementSign;
    }
	/**
    */	
    public BigDecimal getCommissionChargeRatio() {
        return this.commissionChargeRatio;
    }
	/**
    */	
    public void setCommissionChargeRatio(BigDecimal commissionChargeRatio) {
        this.commissionChargeRatio = commissionChargeRatio;
    }
	/**
    */	
    public BigDecimal getBailSum() {
        return this.bailSum;
    }
	/**
    */	
    public void setBailSum(BigDecimal bailSum) {
        this.bailSum = bailSum;
    }
	/**
    */	
    public BigDecimal getReplacementBalance() {
        return this.replacementBalance;
    }
	/**
    */	
    public void setReplacementBalance(BigDecimal replacementBalance) {
        this.replacementBalance = replacementBalance;
    }
	/**
    */	
    public String getFinancingInd() {
        return this.financingInd;
    }
	/**
    */	
    public void setFinancingInd(String financingInd) {
        this.financingInd = financingInd;
    }
	/**
    */	
    public String getLetterOfCreditState() {
        return this.letterOfCreditState;
    }
	/**
    */	
    public void setLetterOfCreditState(String letterOfCreditState) {
        this.letterOfCreditState = letterOfCreditState;
    }
	/**
    */	
    public String getQxRevertDate() {
        return this.qxRevertDate;
    }
	/**
    */	
    public void setQxRevertDate(String qxRevertDate) {
        this.qxRevertDate = qxRevertDate;
    }
	/**
    */	
    public String getLastMaintainDate() {
        return this.lastMaintainDate;
    }
	/**
    */	
    public void setLastMaintainDate(String lastMaintainDate) {
        this.lastMaintainDate = lastMaintainDate;
    }
	/**
    */	
    public BigDecimal getCreditBalance() {
        return this.creditBalance;
    }
	/**
    */	
    public void setCreditBalance(BigDecimal creditBalance) {
        this.creditBalance = creditBalance;
    }
	/**
    */	
    public BigDecimal getTmpAmt() {
        return this.tmpAmt;
    }
	/**
    */	
    public void setTmpAmt(BigDecimal tmpAmt) {
        this.tmpAmt = tmpAmt;
    }
	/**
    */	
    public String getPostalOrderState() {
        return this.postalOrderState;
    }
	/**
    */	
    public void setPostalOrderState(String postalOrderState) {
        this.postalOrderState = postalOrderState;
    }
	/**
    */	
    public String getFourLevel() {
        return this.fourLevel;
    }
	/**
    */	
    public void setFourLevel(String fourLevel) {
        this.fourLevel = fourLevel;
    }
	/**
    */	
    public String getFiveLevel() {
        return this.fiveLevel;
    }
	/**
    */	
    public void setFiveLevel(String fiveLevel) {
        this.fiveLevel = fiveLevel;
    }
	/**
    */	
    public String getStatus() {
        return this.status;
    }
	/**
    */	
    public void setStatus(String status) {
        this.status = status;
    }
	/**
    */	
    public String getCurrencyCd() {
        return this.currencyCd;
    }
	/**
    */	
    public void setCurrencyCd(String currencyCd) {
        this.currencyCd = currencyCd;
    }
	/**
    */	
    public String getRecState() {
        return this.recState;
    }
	/**
    */	
    public void setRecState(String recState) {
        this.recState = recState;
    }
	/**
    */	
    public String getWriteOffDate() {
        return this.writeOffDate;
    }
	/**
    */	
    public void setWriteOffDate(String writeOffDate) {
        this.writeOffDate = writeOffDate;
    }
	/**
    */	
    public String getAdvAcctNo() {
        return this.advAcctNo;
    }
	/**
    */	
    public void setAdvAcctNo(String advAcctNo) {
        this.advAcctNo = advAcctNo;
    }
	/**
    */	
    public BigDecimal getAdvAmt() {
        return this.advAmt;
    }
	/**
    */	
    public void setAdvAmt(BigDecimal advAmt) {
        this.advAmt = advAmt;
    }
	/**
    */	
    public BigDecimal getAdvOutBa() {
        return this.advOutBa;
    }
	/**
    */	
    public void setAdvOutBa(BigDecimal advOutBa) {
        this.advOutBa = advOutBa;
    }
	/**
    */	
    public BigDecimal getAdvInt() {
        return this.advInt;
    }
	/**
    */	
    public void setAdvInt(BigDecimal advInt) {
        this.advInt = advInt;
    }
	/**
    */	
    public String getBorrowStatus() {
        return this.borrowStatus;
    }
	/**
    */	
    public void setBorrowStatus(String borrowStatus) {
        this.borrowStatus = borrowStatus;
    }
	/**
    */	
    public String getBillStatus() {
        return this.billStatus;
    }
	/**
    */	
    public void setBillStatus(String billStatus) {
        this.billStatus = billStatus;
    }
	/**
    * Get the 预警表ID
    */	
    public String getWarnId() {
        return this.warnId;
    }
	/**
    * Set the 预警表ID
    */	
    public void setWarnId(String warnId) {
        this.warnId = warnId;
    }
	/**
    * Get the 数据日期
    */	
    public String getDataDt() {
        return this.dataDt;
    }
	/**
    * Set the 数据日期
    */	
    public void setDataDt(String dataDt) {
        this.dataDt = dataDt;
    }
}