package com.gbicc.warn.ComninationWarn.entity;
// Generated 2015-12-31 14:42:59 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * TCwThresholdversion generated by hbm2java
 */
public class TCwThresholdversion  implements java.io.Serializable {


    /*
    * id.
    */
    private String id;
    /*
    * 阈值版本号.
    */
    private String version;
    /*
    * 黄色边界值.
    */
    private String yellow;
    /*
    * 红色边界值.
    */
    private String red;
    /*
    * 更新时间.
    */
    private Date updatetime;
    /*
    * 更新人员.
    */
    private String operator;
    /*
    * 指标编号.
    */
    private String indexCode;

    public TCwThresholdversion() {
    }

	
    public TCwThresholdversion(String id) {
        this.id = id;
    }
    public TCwThresholdversion(String id, String version, String yellow, String red, Date updatetime, String operator, String indexCode) {
       this.id = id;
       this.version = version;
       this.yellow = yellow;
       this.red = red;
       this.updatetime = updatetime;
       this.operator = operator;
       this.indexCode = indexCode;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public String getYellow() {
        return this.yellow;
    }
    
    public void setYellow(String yellow) {
        this.yellow = yellow;
    }
    public String getRed() {
        return this.red;
    }
    
    public void setRed(String red) {
        this.red = red;
    }
    public Date getUpdatetime() {
        return this.updatetime;
    }
    
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }
    public String getIndexCode() {
        return this.indexCode;
    }
    
    public void setIndexCode(String indexCode) {
        this.indexCode = indexCode;
    }




}


