package com.gbicc.company.view.externaldata.entity;

import java.util.Date;

// default package
// Generated 2016-5-31 9:15:50 by Hibernate Tools 3.4.0.CR1

/**
 * TDataGsxtIcException generated by hbm2java
 */
public class TDataGsxtIcException implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3968880076828308070L;
	private String id;
	private String fdEntId;
	private Integer fdSequence;
	private String fdInExceptionReson;
	private String fdInExceptionDate;
	private String fdOutExceptionReson;
	private String fdOutExceptionDate;
	private String fdDecisionOrg;
	private Date fdUpdateTime;
	private String fdJbkId;
	private String fdRegNum;
	private String fdName;
	private String fdType;
	private String fdLecalPerson;
	private String fdRegCapital;
	private String fdSetUpDate;
	private String fdEntAddress;
	private String fdBusinessTermStart;
	private String fdBusinessTermEnd;
	private String fdBusinessScope;
	private String fdRegOrg;
	private String fdApprovalDate;
	private String fdRegStatus;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getFdEntId() {
		return fdEntId;
	}
	public void setFdEntId(String fdEntId) {
		this.fdEntId = fdEntId;
	}
	public Integer getFdSequence() {
		return fdSequence;
	}
	public void setFdSequence(Integer fdSequence) {
		this.fdSequence = fdSequence;
	}
	public String getFdInExceptionReson() {
		return fdInExceptionReson;
	}
	public void setFdInExceptionReson(String fdInExceptionReson) {
		this.fdInExceptionReson = fdInExceptionReson;
	}
	public String getFdInExceptionDate() {
		return fdInExceptionDate;
	}
	public void setFdInExceptionDate(String fdInExceptionDate) {
		this.fdInExceptionDate = fdInExceptionDate;
	}
	public String getFdOutExceptionReson() {
		return fdOutExceptionReson;
	}
	public void setFdOutExceptionReson(String fdOutExceptionReson) {
		this.fdOutExceptionReson = fdOutExceptionReson;
	}
	public String getFdOutExceptionDate() {
		return fdOutExceptionDate;
	}
	public void setFdOutExceptionDate(String fdOutExceptionDate) {
		this.fdOutExceptionDate = fdOutExceptionDate;
	}
	public String getFdDecisionOrg() {
		return fdDecisionOrg;
	}
	public void setFdDecisionOrg(String fdDecisionOrg) {
		this.fdDecisionOrg = fdDecisionOrg;
	}
	public Date getFdUpdateTime() {
		return fdUpdateTime;
	}
	public void setFdUpdateTime(Date fdUpdateTime) {
		this.fdUpdateTime = fdUpdateTime;
	}
	public String getFdJbkId() {
		return fdJbkId;
	}
	public void setFdJbkId(String fdJbkId) {
		this.fdJbkId = fdJbkId;
	}
	public String getFdRegNum() {
		return fdRegNum;
	}
	public void setFdRegNum(String fdRegNum) {
		this.fdRegNum = fdRegNum;
	}
	public String getFdName() {
		return fdName;
	}
	public void setFdName(String fdName) {
		this.fdName = fdName;
	}
	public String getFdType() {
		return fdType;
	}
	public void setFdType(String fdType) {
		this.fdType = fdType;
	}
	public String getFdLecalPerson() {
		return fdLecalPerson;
	}
	public void setFdLecalPerson(String fdLecalPerson) {
		this.fdLecalPerson = fdLecalPerson;
	}
	public String getFdRegCapital() {
		return fdRegCapital;
	}
	public void setFdRegCapital(String fdRegCapital) {
		this.fdRegCapital = fdRegCapital;
	}
	public String getFdSetUpDate() {
		return fdSetUpDate;
	}
	public void setFdSetUpDate(String fdSetUpDate) {
		this.fdSetUpDate = fdSetUpDate;
	}
	public String getFdEntAddress() {
		return fdEntAddress;
	}
	public void setFdEntAddress(String fdEntAddress) {
		this.fdEntAddress = fdEntAddress;
	}
	public String getFdBusinessTermStart() {
		return fdBusinessTermStart;
	}
	public void setFdBusinessTermStart(String fdBusinessTermStart) {
		this.fdBusinessTermStart = fdBusinessTermStart;
	}
	public String getFdBusinessTermEnd() {
		return fdBusinessTermEnd;
	}
	public void setFdBusinessTermEnd(String fdBusinessTermEnd) {
		this.fdBusinessTermEnd = fdBusinessTermEnd;
	}
	public String getFdBusinessScope() {
		return fdBusinessScope;
	}
	public void setFdBusinessScope(String fdBusinessScope) {
		this.fdBusinessScope = fdBusinessScope;
	}
	public String getFdRegOrg() {
		return fdRegOrg;
	}
	public void setFdRegOrg(String fdRegOrg) {
		this.fdRegOrg = fdRegOrg;
	}
	public String getFdApprovalDate() {
		return fdApprovalDate;
	}
	public void setFdApprovalDate(String fdApprovalDate) {
		this.fdApprovalDate = fdApprovalDate;
	}
	public String getFdRegStatus() {
		return fdRegStatus;
	}
	public void setFdRegStatus(String fdRegStatus) {
		this.fdRegStatus = fdRegStatus;
	}

}
