package com.gbicc.rule.entity;

// Generated 2011-11-5 20:30:11 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * TRulDefinitionId generated by hbm2java
 */
public class TRulDefinition implements java.io.Serializable {

	private static final long serialVersionUID = 4653364134845269956L;
	
	public TRulDefinition(){
		
	}
	
	public TRulDefinition(
			String id, 
			String ruleCode, 
			String ruleName,
			String ruleLevel, 
			String ruleApplyobj, 
			String ruleRemark,
			String ruleType) {
		super();
		this.id = id;
		this.ruleCode = ruleCode;
		this.ruleName = ruleName;
		this.ruleLevel = ruleLevel;
		this.ruleApplyobj = ruleApplyobj;
		this.ruleRemark = ruleRemark;
		this.ruleType = ruleType;
	}
	
	
	public TRulDefinition(String id, String ruleCode, String ruleName,
			String ruleContent, Date ruleCreateddate, Date ruleUpdateddate,
			Integer ruleVersion, String categoryId, String ruleStatus,
			String enable, String triggerFreq, String triggerType,
			Integer triggerPeriodInterval, String triggerPeriodUnit,
			String ruleLevel, String ruleApplyobj, String ruleRemark,
			String ruleType, String approveLevel) {
		this.id = id;
		this.ruleCode = ruleCode;
		this.ruleName = ruleName;
		this.ruleContent = ruleContent;
		this.ruleCreateddate = ruleCreateddate;
		this.ruleUpdateddate = ruleUpdateddate;
		this.ruleVersion = ruleVersion;
		this.categoryId = categoryId;
		this.ruleStatus = ruleStatus;
		this.enable = enable;
		this.triggerFreq = triggerFreq;
		this.triggerType = triggerType;
		this.triggerPeriodInterval = triggerPeriodInterval;
		this.triggerPeriodUnit = triggerPeriodUnit;
		this.ruleLevel = ruleLevel;
		this.ruleApplyobj = ruleApplyobj;
		this.ruleRemark = ruleRemark;
		this.ruleType = ruleType;
		this.approveLevel = approveLevel;
	}


	/*
    */
	private String id;
	/*
	 * 规则编号.
	 */
	private String ruleCode;
	/*
	 * 规则名称.
	 */
	private String ruleName;
	/*
	 * 规则脚本内容.
	 */
	private String ruleContent;
	/*
	 * 规则创建时间.
	 */
	private Date ruleCreateddate;
	/*
	 * 规则修改时间.
	 */
	private Date ruleUpdateddate;
	/*
	 * 规则版本.
	 */
	private Integer ruleVersion;
	/*
	 * 分类目录.
	 */
	private String categoryId;
	/*
	 * 规则状态.
	 */
	private String ruleStatus;
	/*
	 * 状态
	 */
	private String enable;
	/*
	 * 触发频率.
	 */
	private String triggerFreq;
	/*
	 * 触发类型
	 */
	private String triggerType;
	/*
	 * 触发周期间隔
	 */
	private Integer triggerPeriodInterval;
	/*
	 * 触发周期单位
	 */
	private String triggerPeriodUnit;
	/*
	 * 规则等级
	 */
	private String ruleLevel;
	/*
	 * 规则适用对象
	 */
	private String ruleApplyobj;
	/*
	 * 规则备注
	 */
	private String ruleRemark;
	/*
	 * 规则类型
	 */
	private String ruleType;
	/*
	 * 规则审批等级
	 */
	private String approveLevel;
	
	public String getApproveLevel() {
		return approveLevel;
	}
	public void setApproveLevel(String approveLevel) {
		this.approveLevel = approveLevel;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getRuleCode() {
		return ruleCode;
	}
	public void setRuleCode(String ruleCode) {
		this.ruleCode = ruleCode;
	}
	public String getRuleName() {
		return ruleName;
	}
	public void setRuleName(String ruleName) {
		this.ruleName = ruleName;
	}
	public String getRuleContent() {
		return ruleContent;
	}
	public void setRuleContent(String ruleContent) {
		this.ruleContent = ruleContent;
	}
	public Date getRuleCreateddate() {
		return ruleCreateddate;
	}
	public void setRuleCreateddate(Date ruleCreateddate) {
		this.ruleCreateddate = ruleCreateddate;
	}
	public Date getRuleUpdateddate() {
		return ruleUpdateddate;
	}
	public void setRuleUpdateddate(Date ruleUpdateddate) {
		this.ruleUpdateddate = ruleUpdateddate;
	}
	public Integer getRuleVersion() {
		return ruleVersion;
	}
	public void setRuleVersion(Integer ruleVersion) {
		this.ruleVersion = ruleVersion;
	}
	public String getCategoryId() {
		return categoryId;
	}
	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}
	public String getRuleStatus() {
		return ruleStatus;
	}
	public void setRuleStatus(String ruleStatus) {
		this.ruleStatus = ruleStatus;
	}
	public String getEnable() {
		return enable;
	}
	public void setEnable(String enable) {
		this.enable = enable;
	}
	public String getTriggerFreq() {
		return triggerFreq;
	}
	public void setTriggerFreq(String triggerFreq) {
		this.triggerFreq = triggerFreq;
	}
	public String getTriggerType() {
		return triggerType;
	}
	public void setTriggerType(String triggerType) {
		this.triggerType = triggerType;
	}
	public Integer getTriggerPeriodInterval() {
		return triggerPeriodInterval;
	}
	public void setTriggerPeriodInterval(Integer triggerPeriodInterval) {
		this.triggerPeriodInterval = triggerPeriodInterval;
	}
	public String getTriggerPeriodUnit() {
		return triggerPeriodUnit;
	}
	public void setTriggerPeriodUnit(String triggerPeriodUnit) {
		this.triggerPeriodUnit = triggerPeriodUnit;
	}
	public String getRuleLevel() {
		return ruleLevel;
	}
	public void setRuleLevel(String ruleLevel) {
		this.ruleLevel = ruleLevel;
	}
	public String getRuleApplyobj() {
		return ruleApplyobj;
	}
	public void setRuleApplyobj(String ruleApplyobj) {
		this.ruleApplyobj = ruleApplyobj;
	}
	public String getRuleRemark() {
		return ruleRemark;
	}
	public void setRuleRemark(String ruleRemark) {
		this.ruleRemark = ruleRemark;
	}
	public String getRuleType() {
		return ruleType;
	}
	public void setRuleType(String ruleType) {
		this.ruleType = ruleType;
	}
}
