package com.gbicc.personCommon.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 评估信息表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TEdwPlsEvaluation implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 抵质押编号. */
	private String assuid;

	/** 账户ID. */
	private String loanacno;

	/** 评估价值. */
	private Double evalvalue;

	/** 评估日期. */
	private Date evaldate;

	/** 评估机构编号. */
	private String evalcorpid;

	/** 评估机构名称. */
	private String evalcorpname;

	/** 数据日期. */
	private Date m006;

	/**
	 * Constructor.
	 */
	public TEdwPlsEvaluation() {
	}

	/**
	 * Set the 抵质押编号.
	 * 
	 * @param assuid
	 *            抵质押编号
	 */
	public void setAssuid(String assuid) {
		this.assuid = assuid;
	}

	/**
	 * Get the 抵质押编号.
	 * 
	 * @return 抵质押编号
	 */
	public String getAssuid() {
		return this.assuid;
	}

	/**
	 * Set the 账户ID.
	 * 
	 * @param loanacno
	 *            账户ID
	 */
	public void setLoanacno(String loanacno) {
		this.loanacno = loanacno;
	}

	/**
	 * Get the 账户ID.
	 * 
	 * @return 账户ID
	 */
	public String getLoanacno() {
		return this.loanacno;
	}

	/**
	 * Set the 评估价值.
	 * 
	 * @param evalvalue
	 *            评估价值
	 */
	public void setEvalvalue(Double evalvalue) {
		this.evalvalue = evalvalue;
	}

	/**
	 * Get the 评估价值.
	 * 
	 * @return 评估价值
	 */
	public Double getEvalvalue() {
		return this.evalvalue;
	}

	/**
	 * Set the 评估日期.
	 * 
	 * @param evaldate
	 *            评估日期
	 */
	public void setEvaldate(Date evaldate) {
		this.evaldate = evaldate;
	}

	/**
	 * Get the 评估日期.
	 * 
	 * @return 评估日期
	 */
	public Date getEvaldate() {
		return this.evaldate;
	}

	/**
	 * Set the 评估机构编号.
	 * 
	 * @param evalcorpid
	 *            评估机构编号
	 */
	public void setEvalcorpid(String evalcorpid) {
		this.evalcorpid = evalcorpid;
	}

	/**
	 * Get the 评估机构编号.
	 * 
	 * @return 评估机构编号
	 */
	public String getEvalcorpid() {
		return this.evalcorpid;
	}

	/**
	 * Set the 评估机构名称.
	 * 
	 * @param evalcorpname
	 *            评估机构名称
	 */
	public void setEvalcorpname(String evalcorpname) {
		this.evalcorpname = evalcorpname;
	}

	/**
	 * Get the 评估机构名称.
	 * 
	 * @return 评估机构名称
	 */
	public String getEvalcorpname() {
		return this.evalcorpname;
	}

	/**
	 * Set the 数据日期.
	 * 
	 * @param m006
	 *            数据日期
	 */
	public void setM006(Date m006) {
		this.m006 = m006;
	}

	/**
	 * Get the 数据日期.
	 * 
	 * @return 数据日期
	 */
	public Date getM006() {
		return this.m006;
	}


}
