package com.gbicc.company.single.entity;
// Generated 2015-11-28 14:51:34 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import com.huateng.ebank.entity.data.mng.Bctl;
import com.huateng.ebank.entity.data.mng.TlrInfo;

/**
 * TCmSingleRulCases generated by hbm2java
 */
public class TCmSingleRulCases  implements java.io.Serializable {

	private static final long serialVersionUID = 3047981364565672040L;
	
	/*
    * ID主键.
    */
    private String id;
    /*
    * 案例编号.
    */
    private String casesCode;
    /*
    * 案例名称.
    */
    private String casesName;
    /*
    * 案例状态.
    */
    private String casesStatus;
    /*
    * 案例描述.
    */
    private String casesDesc;
    /*
    * 案例性质.
    */
    private String casesNature;
    /*
    * 案例结论.
    */
    private String casesConclusion;
    /*
    * 是否后续关注.
    */
    private String followupFlag;
    /*
    * 创建日期.
    */
    private Date createDt;
    /*
    * 创建机构.
    */
    private Bctl createOrg;
    /*
    * 创建人.
    */
    private TlrInfo createUser;
    /*
     * 处理机构(head:总行,sub:分支行).
     */
    private String handleOrgFlag;
    
    /*
     * 预警信息条数（临时字段）
     */
    private Integer warnCount;
    /*
     * 发起协查任务数（临时字段）
     */
    private Integer inveCount;
    /*
     * 已完成协查任务数（临时字段）
     */
    private Integer alreInveCount;

    public TCmSingleRulCases() {
    }

    public TCmSingleRulCases(String id) {
        this.id = id;
    }
    public TCmSingleRulCases(String id, String casesCode, String casesName, String casesStatus, String casesDesc, String casesNature, String casesConclusion, String followupFlag, Date createDt, Bctl createOrg, TlrInfo createUser) {
       this.id = id;
       this.casesCode = casesCode;
       this.casesName = casesName;
       this.casesStatus = casesStatus;
       this.casesDesc = casesDesc;
       this.casesNature = casesNature;
       this.casesConclusion = casesConclusion;
       this.followupFlag = followupFlag;
       this.createDt = createDt;
       this.createOrg = createOrg;
       this.createUser = createUser;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCasesCode() {
        return this.casesCode;
    }
    
    public void setCasesCode(String casesCode) {
        this.casesCode = casesCode;
    }
    public String getCasesName() {
        return this.casesName;
    }
    
    public void setCasesName(String casesName) {
        this.casesName = casesName;
    }
    public String getCasesStatus() {
        return this.casesStatus;
    }
    
    public void setCasesStatus(String casesStatus) {
        this.casesStatus = casesStatus;
    }
    public String getCasesDesc() {
        return this.casesDesc;
    }
    
    public void setCasesDesc(String casesDesc) {
        this.casesDesc = casesDesc;
    }
    public String getCasesNature() {
        return this.casesNature;
    }
    
    public void setCasesNature(String casesNature) {
        this.casesNature = casesNature;
    }
    public String getCasesConclusion() {
        return this.casesConclusion;
    }
    
    public void setCasesConclusion(String casesConclusion) {
        this.casesConclusion = casesConclusion;
    }
    public String getFollowupFlag() {
        return this.followupFlag;
    }
    
    public void setFollowupFlag(String followupFlag) {
        this.followupFlag = followupFlag;
    }
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }
    public Bctl getCreateOrg() {
        return this.createOrg;
    }
    
    public void setCreateOrg(Bctl createOrg) {
        this.createOrg = createOrg;
    }
    public TlrInfo getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(TlrInfo createUser) {
        this.createUser = createUser;
    }

	public String getHandleOrgFlag() {
		return handleOrgFlag;
	}

	public void setHandleOrgFlag(String handleOrgFlag) {
		this.handleOrgFlag = handleOrgFlag;
	}

	public Integer getWarnCount() {
		return warnCount;
	}

	public void setWarnCount(Integer warnCount) {
		this.warnCount = warnCount;
	}

	public Integer getInveCount() {
		return inveCount;
	}

	public void setInveCount(Integer inveCount) {
		this.inveCount = inveCount;
	}

	public Integer getAlreInveCount() {
		return alreInveCount;
	}

	public void setAlreInveCount(Integer alreInveCount) {
		this.alreInveCount = alreInveCount;
	}
}