package com.gbicc.company.warnDisposal.entity;
// Generated 2015-11-27 11:18:28 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import com.huateng.ebank.entity.data.mng.Bctl;
import com.huateng.ebank.entity.data.mng.TlrInfo;

/**
 * TCmCustomer generated by hbm2java
 */
public class TCmCustomer  implements java.io.Serializable {


    /**
	 * 
	 */
	private static final long serialVersionUID = 1883484173579154647L;
	/*
    */
    private String id;
    /*
    * 客户编号.
    */
    private String custcode;
    /*
    * 客户名称.
    */
    private String custname;
    /*
    * 客户预警等级.
    */
    private String custWarnLevel;
    /*
    * 客户所属机构.
    */
    private String operBank;
    /*
    * 客户经理.
    */
    private String operator;
    /*
    * 贷款金额.
    */
    private Double loanAmount;
    /*
    * 贷款余额.
    */
    private Double loanBalance;
    /*
    * 借款账号.
    */
    private String loanAccount;
    /*
    * 创建日期.
    */
    private Date credited;
    /*
    * 营业执照编号.
    */
    private String businessCode;
    /*
    * 法人代表.
    */
    private String legalRep;
    
    /*
     * 任务编号----非事务字段  无需映射
     */
    private String taskCode;
    
    
    public TCmCustomer() {
    }

	
    public TCmCustomer(String id) {
        this.id = id;
    }
    public TCmCustomer(String id, String custcode, String custname, String custWarnLevel, String operBank, String operator, Double loanAmount, Double loanBalance, String loanAccount, Date credited, String businessCode, String legalRep) {
       this.id = id;
       this.custcode = custcode;
       this.custname = custname;
       this.custWarnLevel = custWarnLevel;
       this.operBank = operBank;
       this.operator = operator;
       this.loanAmount = loanAmount;
       this.loanBalance = loanBalance;
       this.loanAccount = loanAccount;
       this.credited = credited;
       this.businessCode = businessCode;
       this.legalRep = legalRep;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCustcode() {
        return this.custcode;
    }
    
    public void setCustcode(String custcode) {
        this.custcode = custcode;
    }
    public String getCustname() {
        return this.custname;
    }
    
    public void setCustname(String custname) {
        this.custname = custname;
    }
    public String getCustWarnLevel() {
        return this.custWarnLevel;
    }
    
    public void setCustWarnLevel(String custWarnLevel) {
        this.custWarnLevel = custWarnLevel;
    }
    
    
    public String getOperBank() {
		return operBank;
	}


	public void setOperBank(String operBank) {
		this.operBank = operBank;
	}


	public String getOperator() {
		return operator;
	}


	public void setOperator(String operator) {
		this.operator = operator;
	}


	public Double getLoanAmount() {
        return this.loanAmount;
    }
    
    public void setLoanAmount(Double loanAmount) {
        this.loanAmount = loanAmount;
    }
    public Double getLoanBalance() {
        return this.loanBalance;
    }
    
    public void setLoanBalance(Double loanBalance) {
        this.loanBalance = loanBalance;
    }
    public String getLoanAccount() {
        return this.loanAccount;
    }
    
    public void setLoanAccount(String loanAccount) {
        this.loanAccount = loanAccount;
    }
    public Date getCredited() {
        return this.credited;
    }
    
    public void setCredited(Date credited) {
        this.credited = credited;
    }
    public String getBusinessCode() {
        return this.businessCode;
    }
    
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }
    public String getLegalRep() {
        return this.legalRep;
    }
    
    public void setLegalRep(String legalRep) {
        this.legalRep = legalRep;
    }

	public String getTaskCode() {
		return taskCode;
	}


	public void setTaskCode(String taskCode) {
		this.taskCode = taskCode;
	}


	




}


