package com.gbicc.company.warnDisposal.entity;
// Generated 2015-11-27 11:18:28 by Hibernate Tools 3.2.2.GA



/**
 * TCmWarnControlmeasure generated by hbm2java
 */
public class TCmWarnControlmeasure  implements java.io.Serializable {


    /**
	 * 
	 */
	private static final long serialVersionUID = 1198703365519662967L;
	/*
    * ID.
    */
    private String id;
    /*
    * 风控措施.
    */
    private String conmeasCode;
    /*
    * 风控说明.
    */
    private String conmeasDesc;
    /*
    * 任务编号.
    */
    private String taskId;
    /*
    * 任务类型.
    */
    private String taskType;

    public TCmWarnControlmeasure() {
    }

	
    public TCmWarnControlmeasure(String id) {
        this.id = id;
    }
    public TCmWarnControlmeasure(String id, String conmeasCode, String conmeasDesc, String taskId, String taskType) {
       this.id = id;
       this.conmeasCode = conmeasCode;
       this.conmeasDesc = conmeasDesc;
       this.taskId = taskId;
       this.taskType = taskType;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getConmeasCode() {
        return this.conmeasCode;
    }
    
    public void setConmeasCode(String conmeasCode) {
        this.conmeasCode = conmeasCode;
    }
    public String getConmeasDesc() {
        return this.conmeasDesc;
    }
    
    public void setConmeasDesc(String conmeasDesc) {
        this.conmeasDesc = conmeasDesc;
    }
    public String getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }
    public String getTaskType() {
        return this.taskType;
    }
    
    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }




}


