package com.gbicc.company.warnDisposal.entity;
// Generated 2016-1-10 16:58:44 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * TCmWarnTaskCount generated by hbm2java
 */
public class TCmWarnTaskCount  implements java.io.Serializable {


    /*
    * ID.
    */
    private String id;
    /*
    * 任务ID.
    */
    private String taskId;
    /*
    * 客户ID.
    */
    private String customerId;
    /*
    * 流程ID.
    */
    private String processId;
    /*
    * 任务类型.
    */
    private String taskType;
    /*
    * 是否超时.
    */
    private String isChaoshi;
    /*
    */
    private String operator;
    /*
    */
    private String orgCode;
    /*
    * 客户经理是否处理.
    */
    private String isChuli;
    /*
    * 任务生成日期.
    */
    private Date credited;

    public TCmWarnTaskCount() {
    }

	
    public TCmWarnTaskCount(String id) {
        this.id = id;
    }
    public TCmWarnTaskCount(String id, String taskId, String customerId, String processId, String taskType, String isChaoshi, String operator, String orgCode, String isChuli, Date credited) {
       this.id = id;
       this.taskId = taskId;
       this.customerId = customerId;
       this.processId = processId;
       this.taskType = taskType;
       this.isChaoshi = isChaoshi;
       this.operator = operator;
       this.orgCode = orgCode;
       this.isChuli = isChuli;
       this.credited = credited;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
    public String getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(String processId) {
        this.processId = processId;
    }
    public String getTaskType() {
        return this.taskType;
    }
    
    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }
    public String getIsChaoshi() {
        return this.isChaoshi;
    }
    
    public void setIsChaoshi(String isChaoshi) {
        this.isChaoshi = isChaoshi;
    }
    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }
    public String getOrgCode() {
        return this.orgCode;
    }
    
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }
    public String getIsChuli() {
        return this.isChuli;
    }
    
    public void setIsChuli(String isChuli) {
        this.isChuli = isChuli;
    }
    public Date getCredited() {
        return this.credited;
    }
    
    public void setCredited(Date credited) {
        this.credited = credited;
    }




}


