package com.gbicc.company.single.outputentity;
// Generated 2016-4-13 15:01:47 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * TRewA30FrimId generated by hbm2java
 */
public class A30  implements java.io.Serializable {

	private static final long serialVersionUID = -4198946191400430330L;
	
	/*
    * 银行号.
    */
    private String socNo;
    /*
    * 账号.
    */
    private String acctNo;
    /*
    * 交易日期.
    */
    private String postDate;
    /*
    * 流水号.
    */
    private String jrnlNo;
    /*
    * 业务种类.
    */
    private String businessType;
    /*
    * 交易时间.
    */
    private Integer postTime;
    /*
    * 冻结轮顺序号.
    */
    private Integer seqNo;
    /*
    * 经办柜员.
    */
    private String tellerNo;
    /*
    * 经办机构.
    */
    private String branchNo;
    /*
    * 授权柜员.
    */
    private String supTellerNo;
    /*
    * 状态.
    */
    private String status;
    /*
    * 账户名称.
    */
    private String customerName;
    /*
    * 有权机关全称.
    */
    private String governmentAgency;
    /*
    * 执法人员姓名.
    */
    private String lawEnforceOfir;
    /*
    * 客户证件名称.
    */
    private String officerIdName;
    /*
    * 客户证件编号.
    */
    private String officerIdNo;
    /*
    * 法律文书名称.
    */
    private String legalDocName;
    /*
    * 通知书编号.
    */
    private String noticeNo;
    /*
    * 冻结种类.
    */
    private String freezeType;
    /*
    * 冻结原因.
    */
    private String freezeReason;
    /*
    * 账户透支标识.
    */
    private String odInd;
    /*
    * 冻结金额.
    */
    private BigDecimal freezeAmount;
    /*
    * 原冻结流水号.
    */
    private String oriFreezeJrnlNo;
    /*
    * 原冻结日期.
    */
    private String oriFreezeDate;
    /*
    * 冻结到期日.
    */
    private String freezeMatDate;
    /*
    * 扣划种类.
    */
    private String trfType;
    /*
    * 扣划金额.
    */
    private BigDecimal trfAmount;
    /*
    * 收款人账号.
    */
    private String receiveAcctNo;
    /*
    * 收款人名称.
    */
    private String receiveCustName;
    /*
    * 收款人行名.
    */
    private String receiveBankName;
    /*
    * 扣划销账码.
    */
    private String trfSrnNo;
    /*
    * 查询内容及结果.
    */
    private String enquiryContent;
    /*
    * 备注.
    */
    private String remark;
    /*
    * 子账户类别.
    */
    private String subType;
    /*
    * 册号.
    */
    private String volumeNo;
    /*
    * 序号.
    */
    private String sequenceNo;
    /*
    * 扣划优先级.
    */
    private String priorityNo;
    /*
    * 账户余额.
    */
    private BigDecimal acctBalance;
    /*
    * 可冻金额.
    */
    private BigDecimal availAmt;
    /*
    * 已被其他有权机关冻结金额.
    */
    private BigDecimal othGovFreeAmt;
    /*
    * 已被保证金冻结金额.
    */
    private BigDecimal marFreeAmt;
    /*
    * 质押冻结标识.
    */
    private String pleFreeFlg;
    /*
    * 实际冻结金额.
    */
    private BigDecimal realFreezeAmt;
    /*
    * 原冻结金额.
    */
    private BigDecimal origFreezeAmt;
    /*
    * 预警表ID.
    */
    private String warnId;
    /*
    * 数据日期.
    */
    private Date dataDt;

	/**
    * Get the 银行号
    */	
    public String getSocNo() {
        return this.socNo;
    }
	/**
    * Set the 银行号
    */	
    public void setSocNo(String socNo) {
        this.socNo = socNo;
    }
	/**
    * Get the 账号
    */	
    public String getAcctNo() {
        return this.acctNo;
    }
	/**
    * Set the 账号
    */	
    public void setAcctNo(String acctNo) {
        this.acctNo = acctNo;
    }
	/**
    * Get the 交易日期
    */	
    public String getPostDate() {
        return this.postDate;
    }
	/**
    * Set the 交易日期
    */	
    public void setPostDate(String postDate) {
        this.postDate = postDate;
    }
	/**
    * Get the 流水号
    */	
    public String getJrnlNo() {
        return this.jrnlNo;
    }
	/**
    * Set the 流水号
    */	
    public void setJrnlNo(String jrnlNo) {
        this.jrnlNo = jrnlNo;
    }
	/**
    * Get the 业务种类
    */	
    public String getBusinessType() {
        return this.businessType;
    }
	/**
    * Set the 业务种类
    */	
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }
	/**
    * Get the 交易时间
    */	
    public Integer getPostTime() {
        return this.postTime;
    }
	/**
    * Set the 交易时间
    */	
    public void setPostTime(Integer postTime) {
        this.postTime = postTime;
    }
	/**
    * Get the 冻结轮顺序号
    */	
    public Integer getSeqNo() {
        return this.seqNo;
    }
	/**
    * Set the 冻结轮顺序号
    */	
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }
	/**
    * Get the 经办柜员
    */	
    public String getTellerNo() {
        return this.tellerNo;
    }
	/**
    * Set the 经办柜员
    */	
    public void setTellerNo(String tellerNo) {
        this.tellerNo = tellerNo;
    }
	/**
    * Get the 经办机构
    */	
    public String getBranchNo() {
        return this.branchNo;
    }
	/**
    * Set the 经办机构
    */	
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo;
    }
	/**
    * Get the 授权柜员
    */	
    public String getSupTellerNo() {
        return this.supTellerNo;
    }
	/**
    * Set the 授权柜员
    */	
    public void setSupTellerNo(String supTellerNo) {
        this.supTellerNo = supTellerNo;
    }
	/**
    * Get the 状态
    */	
    public String getStatus() {
        return this.status;
    }
	/**
    * Set the 状态
    */	
    public void setStatus(String status) {
        this.status = status;
    }
	/**
    * Get the 账户名称
    */	
    public String getCustomerName() {
        return this.customerName;
    }
	/**
    * Set the 账户名称
    */	
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
	/**
    * Get the 有权机关全称
    */	
    public String getGovernmentAgency() {
        return this.governmentAgency;
    }
	/**
    * Set the 有权机关全称
    */	
    public void setGovernmentAgency(String governmentAgency) {
        this.governmentAgency = governmentAgency;
    }
	/**
    * Get the 执法人员姓名
    */	
    public String getLawEnforceOfir() {
        return this.lawEnforceOfir;
    }
	/**
    * Set the 执法人员姓名
    */	
    public void setLawEnforceOfir(String lawEnforceOfir) {
        this.lawEnforceOfir = lawEnforceOfir;
    }
	/**
    * Get the 客户证件名称
    */	
    public String getOfficerIdName() {
        return this.officerIdName;
    }
	/**
    * Set the 客户证件名称
    */	
    public void setOfficerIdName(String officerIdName) {
        this.officerIdName = officerIdName;
    }
	/**
    * Get the 客户证件编号
    */	
    public String getOfficerIdNo() {
        return this.officerIdNo;
    }
	/**
    * Set the 客户证件编号
    */	
    public void setOfficerIdNo(String officerIdNo) {
        this.officerIdNo = officerIdNo;
    }
	/**
    * Get the 法律文书名称
    */	
    public String getLegalDocName() {
        return this.legalDocName;
    }
	/**
    * Set the 法律文书名称
    */	
    public void setLegalDocName(String legalDocName) {
        this.legalDocName = legalDocName;
    }
	/**
    * Get the 通知书编号
    */	
    public String getNoticeNo() {
        return this.noticeNo;
    }
	/**
    * Set the 通知书编号
    */	
    public void setNoticeNo(String noticeNo) {
        this.noticeNo = noticeNo;
    }
	/**
    * Get the 冻结种类
    */	
    public String getFreezeType() {
        return this.freezeType;
    }
	/**
    * Set the 冻结种类
    */	
    public void setFreezeType(String freezeType) {
        this.freezeType = freezeType;
    }
	/**
    * Get the 冻结原因
    */	
    public String getFreezeReason() {
        return this.freezeReason;
    }
	/**
    * Set the 冻结原因
    */	
    public void setFreezeReason(String freezeReason) {
        this.freezeReason = freezeReason;
    }
	/**
    * Get the 账户透支标识
    */	
    public String getOdInd() {
        return this.odInd;
    }
	/**
    * Set the 账户透支标识
    */	
    public void setOdInd(String odInd) {
        this.odInd = odInd;
    }
	/**
    * Get the 冻结金额
    */	
    public BigDecimal getFreezeAmount() {
        return this.freezeAmount;
    }
	/**
    * Set the 冻结金额
    */	
    public void setFreezeAmount(BigDecimal freezeAmount) {
        this.freezeAmount = freezeAmount;
    }
	/**
    * Get the 原冻结流水号
    */	
    public String getOriFreezeJrnlNo() {
        return this.oriFreezeJrnlNo;
    }
	/**
    * Set the 原冻结流水号
    */	
    public void setOriFreezeJrnlNo(String oriFreezeJrnlNo) {
        this.oriFreezeJrnlNo = oriFreezeJrnlNo;
    }
	/**
    * Get the 原冻结日期
    */	
    public String getOriFreezeDate() {
        return this.oriFreezeDate;
    }
	/**
    * Set the 原冻结日期
    */	
    public void setOriFreezeDate(String oriFreezeDate) {
        this.oriFreezeDate = oriFreezeDate;
    }
	/**
    * Get the 冻结到期日
    */	
    public String getFreezeMatDate() {
        return this.freezeMatDate;
    }
	/**
    * Set the 冻结到期日
    */	
    public void setFreezeMatDate(String freezeMatDate) {
        this.freezeMatDate = freezeMatDate;
    }
	/**
    * Get the 扣划种类
    */	
    public String getTrfType() {
        return this.trfType;
    }
	/**
    * Set the 扣划种类
    */	
    public void setTrfType(String trfType) {
        this.trfType = trfType;
    }
	/**
    * Get the 扣划金额
    */	
    public BigDecimal getTrfAmount() {
        return this.trfAmount;
    }
	/**
    * Set the 扣划金额
    */	
    public void setTrfAmount(BigDecimal trfAmount) {
        this.trfAmount = trfAmount;
    }
	/**
    * Get the 收款人账号
    */	
    public String getReceiveAcctNo() {
        return this.receiveAcctNo;
    }
	/**
    * Set the 收款人账号
    */	
    public void setReceiveAcctNo(String receiveAcctNo) {
        this.receiveAcctNo = receiveAcctNo;
    }
	/**
    * Get the 收款人名称
    */	
    public String getReceiveCustName() {
        return this.receiveCustName;
    }
	/**
    * Set the 收款人名称
    */	
    public void setReceiveCustName(String receiveCustName) {
        this.receiveCustName = receiveCustName;
    }
	/**
    * Get the 收款人行名
    */	
    public String getReceiveBankName() {
        return this.receiveBankName;
    }
	/**
    * Set the 收款人行名
    */	
    public void setReceiveBankName(String receiveBankName) {
        this.receiveBankName = receiveBankName;
    }
	/**
    * Get the 扣划销账码
    */	
    public String getTrfSrnNo() {
        return this.trfSrnNo;
    }
	/**
    * Set the 扣划销账码
    */	
    public void setTrfSrnNo(String trfSrnNo) {
        this.trfSrnNo = trfSrnNo;
    }
	/**
    * Get the 查询内容及结果
    */	
    public String getEnquiryContent() {
        return this.enquiryContent;
    }
	/**
    * Set the 查询内容及结果
    */	
    public void setEnquiryContent(String enquiryContent) {
        this.enquiryContent = enquiryContent;
    }
	/**
    * Get the 备注
    */	
    public String getRemark() {
        return this.remark;
    }
	/**
    * Set the 备注
    */	
    public void setRemark(String remark) {
        this.remark = remark;
    }
	/**
    * Get the 子账户类别
    */	
    public String getSubType() {
        return this.subType;
    }
	/**
    * Set the 子账户类别
    */	
    public void setSubType(String subType) {
        this.subType = subType;
    }
	/**
    * Get the 册号
    */	
    public String getVolumeNo() {
        return this.volumeNo;
    }
	/**
    * Set the 册号
    */	
    public void setVolumeNo(String volumeNo) {
        this.volumeNo = volumeNo;
    }
	/**
    * Get the 序号
    */	
    public String getSequenceNo() {
        return this.sequenceNo;
    }
	/**
    * Set the 序号
    */	
    public void setSequenceNo(String sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
	/**
    * Get the 扣划优先级
    */	
    public String getPriorityNo() {
        return this.priorityNo;
    }
	/**
    * Set the 扣划优先级
    */	
    public void setPriorityNo(String priorityNo) {
        this.priorityNo = priorityNo;
    }
	/**
    * Get the 账户余额
    */	
    public BigDecimal getAcctBalance() {
        return this.acctBalance;
    }
	/**
    * Set the 账户余额
    */	
    public void setAcctBalance(BigDecimal acctBalance) {
        this.acctBalance = acctBalance;
    }
	/**
    * Get the 可冻金额
    */	
    public BigDecimal getAvailAmt() {
        return this.availAmt;
    }
	/**
    * Set the 可冻金额
    */	
    public void setAvailAmt(BigDecimal availAmt) {
        this.availAmt = availAmt;
    }
	/**
    * Get the 已被其他有权机关冻结金额
    */	
    public BigDecimal getOthGovFreeAmt() {
        return this.othGovFreeAmt;
    }
	/**
    * Set the 已被其他有权机关冻结金额
    */	
    public void setOthGovFreeAmt(BigDecimal othGovFreeAmt) {
        this.othGovFreeAmt = othGovFreeAmt;
    }
	/**
    * Get the 已被保证金冻结金额
    */	
    public BigDecimal getMarFreeAmt() {
        return this.marFreeAmt;
    }
	/**
    * Set the 已被保证金冻结金额
    */	
    public void setMarFreeAmt(BigDecimal marFreeAmt) {
        this.marFreeAmt = marFreeAmt;
    }
	/**
    * Get the 质押冻结标识
    */	
    public String getPleFreeFlg() {
        return this.pleFreeFlg;
    }
	/**
    * Set the 质押冻结标识
    */	
    public void setPleFreeFlg(String pleFreeFlg) {
        this.pleFreeFlg = pleFreeFlg;
    }
	/**
    * Get the 实际冻结金额
    */	
    public BigDecimal getRealFreezeAmt() {
        return this.realFreezeAmt;
    }
	/**
    * Set the 实际冻结金额
    */	
    public void setRealFreezeAmt(BigDecimal realFreezeAmt) {
        this.realFreezeAmt = realFreezeAmt;
    }
	/**
    * Get the 原冻结金额
    */	
    public BigDecimal getOrigFreezeAmt() {
        return this.origFreezeAmt;
    }
	/**
    * Set the 原冻结金额
    */	
    public void setOrigFreezeAmt(BigDecimal origFreezeAmt) {
        this.origFreezeAmt = origFreezeAmt;
    }
	/**
    * Get the 预警表ID
    */	
    public String getWarnId() {
        return this.warnId;
    }
	/**
    * Set the 预警表ID
    */	
    public void setWarnId(String warnId) {
        this.warnId = warnId;
    }
	/**
    * Get the 数据日期
    */	
    public Date getDataDt() {
        return this.dataDt;
    }
	/**
    * Set the 数据日期
    */	
    public void setDataDt(Date dataDt) {
        this.dataDt = dataDt;
    }
}