package com.gbicc.company.single.outputentity;
// Generated 2016-1-12 19:22:04 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * TRewC05BuyContractId generated by hbm2java
 */
public class C05  implements java.io.Serializable {

	private static final long serialVersionUID = -5828455604246892923L;
	
	/*
    */
    private int id;
    /*
    */
    private Integer branchId;
    /*
    */
    private Integer acctBranchId;
    /*
    */
    private String taskType;
    /*
    */
    private String buyType;
    /*
    */
    private String buybizType;
    /*
    */
    private String centralBankflg;
    /*
    */
    private String buySigMk;
    /*
    */
    private String businessNo;
    /*
    */
    private String draftType;
    /*
    */
    private String draftAttr;
    /*
    */
    private Integer customerId;
    /*
    */
    private String customerCustno;
    /*
    */
    private String customerName;
    /*
    */
    private Integer customerBankNo;
    /*
    */
    private String customerAccount;
    /*
    */
    private BigDecimal rate;
    /*
    */
    private String rateType;
    /*
    */
    private BigDecimal rerate;
    /*
    */
    private String rerateType;
    /*
    */
    private String buyDate;
    /*
    */
    private String sttlmMk;
    /*
    */
    private String postponeType;
    /*
    */
    private String twoWayDate;
    /*
    */
    private String buySellDate;
    /*
    */
    private String buyBackBeginDate;
    /*
    */
    private String buyBackEndDate;
    /*
    */
    private String innerFlag;
    /*
    */
    private String virtualFlag;
    /*
    */
    private BigDecimal riskScale;
    /*
    */
    private String payType;
    /*
    */
    private String innerCustFlag;
    /*
    */
    private String payerName;
    /*
    */
    private String payerBankName;
    /*
    */
    private String payerAccount;
    /*
    */
    private BigDecimal payerScale;
    /*
    */
    private String agentName;
    /*
    */
    private Integer managerId;
    /*
    */
    private Integer departId;
    /*
    */
    private String discountFirstFlag;
    /*
    */
    private String mendFlag;
    /*
    */
    private String addLastDate;
    /*
    */
    private String acturallyIndusty;
    /*
    */
    private Integer operatorId;
    /*
    */
    private String txnDate;
    /*
    */
    private String logicCheckStatus;
    /*
    */
    private String riskCheckStatus;
    /*
    */
    private String creditCheckStatus;
    /*
    */
    private String auditStatus;
    /*
    */
    private String calcStatus;
    /*
    */
    private String accountStatus;
    /*
    */
    private String maturityStatus;
    /*
    */
    private String disaffirmStatus;
    /*
    */
    private String interestStatus;
    /*
    */
    private BigDecimal agentRate;
    /*
    */
    private String agentRateType;
    /*
    */
    private String profitAssignStatus;
    /*
    */
    private String misc;
    /*
    */
    private String appno;
    /*
    */
    private Integer lastUpdOperId;
    /*
    */
    private String lastUpdTime;
    /*
    */
    private String discountFlag;
    /*
    */
    private Integer resellContractId;
    /*
    */
    private String creditType;
    /*
    */
    private String mgnOptTime;
    /*
    */
    private String transStatus;
    /*
    * 预警表ID.
    */
    private String warnId;
    /*
    * 数据日期.
    */
    private String dataDt;

    public C05() {
    }

    public C05(int id) {
        this.id = id;
    }
    
	/**
    */	
    public int getId() {
        return this.id;
    }
	/**
    */	
    public void setId(int id) {
        this.id = id;
    }
	/**
    */	
    public Integer getBranchId() {
        return this.branchId;
    }
	/**
    */	
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }
	/**
    */	
    public Integer getAcctBranchId() {
        return this.acctBranchId;
    }
	/**
    */	
    public void setAcctBranchId(Integer acctBranchId) {
        this.acctBranchId = acctBranchId;
    }
	/**
    */	
    public String getTaskType() {
        return this.taskType;
    }
	/**
    */	
    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }
	/**
    */	
    public String getBuyType() {
        return this.buyType;
    }
	/**
    */	
    public void setBuyType(String buyType) {
        this.buyType = buyType;
    }
	/**
    */	
    public String getBuybizType() {
        return this.buybizType;
    }
	/**
    */	
    public void setBuybizType(String buybizType) {
        this.buybizType = buybizType;
    }
	/**
    */	
    public String getCentralBankflg() {
        return this.centralBankflg;
    }
	/**
    */	
    public void setCentralBankflg(String centralBankflg) {
        this.centralBankflg = centralBankflg;
    }
	/**
    */	
    public String getBuySigMk() {
        return this.buySigMk;
    }
	/**
    */	
    public void setBuySigMk(String buySigMk) {
        this.buySigMk = buySigMk;
    }
	/**
    */	
    public String getBusinessNo() {
        return this.businessNo;
    }
	/**
    */	
    public void setBusinessNo(String businessNo) {
        this.businessNo = businessNo;
    }
	/**
    */	
    public String getDraftType() {
        return this.draftType;
    }
	/**
    */	
    public void setDraftType(String draftType) {
        this.draftType = draftType;
    }
	/**
    */	
    public String getDraftAttr() {
        return this.draftAttr;
    }
	/**
    */	
    public void setDraftAttr(String draftAttr) {
        this.draftAttr = draftAttr;
    }
	/**
    */	
    public Integer getCustomerId() {
        return this.customerId;
    }
	/**
    */	
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
	/**
    */	
    public String getCustomerCustno() {
        return this.customerCustno;
    }
	/**
    */	
    public void setCustomerCustno(String customerCustno) {
        this.customerCustno = customerCustno;
    }
	/**
    */	
    public String getCustomerName() {
        return this.customerName;
    }
	/**
    */	
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
	/**
    */	
    public Integer getCustomerBankNo() {
        return this.customerBankNo;
    }
	/**
    */	
    public void setCustomerBankNo(Integer customerBankNo) {
        this.customerBankNo = customerBankNo;
    }
	/**
    */	
    public String getCustomerAccount() {
        return this.customerAccount;
    }
	/**
    */	
    public void setCustomerAccount(String customerAccount) {
        this.customerAccount = customerAccount;
    }
	/**
    */	
    public BigDecimal getRate() {
        return this.rate;
    }
	/**
    */	
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }
	/**
    */	
    public String getRateType() {
        return this.rateType;
    }
	/**
    */	
    public void setRateType(String rateType) {
        this.rateType = rateType;
    }
	/**
    */	
    public BigDecimal getRerate() {
        return this.rerate;
    }
	/**
    */	
    public void setRerate(BigDecimal rerate) {
        this.rerate = rerate;
    }
	/**
    */	
    public String getRerateType() {
        return this.rerateType;
    }
	/**
    */	
    public void setRerateType(String rerateType) {
        this.rerateType = rerateType;
    }
	/**
    */	
    public String getBuyDate() {
        return this.buyDate;
    }
	/**
    */	
    public void setBuyDate(String buyDate) {
        this.buyDate = buyDate;
    }
	/**
    */	
    public String getSttlmMk() {
        return this.sttlmMk;
    }
	/**
    */	
    public void setSttlmMk(String sttlmMk) {
        this.sttlmMk = sttlmMk;
    }
	/**
    */	
    public String getPostponeType() {
        return this.postponeType;
    }
	/**
    */	
    public void setPostponeType(String postponeType) {
        this.postponeType = postponeType;
    }
	/**
    */	
    public String getTwoWayDate() {
        return this.twoWayDate;
    }
	/**
    */	
    public void setTwoWayDate(String twoWayDate) {
        this.twoWayDate = twoWayDate;
    }
	/**
    */	
    public String getBuySellDate() {
        return this.buySellDate;
    }
	/**
    */	
    public void setBuySellDate(String buySellDate) {
        this.buySellDate = buySellDate;
    }
	/**
    */	
    public String getBuyBackBeginDate() {
        return this.buyBackBeginDate;
    }
	/**
    */	
    public void setBuyBackBeginDate(String buyBackBeginDate) {
        this.buyBackBeginDate = buyBackBeginDate;
    }
	/**
    */	
    public String getBuyBackEndDate() {
        return this.buyBackEndDate;
    }
	/**
    */	
    public void setBuyBackEndDate(String buyBackEndDate) {
        this.buyBackEndDate = buyBackEndDate;
    }
	/**
    */	
    public String getInnerFlag() {
        return this.innerFlag;
    }
	/**
    */	
    public void setInnerFlag(String innerFlag) {
        this.innerFlag = innerFlag;
    }
	/**
    */	
    public String getVirtualFlag() {
        return this.virtualFlag;
    }
	/**
    */	
    public void setVirtualFlag(String virtualFlag) {
        this.virtualFlag = virtualFlag;
    }
	/**
    */	
    public BigDecimal getRiskScale() {
        return this.riskScale;
    }
	/**
    */	
    public void setRiskScale(BigDecimal riskScale) {
        this.riskScale = riskScale;
    }
	/**
    */	
    public String getPayType() {
        return this.payType;
    }
	/**
    */	
    public void setPayType(String payType) {
        this.payType = payType;
    }
	/**
    */	
    public String getInnerCustFlag() {
        return this.innerCustFlag;
    }
	/**
    */	
    public void setInnerCustFlag(String innerCustFlag) {
        this.innerCustFlag = innerCustFlag;
    }
	/**
    */	
    public String getPayerName() {
        return this.payerName;
    }
	/**
    */	
    public void setPayerName(String payerName) {
        this.payerName = payerName;
    }
	/**
    */	
    public String getPayerBankName() {
        return this.payerBankName;
    }
	/**
    */	
    public void setPayerBankName(String payerBankName) {
        this.payerBankName = payerBankName;
    }
	/**
    */	
    public String getPayerAccount() {
        return this.payerAccount;
    }
	/**
    */	
    public void setPayerAccount(String payerAccount) {
        this.payerAccount = payerAccount;
    }
	/**
    */	
    public BigDecimal getPayerScale() {
        return this.payerScale;
    }
	/**
    */	
    public void setPayerScale(BigDecimal payerScale) {
        this.payerScale = payerScale;
    }
	/**
    */	
    public String getAgentName() {
        return this.agentName;
    }
	/**
    */	
    public void setAgentName(String agentName) {
        this.agentName = agentName;
    }
	/**
    */	
    public Integer getManagerId() {
        return this.managerId;
    }
	/**
    */	
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }
	/**
    */	
    public Integer getDepartId() {
        return this.departId;
    }
	/**
    */	
    public void setDepartId(Integer departId) {
        this.departId = departId;
    }
	/**
    */	
    public String getDiscountFirstFlag() {
        return this.discountFirstFlag;
    }
	/**
    */	
    public void setDiscountFirstFlag(String discountFirstFlag) {
        this.discountFirstFlag = discountFirstFlag;
    }
	/**
    */	
    public String getMendFlag() {
        return this.mendFlag;
    }
	/**
    */	
    public void setMendFlag(String mendFlag) {
        this.mendFlag = mendFlag;
    }
	/**
    */	
    public String getAddLastDate() {
        return this.addLastDate;
    }
	/**
    */	
    public void setAddLastDate(String addLastDate) {
        this.addLastDate = addLastDate;
    }
	/**
    */	
    public String getActurallyIndusty() {
        return this.acturallyIndusty;
    }
	/**
    */	
    public void setActurallyIndusty(String acturallyIndusty) {
        this.acturallyIndusty = acturallyIndusty;
    }
	/**
    */	
    public Integer getOperatorId() {
        return this.operatorId;
    }
	/**
    */	
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }
	/**
    */	
    public String getTxnDate() {
        return this.txnDate;
    }
	/**
    */	
    public void setTxnDate(String txnDate) {
        this.txnDate = txnDate;
    }
	/**
    */	
    public String getLogicCheckStatus() {
        return this.logicCheckStatus;
    }
	/**
    */	
    public void setLogicCheckStatus(String logicCheckStatus) {
        this.logicCheckStatus = logicCheckStatus;
    }
	/**
    */	
    public String getRiskCheckStatus() {
        return this.riskCheckStatus;
    }
	/**
    */	
    public void setRiskCheckStatus(String riskCheckStatus) {
        this.riskCheckStatus = riskCheckStatus;
    }
	/**
    */	
    public String getCreditCheckStatus() {
        return this.creditCheckStatus;
    }
	/**
    */	
    public void setCreditCheckStatus(String creditCheckStatus) {
        this.creditCheckStatus = creditCheckStatus;
    }
	/**
    */	
    public String getAuditStatus() {
        return this.auditStatus;
    }
	/**
    */	
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }
	/**
    */	
    public String getCalcStatus() {
        return this.calcStatus;
    }
	/**
    */	
    public void setCalcStatus(String calcStatus) {
        this.calcStatus = calcStatus;
    }
	/**
    */	
    public String getAccountStatus() {
        return this.accountStatus;
    }
	/**
    */	
    public void setAccountStatus(String accountStatus) {
        this.accountStatus = accountStatus;
    }
	/**
    */	
    public String getMaturityStatus() {
        return this.maturityStatus;
    }
	/**
    */	
    public void setMaturityStatus(String maturityStatus) {
        this.maturityStatus = maturityStatus;
    }
	/**
    */	
    public String getDisaffirmStatus() {
        return this.disaffirmStatus;
    }
	/**
    */	
    public void setDisaffirmStatus(String disaffirmStatus) {
        this.disaffirmStatus = disaffirmStatus;
    }
	/**
    */	
    public String getInterestStatus() {
        return this.interestStatus;
    }
	/**
    */	
    public void setInterestStatus(String interestStatus) {
        this.interestStatus = interestStatus;
    }
	/**
    */	
    public BigDecimal getAgentRate() {
        return this.agentRate;
    }
	/**
    */	
    public void setAgentRate(BigDecimal agentRate) {
        this.agentRate = agentRate;
    }
	/**
    */	
    public String getAgentRateType() {
        return this.agentRateType;
    }
	/**
    */	
    public void setAgentRateType(String agentRateType) {
        this.agentRateType = agentRateType;
    }
	/**
    */	
    public String getProfitAssignStatus() {
        return this.profitAssignStatus;
    }
	/**
    */	
    public void setProfitAssignStatus(String profitAssignStatus) {
        this.profitAssignStatus = profitAssignStatus;
    }
	/**
    */	
    public String getMisc() {
        return this.misc;
    }
	/**
    */	
    public void setMisc(String misc) {
        this.misc = misc;
    }
	/**
    */	
    public String getAppno() {
        return this.appno;
    }
	/**
    */	
    public void setAppno(String appno) {
        this.appno = appno;
    }
	/**
    */	
    public Integer getLastUpdOperId() {
        return this.lastUpdOperId;
    }
	/**
    */	
    public void setLastUpdOperId(Integer lastUpdOperId) {
        this.lastUpdOperId = lastUpdOperId;
    }
	/**
    */	
    public String getLastUpdTime() {
        return this.lastUpdTime;
    }
	/**
    */	
    public void setLastUpdTime(String lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }
	/**
    */	
    public String getDiscountFlag() {
        return this.discountFlag;
    }
	/**
    */	
    public void setDiscountFlag(String discountFlag) {
        this.discountFlag = discountFlag;
    }
	/**
    */	
    public Integer getResellContractId() {
        return this.resellContractId;
    }
	/**
    */	
    public void setResellContractId(Integer resellContractId) {
        this.resellContractId = resellContractId;
    }
	/**
    */	
    public String getCreditType() {
        return this.creditType;
    }
	/**
    */	
    public void setCreditType(String creditType) {
        this.creditType = creditType;
    }
	/**
    */	
    public String getMgnOptTime() {
        return this.mgnOptTime;
    }
	/**
    */	
    public void setMgnOptTime(String mgnOptTime) {
        this.mgnOptTime = mgnOptTime;
    }
	/**
    */	
    public String getTransStatus() {
        return this.transStatus;
    }
	/**
    */	
    public void setTransStatus(String transStatus) {
        this.transStatus = transStatus;
    }
	/**
    * Get the 预警表ID
    */	
    public String getWarnId() {
        return this.warnId;
    }
	/**
    * Set the 预警表ID
    */	
    public void setWarnId(String warnId) {
        this.warnId = warnId;
    }
	/**
    * Get the 数据日期
    */	
    public String getDataDt() {
        return this.dataDt;
    }
	/**
    * Set the 数据日期
    */	
    public void setDataDt(String dataDt) {
        this.dataDt = dataDt;
    }
}