package com.gbicc.company.single.outputentity;
// Generated 2016-1-12 19:22:04 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * TRewJ18CorporationId generated by hbm2java
 */
public class J18  implements java.io.Serializable {

	private static final long serialVersionUID = -410993031870358479L;
	
	/*
    */
    private String partyId;
    /*
    */
    private String customerNum;
    /*
    */
    private String customerTypeCd;
    /*
    */
    private String chineseName;
    /*
    */
    private String englishName;
    /*
    */
    private String chineseShortName;
    /*
    */
    private String englishShortName;
    /*
    */
    private String businessLicenseNum;
    /*
    */
    private String businessLicenseCheckDate;
    /*
    */
    private String orgnNum;
    /*
    */
    private String pbcIndustryCd;
    /*
    */
    private String loanCardNum;
    /*
    */
    private String corporativeCertification;
    /*
    */
    private String loanCardCheckDate;
    /*
    */
    private String nationalTaxRegistrationNum;
    /*
    */
    private String localTaxRegistrationCum;
    /*
    */
    private String ownershipTypeCd;
    /*
    */
    private String orgTypeCd;
    /*
    */
    private String foundedDate;
    /*
    */
    private String deadlineFinancialYear;
    /*
    */
    private String registerCapitalCurrencyCd;
    /*
    */
    private String launchCurrencyCd;
    /*
    */
    private BigDecimal registeredCapital;
    /*
    */
    private BigDecimal launchAmt;
    /*
    */
    private BigDecimal regCapitalReceivedRate;
    /*
    */
    private String supervisingDept;
    /*
    */
    private String customerRunStatusCd;
    /*
    */
    private String customerCreditPolicyCd;
    /*
    */
    private String financialIncomeSourceCd;
    /*
    */
    private String customerSizeCd;
    /*
    */
    private Integer staffNum;
    /*
    */
    private String listedCompanyInd;
    /*
    */
    private String groupCustomerInd;
    /*
    */
    private String basicAcctBank;
    /*
    */
    private String basicAcctNum;
    /*
    */
    private String openDate;
    /*
    */
    private String firstLoanDate;
    /*
    */
    private String ourBankNplRecord;
    /*
    */
    private String otherBankNplRecord;
    /*
    */
    private String cooperationBankInd;
    /*
    */
    private BigDecimal ourBankDepositRevenueSettl;
    /*
    */
    private String basicCustomerInd;
    /*
    */
    private String badAssetsPeeledCustomerInd;
    /*
    */
    private String badAssetsPeeledBank;
    /*
    */
    private String debtTransferStockCustInd;
    /*
    */
    private String ccbEstablishmentInd;
    /*
    */
    private String legalCorporateRepresentative;
    /*
    */
    private String transferedRWDeptInd;
    /*
    */
    private String creditCustomerInd;
    /*
    */
    private String customerMaintStatCd;
    /*
    */
    private String industryLevelOneCd;
    /*
    */
    private String industryLevelTwoCd;
    /*
    */
    private String lastMaintainDate;
    /*
    */
    private String maintainUserNum;
    /*
    */
    private String districtCd;
    /*
    */
    private String deptCd;
    /*
    */
    private String transferStatusCd;
    /*
    */
    private String industryDesc;
    /*
    */
    private String customerStatusCd;
    /*
    */
    private String crbCustomerSizeCd;
    /*
    */
    private String corpImpLevel;
    /*
    */
    private String myStockholderInd;
    /*
    */
    private String economyType;
    /*
    */
    private String corpNature;
    /*
    */
    private String profAssureCorp;
    /*
    */
    private String farmingIndustrySign;
    /*
    */
    private String imexManaInd;
    /*
    */
    private String loanRelationDate;
    /*
    */
    private String cooperateInd;
    /*
    */
    private String guaCustomerInd;
    /*
    */
    private String bpBusinessNum;
    /*
    */
    private String collectivityTypeCd;
    /*
    */
    private String bizLicExpirationDate;
    /*
    */
    private String loanCardPwd;
    /*
    */
    private String registeredTypeCd;
    /*
    */
    private String industryNum;
    /*
    */
    private String capitalLandCurrencyCd;
    /*
    */
    private String financeLicenceNum;
    /*
    */
    private BigDecimal mybankStockRate;
    /*
    */
    private String busCheckYear;
    /*
    */
    private String financingBuyInd;
    /*
    */
    private String newEvalResult;
    /*
    */
    private String holdingEnterpriseType;
    /*
    */
    private String corScientificInd;
    /*
    */
    private String corShutInd;
    /*
    */
    private String govFinanceFlat;
    /*
    */
    private String newCustomerInd;
    /*
    */
    private String smallLoanInd;
    /*
    */
    private String pawnLoanInd;
    /*
    */
    private String govFinanceType;
    /*
    */
    private String directorUnitInd;
    /*
    */
    private String cooperateType;
    /*
    */
    private String smallCorporationInd;
    /*
    */
    private String farmerMarktLinkInd;
    /*
    */
    private String joinSmesInd;
    /*
    */
    private String steelTradeInd;
    /*
    * 预警表ID.
    */
    private String warnId;
    /*
    * 数据日期.
    */
    private String dataDt;

    public J18() {
    }

	/**
    */	
    public String getPartyId() {
        return this.partyId;
    }
	/**
    */	
    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }
	/**
    */	
    public String getCustomerNum() {
        return this.customerNum;
    }
	/**
    */	
    public void setCustomerNum(String customerNum) {
        this.customerNum = customerNum;
    }
	/**
    */	
    public String getCustomerTypeCd() {
        return this.customerTypeCd;
    }
	/**
    */	
    public void setCustomerTypeCd(String customerTypeCd) {
        this.customerTypeCd = customerTypeCd;
    }
	/**
    */	
    public String getChineseName() {
        return this.chineseName;
    }
	/**
    */	
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }
	/**
    */	
    public String getEnglishName() {
        return this.englishName;
    }
	/**
    */	
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }
	/**
    */	
    public String getChineseShortName() {
        return this.chineseShortName;
    }
	/**
    */	
    public void setChineseShortName(String chineseShortName) {
        this.chineseShortName = chineseShortName;
    }
	/**
    */	
    public String getEnglishShortName() {
        return this.englishShortName;
    }
	/**
    */	
    public void setEnglishShortName(String englishShortName) {
        this.englishShortName = englishShortName;
    }
	/**
    */	
    public String getBusinessLicenseNum() {
        return this.businessLicenseNum;
    }
	/**
    */	
    public void setBusinessLicenseNum(String businessLicenseNum) {
        this.businessLicenseNum = businessLicenseNum;
    }
	/**
    */	
    public String getBusinessLicenseCheckDate() {
        return this.businessLicenseCheckDate;
    }
	/**
    */	
    public void setBusinessLicenseCheckDate(String businessLicenseCheckDate) {
        this.businessLicenseCheckDate = businessLicenseCheckDate;
    }
	/**
    */	
    public String getOrgnNum() {
        return this.orgnNum;
    }
	/**
    */	
    public void setOrgnNum(String orgnNum) {
        this.orgnNum = orgnNum;
    }
	/**
    */	
    public String getPbcIndustryCd() {
        return this.pbcIndustryCd;
    }
	/**
    */	
    public void setPbcIndustryCd(String pbcIndustryCd) {
        this.pbcIndustryCd = pbcIndustryCd;
    }
	/**
    */	
    public String getLoanCardNum() {
        return this.loanCardNum;
    }
	/**
    */	
    public void setLoanCardNum(String loanCardNum) {
        this.loanCardNum = loanCardNum;
    }
	/**
    */	
    public String getCorporativeCertification() {
        return this.corporativeCertification;
    }
	/**
    */	
    public void setCorporativeCertification(String corporativeCertification) {
        this.corporativeCertification = corporativeCertification;
    }
	/**
    */	
    public String getLoanCardCheckDate() {
        return this.loanCardCheckDate;
    }
	/**
    */	
    public void setLoanCardCheckDate(String loanCardCheckDate) {
        this.loanCardCheckDate = loanCardCheckDate;
    }
	/**
    */	
    public String getNationalTaxRegistrationNum() {
        return this.nationalTaxRegistrationNum;
    }
	/**
    */	
    public void setNationalTaxRegistrationNum(String nationalTaxRegistrationNum) {
        this.nationalTaxRegistrationNum = nationalTaxRegistrationNum;
    }
	/**
    */	
    public String getLocalTaxRegistrationCum() {
        return this.localTaxRegistrationCum;
    }
	/**
    */	
    public void setLocalTaxRegistrationCum(String localTaxRegistrationCum) {
        this.localTaxRegistrationCum = localTaxRegistrationCum;
    }
	/**
    */	
    public String getOwnershipTypeCd() {
        return this.ownershipTypeCd;
    }
	/**
    */	
    public void setOwnershipTypeCd(String ownershipTypeCd) {
        this.ownershipTypeCd = ownershipTypeCd;
    }
	/**
    */	
    public String getOrgTypeCd() {
        return this.orgTypeCd;
    }
	/**
    */	
    public void setOrgTypeCd(String orgTypeCd) {
        this.orgTypeCd = orgTypeCd;
    }
	/**
    */	
    public String getFoundedDate() {
        return this.foundedDate;
    }
	/**
    */	
    public void setFoundedDate(String foundedDate) {
        this.foundedDate = foundedDate;
    }
	/**
    */	
    public String getDeadlineFinancialYear() {
        return this.deadlineFinancialYear;
    }
	/**
    */	
    public void setDeadlineFinancialYear(String deadlineFinancialYear) {
        this.deadlineFinancialYear = deadlineFinancialYear;
    }
	/**
    */	
    public String getRegisterCapitalCurrencyCd() {
        return this.registerCapitalCurrencyCd;
    }
	/**
    */	
    public void setRegisterCapitalCurrencyCd(String registerCapitalCurrencyCd) {
        this.registerCapitalCurrencyCd = registerCapitalCurrencyCd;
    }
	/**
    */	
    public String getLaunchCurrencyCd() {
        return this.launchCurrencyCd;
    }
	/**
    */	
    public void setLaunchCurrencyCd(String launchCurrencyCd) {
        this.launchCurrencyCd = launchCurrencyCd;
    }
	/**
    */	
    public BigDecimal getRegisteredCapital() {
        return this.registeredCapital;
    }
	/**
    */	
    public void setRegisteredCapital(BigDecimal registeredCapital) {
        this.registeredCapital = registeredCapital;
    }
	/**
    */	
    public BigDecimal getLaunchAmt() {
        return this.launchAmt;
    }
	/**
    */	
    public void setLaunchAmt(BigDecimal launchAmt) {
        this.launchAmt = launchAmt;
    }
	/**
    */	
    public BigDecimal getRegCapitalReceivedRate() {
        return this.regCapitalReceivedRate;
    }
	/**
    */	
    public void setRegCapitalReceivedRate(BigDecimal regCapitalReceivedRate) {
        this.regCapitalReceivedRate = regCapitalReceivedRate;
    }
	/**
    */	
    public String getSupervisingDept() {
        return this.supervisingDept;
    }
	/**
    */	
    public void setSupervisingDept(String supervisingDept) {
        this.supervisingDept = supervisingDept;
    }
	/**
    */	
    public String getCustomerRunStatusCd() {
        return this.customerRunStatusCd;
    }
	/**
    */	
    public void setCustomerRunStatusCd(String customerRunStatusCd) {
        this.customerRunStatusCd = customerRunStatusCd;
    }
	/**
    */	
    public String getCustomerCreditPolicyCd() {
        return this.customerCreditPolicyCd;
    }
	/**
    */	
    public void setCustomerCreditPolicyCd(String customerCreditPolicyCd) {
        this.customerCreditPolicyCd = customerCreditPolicyCd;
    }
	/**
    */	
    public String getFinancialIncomeSourceCd() {
        return this.financialIncomeSourceCd;
    }
	/**
    */	
    public void setFinancialIncomeSourceCd(String financialIncomeSourceCd) {
        this.financialIncomeSourceCd = financialIncomeSourceCd;
    }
	/**
    */	
    public String getCustomerSizeCd() {
        return this.customerSizeCd;
    }
	/**
    */	
    public void setCustomerSizeCd(String customerSizeCd) {
        this.customerSizeCd = customerSizeCd;
    }
	/**
    */	
    public Integer getStaffNum() {
        return this.staffNum;
    }
	/**
    */	
    public void setStaffNum(Integer staffNum) {
        this.staffNum = staffNum;
    }
	/**
    */	
    public String getListedCompanyInd() {
        return this.listedCompanyInd;
    }
	/**
    */	
    public void setListedCompanyInd(String listedCompanyInd) {
        this.listedCompanyInd = listedCompanyInd;
    }
	/**
    */	
    public String getGroupCustomerInd() {
        return this.groupCustomerInd;
    }
	/**
    */	
    public void setGroupCustomerInd(String groupCustomerInd) {
        this.groupCustomerInd = groupCustomerInd;
    }
	/**
    */	
    public String getBasicAcctBank() {
        return this.basicAcctBank;
    }
	/**
    */	
    public void setBasicAcctBank(String basicAcctBank) {
        this.basicAcctBank = basicAcctBank;
    }
	/**
    */	
    public String getBasicAcctNum() {
        return this.basicAcctNum;
    }
	/**
    */	
    public void setBasicAcctNum(String basicAcctNum) {
        this.basicAcctNum = basicAcctNum;
    }
	/**
    */	
    public String getOpenDate() {
        return this.openDate;
    }
	/**
    */	
    public void setOpenDate(String openDate) {
        this.openDate = openDate;
    }
	/**
    */	
    public String getFirstLoanDate() {
        return this.firstLoanDate;
    }
	/**
    */	
    public void setFirstLoanDate(String firstLoanDate) {
        this.firstLoanDate = firstLoanDate;
    }
	/**
    */	
    public String getOurBankNplRecord() {
        return this.ourBankNplRecord;
    }
	/**
    */	
    public void setOurBankNplRecord(String ourBankNplRecord) {
        this.ourBankNplRecord = ourBankNplRecord;
    }
	/**
    */	
    public String getOtherBankNplRecord() {
        return this.otherBankNplRecord;
    }
	/**
    */	
    public void setOtherBankNplRecord(String otherBankNplRecord) {
        this.otherBankNplRecord = otherBankNplRecord;
    }
	/**
    */	
    public String getCooperationBankInd() {
        return this.cooperationBankInd;
    }
	/**
    */	
    public void setCooperationBankInd(String cooperationBankInd) {
        this.cooperationBankInd = cooperationBankInd;
    }
	/**
    */	
    public BigDecimal getOurBankDepositRevenueSettl() {
        return this.ourBankDepositRevenueSettl;
    }
	/**
    */	
    public void setOurBankDepositRevenueSettl(BigDecimal ourBankDepositRevenueSettl) {
        this.ourBankDepositRevenueSettl = ourBankDepositRevenueSettl;
    }
	/**
    */	
    public String getBasicCustomerInd() {
        return this.basicCustomerInd;
    }
	/**
    */	
    public void setBasicCustomerInd(String basicCustomerInd) {
        this.basicCustomerInd = basicCustomerInd;
    }
	/**
    */	
    public String getBadAssetsPeeledCustomerInd() {
        return this.badAssetsPeeledCustomerInd;
    }
	/**
    */	
    public void setBadAssetsPeeledCustomerInd(String badAssetsPeeledCustomerInd) {
        this.badAssetsPeeledCustomerInd = badAssetsPeeledCustomerInd;
    }
	/**
    */	
    public String getBadAssetsPeeledBank() {
        return this.badAssetsPeeledBank;
    }
	/**
    */	
    public void setBadAssetsPeeledBank(String badAssetsPeeledBank) {
        this.badAssetsPeeledBank = badAssetsPeeledBank;
    }
	/**
    */	
    public String getDebtTransferStockCustInd() {
        return this.debtTransferStockCustInd;
    }
	/**
    */	
    public void setDebtTransferStockCustInd(String debtTransferStockCustInd) {
        this.debtTransferStockCustInd = debtTransferStockCustInd;
    }
	/**
    */	
    public String getCcbEstablishmentInd() {
        return this.ccbEstablishmentInd;
    }
	/**
    */	
    public void setCcbEstablishmentInd(String ccbEstablishmentInd) {
        this.ccbEstablishmentInd = ccbEstablishmentInd;
    }
	/**
    */	
    public String getLegalCorporateRepresentative() {
        return this.legalCorporateRepresentative;
    }
	/**
    */	
    public void setLegalCorporateRepresentative(String legalCorporateRepresentative) {
        this.legalCorporateRepresentative = legalCorporateRepresentative;
    }
	/**
    */	
    public String getTransferedRWDeptInd() {
        return this.transferedRWDeptInd;
    }
	/**
    */	
    public void setTransferedRWDeptInd(String transferedRWDeptInd) {
        this.transferedRWDeptInd = transferedRWDeptInd;
    }
	/**
    */	
    public String getCreditCustomerInd() {
        return this.creditCustomerInd;
    }
	/**
    */	
    public void setCreditCustomerInd(String creditCustomerInd) {
        this.creditCustomerInd = creditCustomerInd;
    }
	/**
    */	
    public String getCustomerMaintStatCd() {
        return this.customerMaintStatCd;
    }
	/**
    */	
    public void setCustomerMaintStatCd(String customerMaintStatCd) {
        this.customerMaintStatCd = customerMaintStatCd;
    }
	/**
    */	
    public String getIndustryLevelOneCd() {
        return this.industryLevelOneCd;
    }
	/**
    */	
    public void setIndustryLevelOneCd(String industryLevelOneCd) {
        this.industryLevelOneCd = industryLevelOneCd;
    }
	/**
    */	
    public String getIndustryLevelTwoCd() {
        return this.industryLevelTwoCd;
    }
	/**
    */	
    public void setIndustryLevelTwoCd(String industryLevelTwoCd) {
        this.industryLevelTwoCd = industryLevelTwoCd;
    }
	/**
    */	
    public String getLastMaintainDate() {
        return this.lastMaintainDate;
    }
	/**
    */	
    public void setLastMaintainDate(String lastMaintainDate) {
        this.lastMaintainDate = lastMaintainDate;
    }
	/**
    */	
    public String getMaintainUserNum() {
        return this.maintainUserNum;
    }
	/**
    */	
    public void setMaintainUserNum(String maintainUserNum) {
        this.maintainUserNum = maintainUserNum;
    }
	/**
    */	
    public String getDistrictCd() {
        return this.districtCd;
    }
	/**
    */	
    public void setDistrictCd(String districtCd) {
        this.districtCd = districtCd;
    }
	/**
    */	
    public String getDeptCd() {
        return this.deptCd;
    }
	/**
    */	
    public void setDeptCd(String deptCd) {
        this.deptCd = deptCd;
    }
	/**
    */	
    public String getTransferStatusCd() {
        return this.transferStatusCd;
    }
	/**
    */	
    public void setTransferStatusCd(String transferStatusCd) {
        this.transferStatusCd = transferStatusCd;
    }
	/**
    */	
    public String getIndustryDesc() {
        return this.industryDesc;
    }
	/**
    */	
    public void setIndustryDesc(String industryDesc) {
        this.industryDesc = industryDesc;
    }
	/**
    */	
    public String getCustomerStatusCd() {
        return this.customerStatusCd;
    }
	/**
    */	
    public void setCustomerStatusCd(String customerStatusCd) {
        this.customerStatusCd = customerStatusCd;
    }
	/**
    */	
    public String getCrbCustomerSizeCd() {
        return this.crbCustomerSizeCd;
    }
	/**
    */	
    public void setCrbCustomerSizeCd(String crbCustomerSizeCd) {
        this.crbCustomerSizeCd = crbCustomerSizeCd;
    }
	/**
    */	
    public String getCorpImpLevel() {
        return this.corpImpLevel;
    }
	/**
    */	
    public void setCorpImpLevel(String corpImpLevel) {
        this.corpImpLevel = corpImpLevel;
    }
	/**
    */	
    public String getMyStockholderInd() {
        return this.myStockholderInd;
    }
	/**
    */	
    public void setMyStockholderInd(String myStockholderInd) {
        this.myStockholderInd = myStockholderInd;
    }
	/**
    */	
    public String getEconomyType() {
        return this.economyType;
    }
	/**
    */	
    public void setEconomyType(String economyType) {
        this.economyType = economyType;
    }
	/**
    */	
    public String getCorpNature() {
        return this.corpNature;
    }
	/**
    */	
    public void setCorpNature(String corpNature) {
        this.corpNature = corpNature;
    }
	/**
    */	
    public String getProfAssureCorp() {
        return this.profAssureCorp;
    }
	/**
    */	
    public void setProfAssureCorp(String profAssureCorp) {
        this.profAssureCorp = profAssureCorp;
    }
	/**
    */	
    public String getFarmingIndustrySign() {
        return this.farmingIndustrySign;
    }
	/**
    */	
    public void setFarmingIndustrySign(String farmingIndustrySign) {
        this.farmingIndustrySign = farmingIndustrySign;
    }
	/**
    */	
    public String getImexManaInd() {
        return this.imexManaInd;
    }
	/**
    */	
    public void setImexManaInd(String imexManaInd) {
        this.imexManaInd = imexManaInd;
    }
	/**
    */	
    public String getLoanRelationDate() {
        return this.loanRelationDate;
    }
	/**
    */	
    public void setLoanRelationDate(String loanRelationDate) {
        this.loanRelationDate = loanRelationDate;
    }
	/**
    */	
    public String getCooperateInd() {
        return this.cooperateInd;
    }
	/**
    */	
    public void setCooperateInd(String cooperateInd) {
        this.cooperateInd = cooperateInd;
    }
	/**
    */	
    public String getGuaCustomerInd() {
        return this.guaCustomerInd;
    }
	/**
    */	
    public void setGuaCustomerInd(String guaCustomerInd) {
        this.guaCustomerInd = guaCustomerInd;
    }
	/**
    */	
    public String getBpBusinessNum() {
        return this.bpBusinessNum;
    }
	/**
    */	
    public void setBpBusinessNum(String bpBusinessNum) {
        this.bpBusinessNum = bpBusinessNum;
    }
	/**
    */	
    public String getCollectivityTypeCd() {
        return this.collectivityTypeCd;
    }
	/**
    */	
    public void setCollectivityTypeCd(String collectivityTypeCd) {
        this.collectivityTypeCd = collectivityTypeCd;
    }
	/**
    */	
    public String getBizLicExpirationDate() {
        return this.bizLicExpirationDate;
    }
	/**
    */	
    public void setBizLicExpirationDate(String bizLicExpirationDate) {
        this.bizLicExpirationDate = bizLicExpirationDate;
    }
	/**
    */	
    public String getLoanCardPwd() {
        return this.loanCardPwd;
    }
	/**
    */	
    public void setLoanCardPwd(String loanCardPwd) {
        this.loanCardPwd = loanCardPwd;
    }
	/**
    */	
    public String getRegisteredTypeCd() {
        return this.registeredTypeCd;
    }
	/**
    */	
    public void setRegisteredTypeCd(String registeredTypeCd) {
        this.registeredTypeCd = registeredTypeCd;
    }
	/**
    */	
    public String getIndustryNum() {
        return this.industryNum;
    }
	/**
    */	
    public void setIndustryNum(String industryNum) {
        this.industryNum = industryNum;
    }
	/**
    */	
    public String getCapitalLandCurrencyCd() {
        return this.capitalLandCurrencyCd;
    }
	/**
    */	
    public void setCapitalLandCurrencyCd(String capitalLandCurrencyCd) {
        this.capitalLandCurrencyCd = capitalLandCurrencyCd;
    }
	/**
    */	
    public String getFinanceLicenceNum() {
        return this.financeLicenceNum;
    }
	/**
    */	
    public void setFinanceLicenceNum(String financeLicenceNum) {
        this.financeLicenceNum = financeLicenceNum;
    }
	/**
    */	
    public BigDecimal getMybankStockRate() {
        return this.mybankStockRate;
    }
	/**
    */	
    public void setMybankStockRate(BigDecimal mybankStockRate) {
        this.mybankStockRate = mybankStockRate;
    }
	/**
    */	
    public String getBusCheckYear() {
        return this.busCheckYear;
    }
	/**
    */	
    public void setBusCheckYear(String busCheckYear) {
        this.busCheckYear = busCheckYear;
    }
	/**
    */	
    public String getFinancingBuyInd() {
        return this.financingBuyInd;
    }
	/**
    */	
    public void setFinancingBuyInd(String financingBuyInd) {
        this.financingBuyInd = financingBuyInd;
    }
	/**
    */	
    public String getNewEvalResult() {
        return this.newEvalResult;
    }
	/**
    */	
    public void setNewEvalResult(String newEvalResult) {
        this.newEvalResult = newEvalResult;
    }
	/**
    */	
    public String getHoldingEnterpriseType() {
        return this.holdingEnterpriseType;
    }
	/**
    */	
    public void setHoldingEnterpriseType(String holdingEnterpriseType) {
        this.holdingEnterpriseType = holdingEnterpriseType;
    }
	/**
    */	
    public String getCorScientificInd() {
        return this.corScientificInd;
    }
	/**
    */	
    public void setCorScientificInd(String corScientificInd) {
        this.corScientificInd = corScientificInd;
    }
	/**
    */	
    public String getCorShutInd() {
        return this.corShutInd;
    }
	/**
    */	
    public void setCorShutInd(String corShutInd) {
        this.corShutInd = corShutInd;
    }
	/**
    */	
    public String getGovFinanceFlat() {
        return this.govFinanceFlat;
    }
	/**
    */	
    public void setGovFinanceFlat(String govFinanceFlat) {
        this.govFinanceFlat = govFinanceFlat;
    }
	/**
    */	
    public String getNewCustomerInd() {
        return this.newCustomerInd;
    }
	/**
    */	
    public void setNewCustomerInd(String newCustomerInd) {
        this.newCustomerInd = newCustomerInd;
    }
	/**
    */	
    public String getSmallLoanInd() {
        return this.smallLoanInd;
    }
	/**
    */	
    public void setSmallLoanInd(String smallLoanInd) {
        this.smallLoanInd = smallLoanInd;
    }
	/**
    */	
    public String getPawnLoanInd() {
        return this.pawnLoanInd;
    }
	/**
    */	
    public void setPawnLoanInd(String pawnLoanInd) {
        this.pawnLoanInd = pawnLoanInd;
    }
	/**
    */	
    public String getGovFinanceType() {
        return this.govFinanceType;
    }
	/**
    */	
    public void setGovFinanceType(String govFinanceType) {
        this.govFinanceType = govFinanceType;
    }
	/**
    */	
    public String getDirectorUnitInd() {
        return this.directorUnitInd;
    }
	/**
    */	
    public void setDirectorUnitInd(String directorUnitInd) {
        this.directorUnitInd = directorUnitInd;
    }
	/**
    */	
    public String getCooperateType() {
        return this.cooperateType;
    }
	/**
    */	
    public void setCooperateType(String cooperateType) {
        this.cooperateType = cooperateType;
    }
	/**
    */	
    public String getSmallCorporationInd() {
        return this.smallCorporationInd;
    }
	/**
    */	
    public void setSmallCorporationInd(String smallCorporationInd) {
        this.smallCorporationInd = smallCorporationInd;
    }
	/**
    */	
    public String getFarmerMarktLinkInd() {
        return this.farmerMarktLinkInd;
    }
	/**
    */	
    public void setFarmerMarktLinkInd(String farmerMarktLinkInd) {
        this.farmerMarktLinkInd = farmerMarktLinkInd;
    }
	/**
    */	
    public String getJoinSmesInd() {
        return this.joinSmesInd;
    }
	/**
    */	
    public void setJoinSmesInd(String joinSmesInd) {
        this.joinSmesInd = joinSmesInd;
    }
	/**
    */	
    public String getSteelTradeInd() {
        return this.steelTradeInd;
    }
	/**
    */	
    public void setSteelTradeInd(String steelTradeInd) {
        this.steelTradeInd = steelTradeInd;
    }
	/**
    * Get the 预警表ID
    */	
    public String getWarnId() {
        return this.warnId;
    }
	/**
    * Set the 预警表ID
    */	
    public void setWarnId(String warnId) {
        this.warnId = warnId;
    }
	/**
    * Get the 数据日期
    */	
    public String getDataDt() {
        return this.dataDt;
    }
	/**
    * Set the 数据日期
    */	
    public void setDataDt(String dataDt) {
        this.dataDt = dataDt;
    }
}