package com.gbicc.company.single.outputentity;
// Generated 2016-1-15 16:51:03 by Hibernate Tools 3.2.2.GA



/**
 * TRewL04CouNoticeDetailId generated by hbm2java
 */
public class L04  implements java.io.Serializable {

	private static final long serialVersionUID = -2206994069392794241L;
	
	/*
    * ID.
    */
    private String id;
    /*
    * 法院名称.
    */
    private String courtName;
    /*
    * 法庭名称.
    */
    private String court2Name;
    /*
    * 开庭日期.
    */
    private String tryDate;
    /*
    * 案号.
    */
    private String caseNo;
    /*
    * 案由.
    */
    private String caseReason;
    /*
    * 承办部门.
    */
    private String mainDept;
    /*
    * 审判长/主审人.
    */
    private String tryName;
    /*
    * 原告/上诉人.
    */
    private String accuser;
    /*
    * 被告/被上诉人.
    */
    private String defendant;
    /*
    * 关联基本信息主键.
    */
    private String baseId;
    /*
    * 原链接.
    */
    private String sourceLink;
    /*
    * 关联ID.
    */
    private String relaId;
    /*
    * 数据日期.
    */
    private String rowDate;
    /*
    * 预警表ID.
    */
    private String warnId;
    /*
    * 数据日期.
    */
    private String dataDt;

    public L04() {
    }

	/**
    * Get the ID
    */	
    public String getId() {
        return this.id;
    }
	/**
    * Set the ID
    */	
    public void setId(String id) {
        this.id = id;
    }
	/**
    * Get the 法院名称
    */	
    public String getCourtName() {
        return this.courtName;
    }
	/**
    * Set the 法院名称
    */	
    public void setCourtName(String courtName) {
        this.courtName = courtName;
    }
	/**
    * Get the 法庭名称
    */	
    public String getCourt2Name() {
        return this.court2Name;
    }
	/**
    * Set the 法庭名称
    */	
    public void setCourt2Name(String court2Name) {
        this.court2Name = court2Name;
    }
	/**
    * Get the 开庭日期
    */	
    public String getTryDate() {
        return this.tryDate;
    }
	/**
    * Set the 开庭日期
    */	
    public void setTryDate(String tryDate) {
        this.tryDate = tryDate;
    }
	/**
    * Get the 案号
    */	
    public String getCaseNo() {
        return this.caseNo;
    }
	/**
    * Set the 案号
    */	
    public void setCaseNo(String caseNo) {
        this.caseNo = caseNo;
    }
	/**
    * Get the 案由
    */	
    public String getCaseReason() {
        return this.caseReason;
    }
	/**
    * Set the 案由
    */	
    public void setCaseReason(String caseReason) {
        this.caseReason = caseReason;
    }
	/**
    * Get the 承办部门
    */	
    public String getMainDept() {
        return this.mainDept;
    }
	/**
    * Set the 承办部门
    */	
    public void setMainDept(String mainDept) {
        this.mainDept = mainDept;
    }
	/**
    * Get the 审判长/主审人
    */	
    public String getTryName() {
        return this.tryName;
    }
	/**
    * Set the 审判长/主审人
    */	
    public void setTryName(String tryName) {
        this.tryName = tryName;
    }
	/**
    * Get the 原告/上诉人
    */	
    public String getAccuser() {
        return this.accuser;
    }
	/**
    * Set the 原告/上诉人
    */	
    public void setAccuser(String accuser) {
        this.accuser = accuser;
    }
	/**
    * Get the 被告/被上诉人
    */	
    public String getDefendant() {
        return this.defendant;
    }
	/**
    * Set the 被告/被上诉人
    */	
    public void setDefendant(String defendant) {
        this.defendant = defendant;
    }
	/**
    * Get the 关联基本信息主键
    */	
    public String getBaseId() {
        return this.baseId;
    }
	/**
    * Set the 关联基本信息主键
    */	
    public void setBaseId(String baseId) {
        this.baseId = baseId;
    }
	/**
    * Get the 原链接
    */	
    public String getSourceLink() {
        return this.sourceLink;
    }
	/**
    * Set the 原链接
    */	
    public void setSourceLink(String sourceLink) {
        this.sourceLink = sourceLink;
    }
	/**
    * Get the 关联ID
    */	
    public String getRelaId() {
        return this.relaId;
    }
	/**
    * Set the 关联ID
    */	
    public void setRelaId(String relaId) {
        this.relaId = relaId;
    }
	/**
    * Get the 数据日期
    */	
    public String getRowDate() {
        return this.rowDate;
    }
	/**
    * Set the 数据日期
    */	
    public void setRowDate(String rowDate) {
        this.rowDate = rowDate;
    }
	/**
    * Get the 预警表ID
    */	
    public String getWarnId() {
        return this.warnId;
    }
	/**
    * Set the 预警表ID
    */	
    public void setWarnId(String warnId) {
        this.warnId = warnId;
    }
	/**
    * Get the 数据日期
    */	
    public String getDataDt() {
        return this.dataDt;
    }
	/**
    * Set the 数据日期
    */	
    public void setDataDt(String dataDt) {
        this.dataDt = dataDt;
    }
}