package com.gbicc.company.single.outputentity;
// Generated 2016-1-15 16:51:03 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * TRewL12PersonCreditIndexId generated by hbm2java
 */
public class L12  implements java.io.Serializable {

	private static final long serialVersionUID = 5315259268573494993L;
	
	/*
    * 唯一标识.
    */
    private String fdId;
    /*
    * 过去24个月内贷款的最差还款状态.
    */
    private Integer fd24monMaxloanOverstatus;
    /*
    * 历史贷款最高逾期期数.
    */
    private Integer fdMaxloanOvernum;
    /*
    * 历史贷款累计逾期次数.
    */
    private Integer fdSumloanOvercount;
    /*
    * 卡帐户状态.
    */
    private Integer fdCreditCardStatus;
    /*
    * 过去24个月内信用卡的最差还款状态.
    */
    private Integer fd24monMaxcreditOverstatus;
    /*
    * 过去12个月信用卡未还最低还款额的次数.
    */
    private Integer fd12monMaxcreditOvernum;
    /*
    * 透支额度.
    */
    private BigDecimal fdCreditcardOverdraftAmt;
    /*
    * 历史准贷记卡累计逾期次数.
    */
    private Integer fdMaxscreditcardOvernum;
    /*
    * 历史贷记卡累计逾期次数.
    */
    private Integer fdMaxcreditcardOvernum;
    /*
    * 历史准贷记卡最大逾期期数.
    */
    private Integer fdMaxscreditcardOversum;
    /*
    * 历史贷记卡最大逾期期数.
    */
    private Integer fdMaxcreditcardOversum;
    /*
    * 历史非经营性贷款最大当前逾期期数.
    */
    private Integer fdMaxlfjyloanOversum;
    /*
    * 历史个人经营性贷款最大当前逾期期数.
    */
    private Integer fdMaxjyloanOversum;
    /*
    * 负债总额.
    */
    private BigDecimal fdFzamtsum;
    /*
    * 征信报告日期.
    */
    private String fdReportdate;
    /*
    * 报告编号.
    */
    private String fdReportid;
    /*
    * 是否有征信记录.
    */
    private String fdHascredit;
    /*
    * 数据日期.
    */
    private String fdRowdate;
    /*
    * 最差贷款状态-其它机构.
    */
    private Integer fdMaxloanstate;
    /*
    * 征信等级.
    */
    private Integer fdCreditlevel;
    /*
    * 客户名称.
    */
    private String fdCustname;
    /*
    * 客户证件号码.
    */
    private String fdCreditcard;
    /*
    * 客户证件号码类型.
    */
    private String fdCreditcardtype;
    /*
    * 1有效0无效.
    */
    private String fdValid;
    /*
    * 最近3年贷款存在不良贷款（逾期）.
    */
    private Integer fd3monBadLoanoverState;
    /*
    * 最近3年贷款是否存在五级分类后三类贷款【次级、不良、损失】.
    */
    private Integer fd3yearBadLoanState;
    /*
    * 预警表ID.
    */
    private String fdWarnId;
    /*
    * 数据日期.
    */
    private String fdDataDt;

    public L12() {
    }

	public String getFdId() {
		return fdId;
	}

	public void setFdId(String fdId) {
		this.fdId = fdId;
	}

	public Integer getFd24monMaxloanOverstatus() {
		return fd24monMaxloanOverstatus;
	}

	public void setFd24monMaxloanOverstatus(Integer fd24monMaxloanOverstatus) {
		this.fd24monMaxloanOverstatus = fd24monMaxloanOverstatus;
	}

	public Integer getFdMaxloanOvernum() {
		return fdMaxloanOvernum;
	}

	public void setFdMaxloanOvernum(Integer fdMaxloanOvernum) {
		this.fdMaxloanOvernum = fdMaxloanOvernum;
	}

	public Integer getFdSumloanOvercount() {
		return fdSumloanOvercount;
	}

	public void setFdSumloanOvercount(Integer fdSumloanOvercount) {
		this.fdSumloanOvercount = fdSumloanOvercount;
	}

	public Integer getFdCreditCardStatus() {
		return fdCreditCardStatus;
	}

	public void setFdCreditCardStatus(Integer fdCreditCardStatus) {
		this.fdCreditCardStatus = fdCreditCardStatus;
	}

	public Integer getFd24monMaxcreditOverstatus() {
		return fd24monMaxcreditOverstatus;
	}

	public void setFd24monMaxcreditOverstatus(Integer fd24monMaxcreditOverstatus) {
		this.fd24monMaxcreditOverstatus = fd24monMaxcreditOverstatus;
	}

	public Integer getFd12monMaxcreditOvernum() {
		return fd12monMaxcreditOvernum;
	}

	public void setFd12monMaxcreditOvernum(Integer fd12monMaxcreditOvernum) {
		this.fd12monMaxcreditOvernum = fd12monMaxcreditOvernum;
	}

	public BigDecimal getFdCreditcardOverdraftAmt() {
		return fdCreditcardOverdraftAmt;
	}

	public void setFdCreditcardOverdraftAmt(BigDecimal fdCreditcardOverdraftAmt) {
		this.fdCreditcardOverdraftAmt = fdCreditcardOverdraftAmt;
	}

	public Integer getFdMaxscreditcardOvernum() {
		return fdMaxscreditcardOvernum;
	}

	public void setFdMaxscreditcardOvernum(Integer fdMaxscreditcardOvernum) {
		this.fdMaxscreditcardOvernum = fdMaxscreditcardOvernum;
	}

	public Integer getFdMaxcreditcardOvernum() {
		return fdMaxcreditcardOvernum;
	}

	public void setFdMaxcreditcardOvernum(Integer fdMaxcreditcardOvernum) {
		this.fdMaxcreditcardOvernum = fdMaxcreditcardOvernum;
	}

	public Integer getFdMaxscreditcardOversum() {
		return fdMaxscreditcardOversum;
	}

	public void setFdMaxscreditcardOversum(Integer fdMaxscreditcardOversum) {
		this.fdMaxscreditcardOversum = fdMaxscreditcardOversum;
	}

	public Integer getFdMaxcreditcardOversum() {
		return fdMaxcreditcardOversum;
	}

	public void setFdMaxcreditcardOversum(Integer fdMaxcreditcardOversum) {
		this.fdMaxcreditcardOversum = fdMaxcreditcardOversum;
	}

	public Integer getFdMaxlfjyloanOversum() {
		return fdMaxlfjyloanOversum;
	}

	public void setFdMaxlfjyloanOversum(Integer fdMaxlfjyloanOversum) {
		this.fdMaxlfjyloanOversum = fdMaxlfjyloanOversum;
	}

	public Integer getFdMaxjyloanOversum() {
		return fdMaxjyloanOversum;
	}

	public void setFdMaxjyloanOversum(Integer fdMaxjyloanOversum) {
		this.fdMaxjyloanOversum = fdMaxjyloanOversum;
	}

	public BigDecimal getFdFzamtsum() {
		return fdFzamtsum;
	}

	public void setFdFzamtsum(BigDecimal fdFzamtsum) {
		this.fdFzamtsum = fdFzamtsum;
	}

	public String getFdReportdate() {
		return fdReportdate;
	}

	public void setFdReportdate(String fdReportdate) {
		this.fdReportdate = fdReportdate;
	}

	public String getFdReportid() {
		return fdReportid;
	}

	public void setFdReportid(String fdReportid) {
		this.fdReportid = fdReportid;
	}

	public String getFdHascredit() {
		return fdHascredit;
	}

	public void setFdHascredit(String fdHascredit) {
		this.fdHascredit = fdHascredit;
	}

	public String getFdRowdate() {
		return fdRowdate;
	}

	public void setFdRowdate(String fdRowdate) {
		this.fdRowdate = fdRowdate;
	}

	public Integer getFdMaxloanstate() {
		return fdMaxloanstate;
	}

	public void setFdMaxloanstate(Integer fdMaxloanstate) {
		this.fdMaxloanstate = fdMaxloanstate;
	}

	public Integer getFdCreditlevel() {
		return fdCreditlevel;
	}

	public void setFdCreditlevel(Integer fdCreditlevel) {
		this.fdCreditlevel = fdCreditlevel;
	}

	public String getFdCustname() {
		return fdCustname;
	}

	public void setFdCustname(String fdCustname) {
		this.fdCustname = fdCustname;
	}

	public String getFdCreditcard() {
		return fdCreditcard;
	}

	public void setFdCreditcard(String fdCreditcard) {
		this.fdCreditcard = fdCreditcard;
	}

	public String getFdCreditcardtype() {
		return fdCreditcardtype;
	}

	public void setFdCreditcardtype(String fdCreditcardtype) {
		this.fdCreditcardtype = fdCreditcardtype;
	}

	public String getFdValid() {
		return fdValid;
	}

	public void setFdValid(String fdValid) {
		this.fdValid = fdValid;
	}

	public Integer getFd3monBadLoanoverState() {
		return fd3monBadLoanoverState;
	}

	public void setFd3monBadLoanoverState(Integer fd3monBadLoanoverState) {
		this.fd3monBadLoanoverState = fd3monBadLoanoverState;
	}

	public Integer getFd3yearBadLoanState() {
		return fd3yearBadLoanState;
	}

	public void setFd3yearBadLoanState(Integer fd3yearBadLoanState) {
		this.fd3yearBadLoanState = fd3yearBadLoanState;
	}

	public String getFdWarnId() {
		return fdWarnId;
	}

	public void setFdWarnId(String fdWarnId) {
		this.fdWarnId = fdWarnId;
	}

	public String getFdDataDt() {
		return fdDataDt;
	}

	public void setFdDataDt(String fdDataDt) {
		this.fdDataDt = fdDataDt;
	}
}