package com.gbicc.company.single.outputentity;
// Generated 2016-7-14 12:51:32 by Hibernate Tools 3.2.2.GA



/**
 * TRewL16CompanyCreditLoaninfoId generated by hbm2java
 */
public class L16  implements java.io.Serializable {

	private static final long serialVersionUID = 8016520480805635959L;
	
	/*
    */
    private String fdId;
    /*
    */
    private String fdFinancecode;
    /*
    */
    private String fdContractcode;
    /*
    */
    private String fdLoankindcode;
    /*
    */
    private String fdCurrency;
    /*
    */
    private String fdDuebillsum;
    /*
    */
    private String fdDuebilltakeoutdate;
    /*
    */
    private String fdDuebillterminatedate;
    /*
    */
    private String fdSettlementdate;
    /*
    */
    private String fdRepaytype;
    /*
    */
    private String fdFiveclasscode;
    /*
    */
    private String fdIndexId;
    /*
    */
    private String fdIsbad;
    /*
    */
    private String fdWarnId;

    public L16() {
    }

	public String getFdId() {
		return fdId;
	}

	public void setFdId(String fdId) {
		this.fdId = fdId;
	}

	public String getFdFinancecode() {
		return fdFinancecode;
	}

	public void setFdFinancecode(String fdFinancecode) {
		this.fdFinancecode = fdFinancecode;
	}

	public String getFdContractcode() {
		return fdContractcode;
	}

	public void setFdContractcode(String fdContractcode) {
		this.fdContractcode = fdContractcode;
	}

	public String getFdLoankindcode() {
		return fdLoankindcode;
	}

	public void setFdLoankindcode(String fdLoankindcode) {
		this.fdLoankindcode = fdLoankindcode;
	}

	public String getFdCurrency() {
		return fdCurrency;
	}

	public void setFdCurrency(String fdCurrency) {
		this.fdCurrency = fdCurrency;
	}

	public String getFdDuebillsum() {
		return fdDuebillsum;
	}

	public void setFdDuebillsum(String fdDuebillsum) {
		this.fdDuebillsum = fdDuebillsum;
	}

	public String getFdDuebilltakeoutdate() {
		return fdDuebilltakeoutdate;
	}

	public void setFdDuebilltakeoutdate(String fdDuebilltakeoutdate) {
		this.fdDuebilltakeoutdate = fdDuebilltakeoutdate;
	}

	public String getFdDuebillterminatedate() {
		return fdDuebillterminatedate;
	}

	public void setFdDuebillterminatedate(String fdDuebillterminatedate) {
		this.fdDuebillterminatedate = fdDuebillterminatedate;
	}

	public String getFdSettlementdate() {
		return fdSettlementdate;
	}

	public void setFdSettlementdate(String fdSettlementdate) {
		this.fdSettlementdate = fdSettlementdate;
	}

	public String getFdRepaytype() {
		return fdRepaytype;
	}

	public void setFdRepaytype(String fdRepaytype) {
		this.fdRepaytype = fdRepaytype;
	}

	public String getFdFiveclasscode() {
		return fdFiveclasscode;
	}

	public void setFdFiveclasscode(String fdFiveclasscode) {
		this.fdFiveclasscode = fdFiveclasscode;
	}

	public String getFdIndexId() {
		return fdIndexId;
	}

	public void setFdIndexId(String fdIndexId) {
		this.fdIndexId = fdIndexId;
	}

	public String getFdIsbad() {
		return fdIsbad;
	}

	public void setFdIsbad(String fdIsbad) {
		this.fdIsbad = fdIsbad;
	}

	public String getFdWarnId() {
		return fdWarnId;
	}

	public void setFdWarnId(String fdWarnId) {
		this.fdWarnId = fdWarnId;
	}
}