package com.gbicc.company.view.entity;
// Generated 2016-1-18 16:47:43 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * TCmCustomerId generated by hbm2java
 */
public class TCmCustomer_v  implements java.io.Serializable {


    /*
    * 参与人ID.
    */
    private String partyId;
    /*
    * 客户编号.
    */
    private String customerNum;
    /*
    * 客户类型代码.
    */
    private String customerTypeCd;
    /*
    * 中文名称.
    */
    private String chineseName;
    /*
    * 英文名称.
    */
    private String englishName;
    /*
    * 中文简称.
    */
    private String chineseShortName;
    /*
    * 客户所属机构.
    */
    private String deptCd;
    /*
    * 客户经理.
    */
    private String customerManager;
    /*
    * 贷款金额.
    */
    private Double loanAmount;
    /*
    * 贷款余额.
    */
    private Double loanBalance;
    /*
    * 客户预警等级.
    */
    private String custWarnLevel;
    /*
    * 是否黑名单.
    */
    private String isBlackName;
    /*
    * 客户卡号.
    */
    private String loanCardNum;

    
    private String orgnNum;
    
    private String industryCd;

    private String warnYlevel;
    
	public String getPartyId() {
		return partyId;
	}
	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}
	public String getCustomerNum() {
		return customerNum;
	}
	public void setCustomerNum(String customerNum) {
		this.customerNum = customerNum;
	}
	public String getCustomerTypeCd() {
		return customerTypeCd;
	}
	public void setCustomerTypeCd(String customerTypeCd) {
		this.customerTypeCd = customerTypeCd;
	}
	public String getChineseName() {
		return chineseName;
	}
	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}
	public String getEnglishName() {
		return englishName;
	}
	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}
	public String getChineseShortName() {
		return chineseShortName;
	}
	public void setChineseShortName(String chineseShortName) {
		this.chineseShortName = chineseShortName;
	}
	public String getCustomerManager() {
		return customerManager;
	}
	public void setCustomerManager(String customerManager) {
		this.customerManager = customerManager;
	}
	public Double getLoanAmount() {
		return loanAmount;
	}
	public void setLoanAmount(Double loanAmount) {
		this.loanAmount = loanAmount;
	}
	public Double getLoanBalance() {
		return loanBalance;
	}
	public void setLoanBalance(Double loanBalance) {
		this.loanBalance = loanBalance;
	}
	public String getCustWarnLevel() {
		return custWarnLevel;
	}
	public void setCustWarnLevel(String custWarnLevel) {
		this.custWarnLevel = custWarnLevel;
	}
	public String getIsBlackName() {
		return isBlackName;
	}
	public void setIsBlackName(String isBlackName) {
		this.isBlackName = isBlackName;
	}
	public String getDeptCd() {
		return deptCd;
	}
	public void setDeptCd(String deptCd) {
		this.deptCd = deptCd;
	}
	public String getOrgnNum() {
		return orgnNum;
	}
	public void setOrgnNum(String orgnNum) {
		this.orgnNum = orgnNum;
	}
	public String getLoanCardNum() {
		return loanCardNum;
	}
	public void setLoanCardNum(String loanCardNum) {
		this.loanCardNum = loanCardNum;
	}
	public String getIndustryCd() {
		return industryCd;
	}
	public void setIndustryCd(String industryCd) {
		this.industryCd = industryCd;
	}
	public String getWarnYlevel() {
		return warnYlevel;
	}
	public void setWarnYlevel(String warnYlevel) {
		this.warnYlevel = warnYlevel;
	}

   

}


