package com.gbicc.person.creditMemo.entity;
// Generated 2015-11-20 11:33:25 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * TPlCreditMemo generated by hbm2java
 */
public class TPlCreditMemo  implements java.io.Serializable {


    /**
	 * 
	 */
	private static final long serialVersionUID = 4953860130748610790L;
	/*
    * 编号.
    */
    private String id;
    /*
    * 发起日期.
    */
    private Date startDate;
    /*
    * 客户编号.
    */
    private String custcode;
    /*
    * 客户名称.
    */
    private String custname;
    /*
    * 贷款账号.
    */
    private String loanAccount;
    /*
    * 报警编号.
    */
    private String reprotCode;
    /*
    * 发起原因.
    */
    private String startRemark;
    /*
    * 控制措施.
    */
    private String controlmeasure;
    /*
    * 操作人.
    */
    private String operator;
    /*
    * 操作行.
    */
    private String operBank;
    /*
    * 发起类型.
    */
    private String startType;
    /*
    * 业务ID.
    */
    private String businessId;

    public TPlCreditMemo() {
    }

	
    public TPlCreditMemo(String id) {
        this.id = id;
    }
    public TPlCreditMemo(String id, Date startDate, String custcode, String custname, String loanAccount, String reprotCode, String startRemark, String controlmeasure, String operator, String operBank, String startType, String businessId) {
       this.id = id;
       this.startDate = startDate;
       this.custcode = custcode;
       this.custname = custname;
       this.loanAccount = loanAccount;
       this.reprotCode = reprotCode;
       this.startRemark = startRemark;
       this.controlmeasure = controlmeasure;
       this.operator = operator;
       this.operBank = operBank;
       this.startType = startType;
       this.businessId = businessId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public String getCustcode() {
        return this.custcode;
    }
    
    public void setCustcode(String custcode) {
        this.custcode = custcode;
    }
    public String getCustname() {
        return this.custname;
    }
    
    public void setCustname(String custname) {
        this.custname = custname;
    }
    public String getLoanAccount() {
        return this.loanAccount;
    }
    
    public void setLoanAccount(String loanAccount) {
        this.loanAccount = loanAccount;
    }
    public String getReprotCode() {
        return this.reprotCode;
    }
    
    public void setReprotCode(String reprotCode) {
        this.reprotCode = reprotCode;
    }
    public String getStartRemark() {
        return this.startRemark;
    }
    
    public void setStartRemark(String startRemark) {
        this.startRemark = startRemark;
    }
    public String getControlmeasure() {
        return this.controlmeasure;
    }
    
    public void setControlmeasure(String controlmeasure) {
        this.controlmeasure = controlmeasure;
    }
    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }
    public String getOperBank() {
        return this.operBank;
    }
    
    public void setOperBank(String operBank) {
        this.operBank = operBank;
    }
    public String getStartType() {
        return this.startType;
    }
    
    public void setStartType(String startType) {
        this.startType = startType;
    }
    public String getBusinessId() {
        return this.businessId;
    }
    
    public void setBusinessId(String businessId) {
        this.businessId = businessId;
    }




}


