package com.gbicc.bpm.entity;
// Generated 2015-12-8 14:45:49 by Hibernate Tools 3.2.2.GA



/**
 * TLoanAccountRelDuty generated by hbm2java
 */
public class TLoanAccountRelDuty  implements java.io.Serializable {

	private static final long serialVersionUID = 4093724035164452583L;
	
	/*
    * 账户ID.
    */
    private String loanacno;
    /*
    * 责任人ID.
    */
    private String dutyid;
    /*
    * 责任人姓名.
    */
    private String dutyname;
    /*
     * 责任人机构.
     */
    private String dutyorg;
    /*
     * 催收人ID.
     */
     private String collid;
     /*
     * 催收人姓名.
     */
     private String collname;
     /**
      * 催收人机构
      */
     private String collorg;

    public TLoanAccountRelDuty() {
    }

    public String getLoanacno() {
        return this.loanacno;
    }
    public void setLoanacno(String loanacno) {
        this.loanacno = loanacno;
    }
    
    public String getDutyid() {
        return this.dutyid;
    }
    public void setDutyid(String dutyid) {
        this.dutyid = dutyid;
    }
    
    public String getDutyname() {
        return this.dutyname;
    }
    public void setDutyname(String dutyname) {
        this.dutyname = dutyname;
    }

	public String getCollid() {
		return collid;
	}
	public void setCollid(String collid) {
		this.collid = collid;
	}

	public String getCollname() {
		return collname;
	}
	public void setCollname(String collname) {
		this.collname = collname;
	}

	public String getDutyorg() {
		return dutyorg;
	}

	public void setDutyorg(String dutyorg) {
		this.dutyorg = dutyorg;
	}

	public String getCollorg() {
		return collorg;
	}

	public void setCollorg(String collorg) {
		this.collorg = collorg;
	}
}