package com.gbicc.company.view.entity;

import java.io.Serializable;
import java.math.BigDecimal;
// Generated 2015-11-30 17:00:32 by Hibernate Tools 3.2.2.GA



/**
 * TbConContract generated by hbm2java
 */
public class TbConContract implements Serializable {
	private static final long serialVersionUID = 1L;
	private String adjustInd;
	private String affordableHouseType;
	private String agriForeAnimFishLoanType;
	private String approveNum;
	private BigDecimal assureAddAmt;
	private BigDecimal assureAddAmtMod;
	private String assureEndDate;
	private String bankTeamRole;
	private String bizId;
	private String bizNum;
	private String classificationResult;
	private String comprBizContractInd;
	private String contractChangeInd;
	private String contractCycleInd;
	private String contractId;
	private String contractLoanCd;
	private String contractManualNum;
	private String contractNatureCd;
	private String contractNum;
	private String contractOtherCondition;
	private String contractProvidePurpose;
	private String contractSignDate;
	private String contractSignPlace;
	private String contractStatusCd;
	private String contractSupplement;
	private Integer contractTerm;
	private String contractTerminationDate;
	private String contractTerminationWayCd;
	private BigDecimal contractTotalAmt;
	private String contractTypeCd;
	private String creditLimitId;
	private String creditLimitNum;
	private String creditProductCd;
	private String currencyCd;
	private String customerNum;
	private String debtReformTypeCd;
	private String disbOrgCd;
	private BigDecimal exchangeRate;
	private String expirationDate;
	private BigDecimal exportAmt;
	private String exportCurrencyCd;
	private String exportPresentNum;
	private String extendField;
	private String extendFlagField;
	private String firstPayStartTerm;
	private String focusIndustryCd;
	private String forfaitingType;
	private String freeTradeInd;
	private String freezenInd;
	private String gdTemp1;
	private String gdTemp2;
	private String govCreditType;
	private String guarantyNote;
	private BigDecimal guarantyRate;
	private String guarantyType;
	private String handlingOrgCd;
	private String handlingUserNum;
	private String ifCorpHoustLoan;
	private String industryLevelTwoCd;
	private String lastMaIntegerainDate;
	private String lcNum;
	private String loanLendSourceType;
	private String loanTypeInstructionCd;
	private String lowRiskBizTypeCd;
	private String lowRiskInd;
	private String mainSuertySubchild;
	private String mainSuretyMode;
	private String noteCustomerNum;
	private String oldBizDetailId;
	private String oldContractDetailId;
	private String originalContractExpDate;
	private String originalContractManualNum;
	private String originalGuarantyContractNum;
	private String otherBankSuertyMode;
	private String otherBankSuertySubchild;
	private BigDecimal ourbankBuyAmt;
	private String partyId;
	private BigDecimal payDiscountAmt;
	private String paymentBank;
	private String payoutApproveLevel;
	private String payoutInd;
	private String peasantLoanType;
	private String postPonementTypeCd;
	private String postponementInd;
	private String prerequisitionComment;
	private BigDecimal promisesAmt;
	private String promisesAmtCollectionType;
	private String realtyLoanType;
	private String realtyLoanTypeInd;
	private String reformLoanInd;
	private String relaBizNum;
	private Integer remitPSum;
	private String reportSuertyMode;
	private String reportSuertySubchild;
	private String representModalityInd;
	private String restrictIndustryInd;
	private Integer shortOperationMatureTerm;
	private String startDate;
	private String suertyCd;
	private String superContractNum;
	private String termEndDate;
	private Integer tipFinancingAmtTerm;
	private String topFinancingEndDate;
	private String topFinancingStartDate;
	private String topGuarantyInd;
	private String transferedToWrInd;
	private Integer widthTerm;
	private String wrOrgCd;
	private String yhCurrencyCd;
	private String lastMaintainDate;

	public TbConContract() {
	}

	public String getAdjustInd() {
		return adjustInd;
	}

	public void setAdjustInd(String adjustInd) {
		this.adjustInd = adjustInd;
	}

	public String getAffordableHouseType() {
		return affordableHouseType;
	}

	public void setAffordableHouseType(String affordableHouseType) {
		this.affordableHouseType = affordableHouseType;
	}

	public String getAgriForeAnimFishLoanType() {
		return agriForeAnimFishLoanType;
	}

	public void setAgriForeAnimFishLoanType(String agriForeAnimFishLoanType) {
		this.agriForeAnimFishLoanType = agriForeAnimFishLoanType;
	}

	public String getApproveNum() {
		return approveNum;
	}

	public void setApproveNum(String approveNum) {
		this.approveNum = approveNum;
	}

	public BigDecimal getAssureAddAmt() {
		return assureAddAmt;
	}

	public void setAssureAddAmt(BigDecimal assureAddAmt) {
		this.assureAddAmt = assureAddAmt;
	}

	public BigDecimal getAssureAddAmtMod() {
		return assureAddAmtMod;
	}

	public void setAssureAddAmtMod(BigDecimal assureAddAmtMod) {
		this.assureAddAmtMod = assureAddAmtMod;
	}

	public String getAssureEndDate() {
		return assureEndDate;
	}

	public void setAssureEndDate(String assureEndDate) {
		this.assureEndDate = assureEndDate;
	}

	public String getBankTeamRole() {
		return bankTeamRole;
	}

	public void setBankTeamRole(String bankTeamRole) {
		this.bankTeamRole = bankTeamRole;
	}

	public String getBizId() {
		return bizId;
	}

	public void setBizId(String bizId) {
		this.bizId = bizId;
	}

	public String getBizNum() {
		return bizNum;
	}

	public void setBizNum(String bizNum) {
		this.bizNum = bizNum;
	}

	public String getClassificationResult() {
		return classificationResult;
	}

	public void setClassificationResult(String classificationResult) {
		this.classificationResult = classificationResult;
	}

	public String getComprBizContractInd() {
		return comprBizContractInd;
	}

	public void setComprBizContractInd(String comprBizContractInd) {
		this.comprBizContractInd = comprBizContractInd;
	}

	public String getContractChangeInd() {
		return contractChangeInd;
	}

	public void setContractChangeInd(String contractChangeInd) {
		this.contractChangeInd = contractChangeInd;
	}

	public String getContractCycleInd() {
		return contractCycleInd;
	}

	public void setContractCycleInd(String contractCycleInd) {
		this.contractCycleInd = contractCycleInd;
	}

	public String getContractId() {
		return contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	public String getContractLoanCd() {
		return contractLoanCd;
	}

	public void setContractLoanCd(String contractLoanCd) {
		this.contractLoanCd = contractLoanCd;
	}

	public String getContractManualNum() {
		return contractManualNum;
	}

	public void setContractManualNum(String contractManualNum) {
		this.contractManualNum = contractManualNum;
	}

	public String getContractNatureCd() {
		return contractNatureCd;
	}

	public void setContractNatureCd(String contractNatureCd) {
		this.contractNatureCd = contractNatureCd;
	}

	public String getContractNum() {
		return contractNum;
	}

	public void setContractNum(String contractNum) {
		this.contractNum = contractNum;
	}

	public String getContractOtherCondition() {
		return contractOtherCondition;
	}

	public void setContractOtherCondition(String contractOtherCondition) {
		this.contractOtherCondition = contractOtherCondition;
	}

	public String getContractProvidePurpose() {
		return contractProvidePurpose;
	}

	public void setContractProvidePurpose(String contractProvidePurpose) {
		this.contractProvidePurpose = contractProvidePurpose;
	}

	public String getContractSignDate() {
		return contractSignDate;
	}

	public void setContractSignDate(String contractSignDate) {
		this.contractSignDate = contractSignDate;
	}

	public String getContractSignPlace() {
		return contractSignPlace;
	}

	public void setContractSignPlace(String contractSignPlace) {
		this.contractSignPlace = contractSignPlace;
	}

	public String getContractStatusCd() {
		return contractStatusCd;
	}

	public void setContractStatusCd(String contractStatusCd) {
		this.contractStatusCd = contractStatusCd;
	}

	public String getContractSupplement() {
		return contractSupplement;
	}

	public void setContractSupplement(String contractSupplement) {
		this.contractSupplement = contractSupplement;
	}

	public Integer getContractTerm() {
		return contractTerm;
	}

	public void setContractTerm(Integer contractTerm) {
		this.contractTerm = contractTerm;
	}

	public String getContractTerminationDate() {
		return contractTerminationDate;
	}

	public void setContractTerminationDate(String contractTerminationDate) {
		this.contractTerminationDate = contractTerminationDate;
	}

	public String getContractTerminationWayCd() {
		return contractTerminationWayCd;
	}

	public void setContractTerminationWayCd(String contractTerminationWayCd) {
		this.contractTerminationWayCd = contractTerminationWayCd;
	}

	public BigDecimal getContractTotalAmt() {
		return contractTotalAmt;
	}

	public void setContractTotalAmt(BigDecimal contractTotalAmt) {
		this.contractTotalAmt = contractTotalAmt;
	}

	public String getContractTypeCd() {
		return contractTypeCd;
	}

	public void setContractTypeCd(String contractTypeCd) {
		this.contractTypeCd = contractTypeCd;
	}

	public String getCreditLimitId() {
		return creditLimitId;
	}

	public void setCreditLimitId(String creditLimitId) {
		this.creditLimitId = creditLimitId;
	}

	public String getCreditLimitNum() {
		return creditLimitNum;
	}

	public void setCreditLimitNum(String creditLimitNum) {
		this.creditLimitNum = creditLimitNum;
	}

	public String getCreditProductCd() {
		return creditProductCd;
	}

	public void setCreditProductCd(String creditProductCd) {
		this.creditProductCd = creditProductCd;
	}

	public String getCurrencyCd() {
		return currencyCd;
	}

	public void setCurrencyCd(String currencyCd) {
		this.currencyCd = currencyCd;
	}

	public String getCustomerNum() {
		return customerNum;
	}

	public void setCustomerNum(String customerNum) {
		this.customerNum = customerNum;
	}

	public String getDebtReformTypeCd() {
		return debtReformTypeCd;
	}

	public void setDebtReformTypeCd(String debtReformTypeCd) {
		this.debtReformTypeCd = debtReformTypeCd;
	}

	public String getDisbOrgCd() {
		return disbOrgCd;
	}

	public void setDisbOrgCd(String disbOrgCd) {
		this.disbOrgCd = disbOrgCd;
	}

	public BigDecimal getExchangeRate() {
		return exchangeRate;
	}

	public void setExchangeRate(BigDecimal exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	public String getExpirationDate() {
		return expirationDate;
	}

	public void setExpirationDate(String expirationDate) {
		this.expirationDate = expirationDate;
	}

	public BigDecimal getExportAmt() {
		return exportAmt;
	}

	public void setExportAmt(BigDecimal exportAmt) {
		this.exportAmt = exportAmt;
	}

	public String getExportCurrencyCd() {
		return exportCurrencyCd;
	}

	public void setExportCurrencyCd(String exportCurrencyCd) {
		this.exportCurrencyCd = exportCurrencyCd;
	}

	public String getExportPresentNum() {
		return exportPresentNum;
	}

	public void setExportPresentNum(String exportPresentNum) {
		this.exportPresentNum = exportPresentNum;
	}

	public String getExtendField() {
		return extendField;
	}

	public void setExtendField(String extendField) {
		this.extendField = extendField;
	}

	public String getExtendFlagField() {
		return extendFlagField;
	}

	public void setExtendFlagField(String extendFlagField) {
		this.extendFlagField = extendFlagField;
	}

	public String getFirstPayStartTerm() {
		return firstPayStartTerm;
	}

	public void setFirstPayStartTerm(String firstPayStartTerm) {
		this.firstPayStartTerm = firstPayStartTerm;
	}

	public String getFocusIndustryCd() {
		return focusIndustryCd;
	}

	public void setFocusIndustryCd(String focusIndustryCd) {
		this.focusIndustryCd = focusIndustryCd;
	}

	public String getForfaitingType() {
		return forfaitingType;
	}

	public void setForfaitingType(String forfaitingType) {
		this.forfaitingType = forfaitingType;
	}

	public String getFreeTradeInd() {
		return freeTradeInd;
	}

	public void setFreeTradeInd(String freeTradeInd) {
		this.freeTradeInd = freeTradeInd;
	}

	public String getFreezenInd() {
		return freezenInd;
	}

	public void setFreezenInd(String freezenInd) {
		this.freezenInd = freezenInd;
	}

	public String getGdTemp1() {
		return gdTemp1;
	}

	public void setGdTemp1(String gdTemp1) {
		this.gdTemp1 = gdTemp1;
	}

	public String getGdTemp2() {
		return gdTemp2;
	}

	public void setGdTemp2(String gdTemp2) {
		this.gdTemp2 = gdTemp2;
	}

	public String getGovCreditType() {
		return govCreditType;
	}

	public void setGovCreditType(String govCreditType) {
		this.govCreditType = govCreditType;
	}

	public String getGuarantyNote() {
		return guarantyNote;
	}

	public void setGuarantyNote(String guarantyNote) {
		this.guarantyNote = guarantyNote;
	}

	public BigDecimal getGuarantyRate() {
		return guarantyRate;
	}

	public void setGuarantyRate(BigDecimal guarantyRate) {
		this.guarantyRate = guarantyRate;
	}

	public String getGuarantyType() {
		return guarantyType;
	}

	public void setGuarantyType(String guarantyType) {
		this.guarantyType = guarantyType;
	}

	public String getHandlingOrgCd() {
		return handlingOrgCd;
	}

	public void setHandlingOrgCd(String handlingOrgCd) {
		this.handlingOrgCd = handlingOrgCd;
	}

	public String getHandlingUserNum() {
		return handlingUserNum;
	}

	public void setHandlingUserNum(String handlingUserNum) {
		this.handlingUserNum = handlingUserNum;
	}

	public String getIfCorpHoustLoan() {
		return ifCorpHoustLoan;
	}

	public void setIfCorpHoustLoan(String ifCorpHoustLoan) {
		this.ifCorpHoustLoan = ifCorpHoustLoan;
	}

	public String getIndustryLevelTwoCd() {
		return industryLevelTwoCd;
	}

	public void setIndustryLevelTwoCd(String industryLevelTwoCd) {
		this.industryLevelTwoCd = industryLevelTwoCd;
	}

	public String getLastMaIntegerainDate() {
		return lastMaIntegerainDate;
	}

	public void setLastMaIntegerainDate(String lastMaIntegerainDate) {
		this.lastMaIntegerainDate = lastMaIntegerainDate;
	}

	public String getLcNum() {
		return lcNum;
	}

	public void setLcNum(String lcNum) {
		this.lcNum = lcNum;
	}

	public String getLoanLendSourceType() {
		return loanLendSourceType;
	}

	public void setLoanLendSourceType(String loanLendSourceType) {
		this.loanLendSourceType = loanLendSourceType;
	}

	public String getLoanTypeInstructionCd() {
		return loanTypeInstructionCd;
	}

	public void setLoanTypeInstructionCd(String loanTypeInstructionCd) {
		this.loanTypeInstructionCd = loanTypeInstructionCd;
	}

	public String getLowRiskBizTypeCd() {
		return lowRiskBizTypeCd;
	}

	public void setLowRiskBizTypeCd(String lowRiskBizTypeCd) {
		this.lowRiskBizTypeCd = lowRiskBizTypeCd;
	}

	public String getLowRiskInd() {
		return lowRiskInd;
	}

	public void setLowRiskInd(String lowRiskInd) {
		this.lowRiskInd = lowRiskInd;
	}

	public String getMainSuertySubchild() {
		return mainSuertySubchild;
	}

	public void setMainSuertySubchild(String mainSuertySubchild) {
		this.mainSuertySubchild = mainSuertySubchild;
	}

	public String getMainSuretyMode() {
		return mainSuretyMode;
	}

	public void setMainSuretyMode(String mainSuretyMode) {
		this.mainSuretyMode = mainSuretyMode;
	}

	public String getNoteCustomerNum() {
		return noteCustomerNum;
	}

	public void setNoteCustomerNum(String noteCustomerNum) {
		this.noteCustomerNum = noteCustomerNum;
	}

	public String getOldBizDetailId() {
		return oldBizDetailId;
	}

	public void setOldBizDetailId(String oldBizDetailId) {
		this.oldBizDetailId = oldBizDetailId;
	}

	public String getOldContractDetailId() {
		return oldContractDetailId;
	}

	public void setOldContractDetailId(String oldContractDetailId) {
		this.oldContractDetailId = oldContractDetailId;
	}

	public String getOriginalContractExpDate() {
		return originalContractExpDate;
	}

	public void setOriginalContractExpDate(String originalContractExpDate) {
		this.originalContractExpDate = originalContractExpDate;
	}

	public String getOriginalContractManualNum() {
		return originalContractManualNum;
	}

	public void setOriginalContractManualNum(String originalContractManualNum) {
		this.originalContractManualNum = originalContractManualNum;
	}

	public String getOriginalGuarantyContractNum() {
		return originalGuarantyContractNum;
	}

	public void setOriginalGuarantyContractNum(String originalGuarantyContractNum) {
		this.originalGuarantyContractNum = originalGuarantyContractNum;
	}

	public String getOtherBankSuertyMode() {
		return otherBankSuertyMode;
	}

	public void setOtherBankSuertyMode(String otherBankSuertyMode) {
		this.otherBankSuertyMode = otherBankSuertyMode;
	}

	public String getOtherBankSuertySubchild() {
		return otherBankSuertySubchild;
	}

	public void setOtherBankSuertySubchild(String otherBankSuertySubchild) {
		this.otherBankSuertySubchild = otherBankSuertySubchild;
	}

	public BigDecimal getOurbankBuyAmt() {
		return ourbankBuyAmt;
	}

	public void setOurbankBuyAmt(BigDecimal ourbankBuyAmt) {
		this.ourbankBuyAmt = ourbankBuyAmt;
	}

	public String getPartyId() {
		return partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public BigDecimal getPayDiscountAmt() {
		return payDiscountAmt;
	}

	public void setPayDiscountAmt(BigDecimal payDiscountAmt) {
		this.payDiscountAmt = payDiscountAmt;
	}

	public String getPaymentBank() {
		return paymentBank;
	}

	public void setPaymentBank(String paymentBank) {
		this.paymentBank = paymentBank;
	}

	public String getPayoutApproveLevel() {
		return payoutApproveLevel;
	}

	public void setPayoutApproveLevel(String payoutApproveLevel) {
		this.payoutApproveLevel = payoutApproveLevel;
	}

	public String getPayoutInd() {
		return payoutInd;
	}

	public void setPayoutInd(String payoutInd) {
		this.payoutInd = payoutInd;
	}

	public String getPeasantLoanType() {
		return peasantLoanType;
	}

	public void setPeasantLoanType(String peasantLoanType) {
		this.peasantLoanType = peasantLoanType;
	}

	public String getPostPonementTypeCd() {
		return postPonementTypeCd;
	}

	public void setPostPonementTypeCd(String postPonementTypeCd) {
		this.postPonementTypeCd = postPonementTypeCd;
	}

	public String getPostponementInd() {
		return postponementInd;
	}

	public void setPostponementInd(String postponementInd) {
		this.postponementInd = postponementInd;
	}

	public String getPrerequisitionComment() {
		return prerequisitionComment;
	}

	public void setPrerequisitionComment(String prerequisitionComment) {
		this.prerequisitionComment = prerequisitionComment;
	}

	public BigDecimal getPromisesAmt() {
		return promisesAmt;
	}

	public void setPromisesAmt(BigDecimal promisesAmt) {
		this.promisesAmt = promisesAmt;
	}

	public String getPromisesAmtCollectionType() {
		return promisesAmtCollectionType;
	}

	public void setPromisesAmtCollectionType(String promisesAmtCollectionType) {
		this.promisesAmtCollectionType = promisesAmtCollectionType;
	}

	public String getRealtyLoanType() {
		return realtyLoanType;
	}

	public void setRealtyLoanType(String realtyLoanType) {
		this.realtyLoanType = realtyLoanType;
	}

	public String getRealtyLoanTypeInd() {
		return realtyLoanTypeInd;
	}

	public void setRealtyLoanTypeInd(String realtyLoanTypeInd) {
		this.realtyLoanTypeInd = realtyLoanTypeInd;
	}

	public String getReformLoanInd() {
		return reformLoanInd;
	}

	public void setReformLoanInd(String reformLoanInd) {
		this.reformLoanInd = reformLoanInd;
	}

	public String getRelaBizNum() {
		return relaBizNum;
	}

	public void setRelaBizNum(String relaBizNum) {
		this.relaBizNum = relaBizNum;
	}

	public Integer getRemitPSum() {
		return remitPSum;
	}

	public void setRemitPSum(Integer remitPSum) {
		this.remitPSum = remitPSum;
	}

	public String getReportSuertyMode() {
		return reportSuertyMode;
	}

	public void setReportSuertyMode(String reportSuertyMode) {
		this.reportSuertyMode = reportSuertyMode;
	}

	public String getReportSuertySubchild() {
		return reportSuertySubchild;
	}

	public void setReportSuertySubchild(String reportSuertySubchild) {
		this.reportSuertySubchild = reportSuertySubchild;
	}

	public String getRepresentModalityInd() {
		return representModalityInd;
	}

	public void setRepresentModalityInd(String representModalityInd) {
		this.representModalityInd = representModalityInd;
	}

	public String getRestrictIndustryInd() {
		return restrictIndustryInd;
	}

	public void setRestrictIndustryInd(String restrictIndustryInd) {
		this.restrictIndustryInd = restrictIndustryInd;
	}

	public Integer getShortOperationMatureTerm() {
		return shortOperationMatureTerm;
	}

	public void setShortOperationMatureTerm(Integer shortOperationMatureTerm) {
		this.shortOperationMatureTerm = shortOperationMatureTerm;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getSuertyCd() {
		return suertyCd;
	}

	public void setSuertyCd(String suertyCd) {
		this.suertyCd = suertyCd;
	}

	public String getSuperContractNum() {
		return superContractNum;
	}

	public void setSuperContractNum(String superContractNum) {
		this.superContractNum = superContractNum;
	}

	public String getTermEndDate() {
		return termEndDate;
	}

	public void setTermEndDate(String termEndDate) {
		this.termEndDate = termEndDate;
	}

	public Integer getTipFinancingAmtTerm() {
		return tipFinancingAmtTerm;
	}

	public void setTipFinancingAmtTerm(Integer tipFinancingAmtTerm) {
		this.tipFinancingAmtTerm = tipFinancingAmtTerm;
	}

	public String getTopFinancingEndDate() {
		return topFinancingEndDate;
	}

	public void setTopFinancingEndDate(String topFinancingEndDate) {
		this.topFinancingEndDate = topFinancingEndDate;
	}

	public String getTopFinancingStartDate() {
		return topFinancingStartDate;
	}

	public void setTopFinancingStartDate(String topFinancingStartDate) {
		this.topFinancingStartDate = topFinancingStartDate;
	}

	public String getTopGuarantyInd() {
		return topGuarantyInd;
	}

	public void setTopGuarantyInd(String topGuarantyInd) {
		this.topGuarantyInd = topGuarantyInd;
	}

	public String getTransferedToWrInd() {
		return transferedToWrInd;
	}

	public void setTransferedToWrInd(String transferedToWrInd) {
		this.transferedToWrInd = transferedToWrInd;
	}

	public Integer getWidthTerm() {
		return widthTerm;
	}

	public void setWidthTerm(Integer widthTerm) {
		this.widthTerm = widthTerm;
	}

	public String getWrOrgCd() {
		return wrOrgCd;
	}

	public void setWrOrgCd(String wrOrgCd) {
		this.wrOrgCd = wrOrgCd;
	}

	public String getYhCurrencyCd() {
		return yhCurrencyCd;
	}

	public void setYhCurrencyCd(String yhCurrencyCd) {
		this.yhCurrencyCd = yhCurrencyCd;
	}

	public String getLastMaintainDate() {
		return lastMaintainDate;
	}

	public void setLastMaintainDate(String lastMaintainDate) {
		this.lastMaintainDate = lastMaintainDate;
	}


}


