package com.gbicc.personCommon.entity;
// Generated 2016-2-19 17:27:55 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * TPlTaskRoutineMoni generated by hbm2java
 */
public class TPlTaskRoutineMoni  implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	/*
    * 账户ID.
    */
    private String accId;
    /*
    * 风险分类等级.
    */
    private String riskFlag;
    /*
    * 开户日期.
    */
    private Date openDate;
    /*
    * 贷款结清标志.
    */
    private String settleFlag;
    /*
    * 产品代码.
    */
    private String productCode;
    /*
    * 上次使用等级.
    */
    private Integer rankPrev;
    /*
    * 本次使用等级.
    */
    private Integer rank;
    /*
    * 任务触发频率.
    */
    private Double trigRate;
    /*
    * 人工调整任务触发频率.
    */
    private Double trigRateAdjust;
    /*
    * 上次任务触发日期.
    */
    private Date trigDatePrev;
    /*
    * 下次任务触发日期.
    */
    private Date trigDateNext;
    /*
    * 观察期开始日期.
    */
    private Date observStart;
    /*
    * 数据处理日期.
    */
    private Date processDate;

    public TPlTaskRoutineMoni() {
    }

	
    public TPlTaskRoutineMoni(String accId) {
        this.accId = accId;
    }
    public TPlTaskRoutineMoni(String accId, String riskFlag, Date openDate, String settleFlag, String productCode, Integer rankPrev, Integer rank, Double trigRate, Double trigRateAdjust, Date trigDatePrev, Date trigDateNext, Date observStart, Date processDate) {
       this.accId = accId;
       this.riskFlag = riskFlag;
       this.openDate = openDate;
       this.settleFlag = settleFlag;
       this.productCode = productCode;
       this.rankPrev = rankPrev;
       this.rank = rank;
       this.trigRate = trigRate;
       this.trigRateAdjust = trigRateAdjust;
       this.trigDatePrev = trigDatePrev;
       this.trigDateNext = trigDateNext;
       this.observStart = observStart;
       this.processDate = processDate;
    }
   
	/**
    * Get the 账户ID
    */	
    public String getAccId() {
        return this.accId;
    }
	/**
    * Set the 账户ID
    */	
    public void setAccId(String accId) {
        this.accId = accId;
    }
	/**
    * Get the 风险分类等级
    */	
    public String getRiskFlag() {
        return this.riskFlag;
    }
	/**
    * Set the 风险分类等级
    */	
    public void setRiskFlag(String riskFlag) {
        this.riskFlag = riskFlag;
    }
	/**
    * Get the 开户日期
    */	
    public Date getOpenDate() {
        return this.openDate;
    }
	/**
    * Set the 开户日期
    */	
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }
	/**
    * Get the 贷款结清标志
    */	
    public String getSettleFlag() {
        return this.settleFlag;
    }
	/**
    * Set the 贷款结清标志
    */	
    public void setSettleFlag(String settleFlag) {
        this.settleFlag = settleFlag;
    }
	/**
    * Get the 产品代码
    */	
    public String getProductCode() {
        return this.productCode;
    }
	/**
    * Set the 产品代码
    */	
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
	/**
    * Get the 上次使用等级
    */	
    public Integer getRankPrev() {
        return this.rankPrev;
    }
	/**
    * Set the 上次使用等级
    */	
    public void setRankPrev(Integer rankPrev) {
        this.rankPrev = rankPrev;
    }
	/**
    * Get the 本次使用等级
    */	
    public Integer getRank() {
        return this.rank;
    }
	/**
    * Set the 本次使用等级
    */	
    public void setRank(Integer rank) {
        this.rank = rank;
    }
	/**
    * Get the 任务触发频率
    */	
    public Double getTrigRate() {
        return this.trigRate;
    }
	/**
    * Set the 任务触发频率
    */	
    public void setTrigRate(Double trigRate) {
        this.trigRate = trigRate;
    }
	/**
    * Get the 人工调整任务触发频率
    */	
    public Double getTrigRateAdjust() {
        return this.trigRateAdjust;
    }
	/**
    * Set the 人工调整任务触发频率
    */	
    public void setTrigRateAdjust(Double trigRateAdjust) {
        this.trigRateAdjust = trigRateAdjust;
    }
	/**
    * Get the 上次任务触发日期
    */	
    public Date getTrigDatePrev() {
        return this.trigDatePrev;
    }
	/**
    * Set the 上次任务触发日期
    */	
    public void setTrigDatePrev(Date trigDatePrev) {
        this.trigDatePrev = trigDatePrev;
    }
	/**
    * Get the 下次任务触发日期
    */	
    public Date getTrigDateNext() {
        return this.trigDateNext;
    }
	/**
    * Set the 下次任务触发日期
    */	
    public void setTrigDateNext(Date trigDateNext) {
        this.trigDateNext = trigDateNext;
    }
	/**
    * Get the 观察期开始日期
    */	
    public Date getObservStart() {
        return this.observStart;
    }
	/**
    * Set the 观察期开始日期
    */	
    public void setObservStart(Date observStart) {
        this.observStart = observStart;
    }
	/**
    * Get the 数据处理日期
    */	
    public Date getProcessDate() {
        return this.processDate;
    }
	/**
    * Set the 数据处理日期
    */	
    public void setProcessDate(Date processDate) {
        this.processDate = processDate;
    }




}


