package com.gbicc.personCommon.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 客户经营情况信息表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TEdwPlsBusiness implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 经营项目编号. */
	private String keyno;

	/** 法人客户编号. */
	private String corpcustid;

	/** 营业执照号. */
	private String liceid;

	/** 注册地址. */
	private String liceaddr;

	/** 经营地址. */
	private String dealaddr;

	/** 成立日期. */
	private Date comedate;

	/** 经营范围. */
	private String dealscope;

	/** 雇员人数. */
	private Integer empnum;

	/**
	 * Constructor.
	 */
	public TEdwPlsBusiness() {
	}

	/**
	 * Set the 经营项目编号.
	 * 
	 * @param keyno
	 *            经营项目编号
	 */
	public void setKeyno(String keyno) {
		this.keyno = keyno;
	}

	/**
	 * Get the 经营项目编号.
	 * 
	 * @return 经营项目编号
	 */
	public String getKeyno() {
		return this.keyno;
	}

	/**
	 * Set the 法人客户编号.
	 * 
	 * @param corpcustid
	 *            法人客户编号
	 */
	public void setCorpcustid(String corpcustid) {
		this.corpcustid = corpcustid;
	}

	/**
	 * Get the 法人客户编号.
	 * 
	 * @return 法人客户编号
	 */
	public String getCorpcustid() {
		return this.corpcustid;
	}

	/**
	 * Set the 营业执照号.
	 * 
	 * @param liceid
	 *            营业执照号
	 */
	public void setLiceid(String liceid) {
		this.liceid = liceid;
	}

	/**
	 * Get the 营业执照号.
	 * 
	 * @return 营业执照号
	 */
	public String getLiceid() {
		return this.liceid;
	}

	/**
	 * Set the 注册地址.
	 * 
	 * @param liceaddr
	 *            注册地址
	 */
	public void setLiceaddr(String liceaddr) {
		this.liceaddr = liceaddr;
	}

	/**
	 * Get the 注册地址.
	 * 
	 * @return 注册地址
	 */
	public String getLiceaddr() {
		return this.liceaddr;
	}

	/**
	 * Set the 经营地址.
	 * 
	 * @param dealaddr
	 *            经营地址
	 */
	public void setDealaddr(String dealaddr) {
		this.dealaddr = dealaddr;
	}

	/**
	 * Get the 经营地址.
	 * 
	 * @return 经营地址
	 */
	public String getDealaddr() {
		return this.dealaddr;
	}

	/**
	 * Set the 成立日期.
	 * 
	 * @param comedate
	 *            成立日期
	 */
	public void setComedate(Date comedate) {
		this.comedate = comedate;
	}

	/**
	 * Get the 成立日期.
	 * 
	 * @return 成立日期
	 */
	public Date getComedate() {
		return this.comedate;
	}

	/**
	 * Set the 经营范围.
	 * 
	 * @param dealscope
	 *            经营范围
	 */
	public void setDealscope(String dealscope) {
		this.dealscope = dealscope;
	}

	/**
	 * Get the 经营范围.
	 * 
	 * @return 经营范围
	 */
	public String getDealscope() {
		return this.dealscope;
	}

	/**
	 * Set the 雇员人数.
	 * 
	 * @param empnum
	 *            雇员人数
	 */
	public void setEmpnum(Integer empnum) {
		this.empnum = empnum;
	}

	/**
	 * Get the 雇员人数.
	 * 
	 * @return 雇员人数
	 */
	public Integer getEmpnum() {
		return this.empnum;
	}


}
