package com.gbicc.company.single.outputentity;
// Generated 2016-1-12 19:22:04 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * TRewA38BgdfId generated by hbm2java
 */
public class A38  implements java.io.Serializable {

	private static final long serialVersionUID = -7410325165713725339L;
	
	/*
    */
    private String instNo;
    /*
    */
    private String branchNumber;
    /*
    */
    private String provincePreCode;
    /*
    */
    private String draftNo;
    /*
    */
    private String draftType;
    /*
    */
    private String contractType;
    /*
    */
    private String contractNo;
    /*
    */
    private String sequenceNo;
    /*
    */
    private String payeeName;
    /*
    */
    private String bankId;
    /*
    */
    private String payBankAcctno;
    /*
    */
    private BigDecimal draftAmt;
    /*
    */
    private String draftIssueDt;
    /*
    */
    private String draftMatDt;
    /*
    */
    private String draftStatus;
    /*
    */
    private String ctaAcctNo;
    /*
    */
    private String acceptanceDate;
    /*
    */
    private String tranType;
    /*
    */
    private String existingDraftNo;
    /*
    */
    private String transferId;
    /*
    */
    private String draftVerType;
    /*
    */
    private String reissueMark;
    /*
    */
    private String reissueReason;
    /*
    */
    private String remAcctNo;
    /*
    */
    private String bgdfCurrency;
    /*
    */
    private String payingBankNo;
    /*
    */
    private String actBankSlNo;
    /*
    */
    private String advanceMark;
    /*
    */
    private String advanceAcctNo;
    /*
    */
    private BigDecimal advanceAmount;
    /*
    */
    private String advanceDate;
    /*
    */
    private String impBlankDocSt;
    /*
    */
    private String settlementMode;
    /*
    */
    private String paymentDate;
    /*
    */
    private String bgdfCipher;
    /*
    */
    private String holderName;
    /*
    */
    private String holdAccountNo;
    /*
    */
    private String holdDepBkNo;
    /*
    */
    private String discountBkNo;
    /*
    */
    private String payReflReason;
    /*
    */
    private String discDraftStatus;
    /*
    */
    private BigDecimal amtFromSecAcct;
    /*
    */
    private BigDecimal amtFromDepAcct;
    /*
    */
    private String holdReason;
    /*
    */
    private String holdUnholdNarr;
    /*
    */
    private String courtAdviseNo;
    /*
    */
    private String cipherType;
    /*
    */
    private String bgdHoldDate;
    /*
    */
    private String tellerNo;
    /*
    */
    private String rmitrMcaSubTyp;
    /*
    */
    private String holderBankName;
    /*
    */
    private String lastMaintDate;
    /*
    */
    private String lastMaintStat;
    /*
    * 预警表ID.
    */
    private String warnId;
    /*
    * 数据日期.
    */
    private String dataDt;

    public A38() {
    }

	/**
    */	
    public String getInstNo() {
        return this.instNo;
    }
	/**
    */	
    public void setInstNo(String instNo) {
        this.instNo = instNo;
    }
	/**
    */	
    public String getBranchNumber() {
        return this.branchNumber;
    }
	/**
    */	
    public void setBranchNumber(String branchNumber) {
        this.branchNumber = branchNumber;
    }
	/**
    */	
    public String getProvincePreCode() {
        return this.provincePreCode;
    }
	/**
    */	
    public void setProvincePreCode(String provincePreCode) {
        this.provincePreCode = provincePreCode;
    }
	/**
    */	
    public String getDraftNo() {
        return this.draftNo;
    }
	/**
    */	
    public void setDraftNo(String draftNo) {
        this.draftNo = draftNo;
    }
	/**
    */	
    public String getDraftType() {
        return this.draftType;
    }
	/**
    */	
    public void setDraftType(String draftType) {
        this.draftType = draftType;
    }
	/**
    */	
    public String getContractType() {
        return this.contractType;
    }
	/**
    */	
    public void setContractType(String contractType) {
        this.contractType = contractType;
    }
	/**
    */	
    public String getContractNo() {
        return this.contractNo;
    }
	/**
    */	
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo;
    }
	/**
    */	
    public String getSequenceNo() {
        return this.sequenceNo;
    }
	/**
    */	
    public void setSequenceNo(String sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
	/**
    */	
    public String getPayeeName() {
        return this.payeeName;
    }
	/**
    */	
    public void setPayeeName(String payeeName) {
        this.payeeName = payeeName;
    }
	/**
    */	
    public String getBankId() {
        return this.bankId;
    }
	/**
    */	
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }
	/**
    */	
    public String getPayBankAcctno() {
        return this.payBankAcctno;
    }
	/**
    */	
    public void setPayBankAcctno(String payBankAcctno) {
        this.payBankAcctno = payBankAcctno;
    }
	/**
    */	
    public BigDecimal getDraftAmt() {
        return this.draftAmt;
    }
	/**
    */	
    public void setDraftAmt(BigDecimal draftAmt) {
        this.draftAmt = draftAmt;
    }
	/**
    */	
    public String getDraftIssueDt() {
        return this.draftIssueDt;
    }
	/**
    */	
    public void setDraftIssueDt(String draftIssueDt) {
        this.draftIssueDt = draftIssueDt;
    }
	/**
    */	
    public String getDraftMatDt() {
        return this.draftMatDt;
    }
	/**
    */	
    public void setDraftMatDt(String draftMatDt) {
        this.draftMatDt = draftMatDt;
    }
	/**
    */	
    public String getDraftStatus() {
        return this.draftStatus;
    }
	/**
    */	
    public void setDraftStatus(String draftStatus) {
        this.draftStatus = draftStatus;
    }
	/**
    */	
    public String getCtaAcctNo() {
        return this.ctaAcctNo;
    }
	/**
    */	
    public void setCtaAcctNo(String ctaAcctNo) {
        this.ctaAcctNo = ctaAcctNo;
    }
	/**
    */	
    public String getAcceptanceDate() {
        return this.acceptanceDate;
    }
	/**
    */	
    public void setAcceptanceDate(String acceptanceDate) {
        this.acceptanceDate = acceptanceDate;
    }
	/**
    */	
    public String getTranType() {
        return this.tranType;
    }
	/**
    */	
    public void setTranType(String tranType) {
        this.tranType = tranType;
    }
	/**
    */	
    public String getExistingDraftNo() {
        return this.existingDraftNo;
    }
	/**
    */	
    public void setExistingDraftNo(String existingDraftNo) {
        this.existingDraftNo = existingDraftNo;
    }
	/**
    */	
    public String getTransferId() {
        return this.transferId;
    }
	/**
    */	
    public void setTransferId(String transferId) {
        this.transferId = transferId;
    }
	/**
    */	
    public String getDraftVerType() {
        return this.draftVerType;
    }
	/**
    */	
    public void setDraftVerType(String draftVerType) {
        this.draftVerType = draftVerType;
    }
	/**
    */	
    public String getReissueMark() {
        return this.reissueMark;
    }
	/**
    */	
    public void setReissueMark(String reissueMark) {
        this.reissueMark = reissueMark;
    }
	/**
    */	
    public String getReissueReason() {
        return this.reissueReason;
    }
	/**
    */	
    public void setReissueReason(String reissueReason) {
        this.reissueReason = reissueReason;
    }
	/**
    */	
    public String getRemAcctNo() {
        return this.remAcctNo;
    }
	/**
    */	
    public void setRemAcctNo(String remAcctNo) {
        this.remAcctNo = remAcctNo;
    }
	/**
    */	
    public String getBgdfCurrency() {
        return this.bgdfCurrency;
    }
	/**
    */	
    public void setBgdfCurrency(String bgdfCurrency) {
        this.bgdfCurrency = bgdfCurrency;
    }
	/**
    */	
    public String getPayingBankNo() {
        return this.payingBankNo;
    }
	/**
    */	
    public void setPayingBankNo(String payingBankNo) {
        this.payingBankNo = payingBankNo;
    }
	/**
    */	
    public String getActBankSlNo() {
        return this.actBankSlNo;
    }
	/**
    */	
    public void setActBankSlNo(String actBankSlNo) {
        this.actBankSlNo = actBankSlNo;
    }
	/**
    */	
    public String getAdvanceMark() {
        return this.advanceMark;
    }
	/**
    */	
    public void setAdvanceMark(String advanceMark) {
        this.advanceMark = advanceMark;
    }
	/**
    */	
    public String getAdvanceAcctNo() {
        return this.advanceAcctNo;
    }
	/**
    */	
    public void setAdvanceAcctNo(String advanceAcctNo) {
        this.advanceAcctNo = advanceAcctNo;
    }
	/**
    */	
    public BigDecimal getAdvanceAmount() {
        return this.advanceAmount;
    }
	/**
    */	
    public void setAdvanceAmount(BigDecimal advanceAmount) {
        this.advanceAmount = advanceAmount;
    }
	/**
    */	
    public String getAdvanceDate() {
        return this.advanceDate;
    }
	/**
    */	
    public void setAdvanceDate(String advanceDate) {
        this.advanceDate = advanceDate;
    }
	/**
    */	
    public String getImpBlankDocSt() {
        return this.impBlankDocSt;
    }
	/**
    */	
    public void setImpBlankDocSt(String impBlankDocSt) {
        this.impBlankDocSt = impBlankDocSt;
    }
	/**
    */	
    public String getSettlementMode() {
        return this.settlementMode;
    }
	/**
    */	
    public void setSettlementMode(String settlementMode) {
        this.settlementMode = settlementMode;
    }
	/**
    */	
    public String getPaymentDate() {
        return this.paymentDate;
    }
	/**
    */	
    public void setPaymentDate(String paymentDate) {
        this.paymentDate = paymentDate;
    }
	/**
    */	
    public String getBgdfCipher() {
        return this.bgdfCipher;
    }
	/**
    */	
    public void setBgdfCipher(String bgdfCipher) {
        this.bgdfCipher = bgdfCipher;
    }
	/**
    */	
    public String getHolderName() {
        return this.holderName;
    }
	/**
    */	
    public void setHolderName(String holderName) {
        this.holderName = holderName;
    }
	/**
    */	
    public String getHoldAccountNo() {
        return this.holdAccountNo;
    }
	/**
    */	
    public void setHoldAccountNo(String holdAccountNo) {
        this.holdAccountNo = holdAccountNo;
    }
	/**
    */	
    public String getHoldDepBkNo() {
        return this.holdDepBkNo;
    }
	/**
    */	
    public void setHoldDepBkNo(String holdDepBkNo) {
        this.holdDepBkNo = holdDepBkNo;
    }
	/**
    */	
    public String getDiscountBkNo() {
        return this.discountBkNo;
    }
	/**
    */	
    public void setDiscountBkNo(String discountBkNo) {
        this.discountBkNo = discountBkNo;
    }
	/**
    */	
    public String getPayReflReason() {
        return this.payReflReason;
    }
	/**
    */	
    public void setPayReflReason(String payReflReason) {
        this.payReflReason = payReflReason;
    }
	/**
    */	
    public String getDiscDraftStatus() {
        return this.discDraftStatus;
    }
	/**
    */	
    public void setDiscDraftStatus(String discDraftStatus) {
        this.discDraftStatus = discDraftStatus;
    }
	/**
    */	
    public BigDecimal getAmtFromSecAcct() {
        return this.amtFromSecAcct;
    }
	/**
    */	
    public void setAmtFromSecAcct(BigDecimal amtFromSecAcct) {
        this.amtFromSecAcct = amtFromSecAcct;
    }
	/**
    */	
    public BigDecimal getAmtFromDepAcct() {
        return this.amtFromDepAcct;
    }
	/**
    */	
    public void setAmtFromDepAcct(BigDecimal amtFromDepAcct) {
        this.amtFromDepAcct = amtFromDepAcct;
    }
	/**
    */	
    public String getHoldReason() {
        return this.holdReason;
    }
	/**
    */	
    public void setHoldReason(String holdReason) {
        this.holdReason = holdReason;
    }
	/**
    */	
    public String getHoldUnholdNarr() {
        return this.holdUnholdNarr;
    }
	/**
    */	
    public void setHoldUnholdNarr(String holdUnholdNarr) {
        this.holdUnholdNarr = holdUnholdNarr;
    }
	/**
    */	
    public String getCourtAdviseNo() {
        return this.courtAdviseNo;
    }
	/**
    */	
    public void setCourtAdviseNo(String courtAdviseNo) {
        this.courtAdviseNo = courtAdviseNo;
    }
	/**
    */	
    public String getCipherType() {
        return this.cipherType;
    }
	/**
    */	
    public void setCipherType(String cipherType) {
        this.cipherType = cipherType;
    }
	/**
    */	
    public String getBgdHoldDate() {
        return this.bgdHoldDate;
    }
	/**
    */	
    public void setBgdHoldDate(String bgdHoldDate) {
        this.bgdHoldDate = bgdHoldDate;
    }
	/**
    */	
    public String getTellerNo() {
        return this.tellerNo;
    }
	/**
    */	
    public void setTellerNo(String tellerNo) {
        this.tellerNo = tellerNo;
    }
	/**
    */	
    public String getRmitrMcaSubTyp() {
        return this.rmitrMcaSubTyp;
    }
	/**
    */	
    public void setRmitrMcaSubTyp(String rmitrMcaSubTyp) {
        this.rmitrMcaSubTyp = rmitrMcaSubTyp;
    }
	/**
    */	
    public String getHolderBankName() {
        return this.holderBankName;
    }
	/**
    */	
    public void setHolderBankName(String holderBankName) {
        this.holderBankName = holderBankName;
    }
	/**
    */	
    public String getLastMaintDate() {
        return this.lastMaintDate;
    }
	/**
    */	
    public void setLastMaintDate(String lastMaintDate) {
        this.lastMaintDate = lastMaintDate;
    }
	/**
    */	
    public String getLastMaintStat() {
        return this.lastMaintStat;
    }
	/**
    */	
    public void setLastMaintStat(String lastMaintStat) {
        this.lastMaintStat = lastMaintStat;
    }
	/**
    * Get the 预警表ID
    */	
    public String getWarnId() {
        return this.warnId;
    }
	/**
    * Set the 预警表ID
    */	
    public void setWarnId(String warnId) {
        this.warnId = warnId;
    }
	/**
    * Get the 数据日期
    */	
    public String getDataDt() {
        return this.dataDt;
    }
	/**
    * Set the 数据日期
    */	
    public void setDataDt(String dataDt) {
        this.dataDt = dataDt;
    }
}