package com.gbicc.company.single.outputentity;
// Generated 2016-1-12 19:22:04 by Hibernate Tools 3.2.2.GA



/**
 * TRewC11EndorsementInfoId generated by hbm2java
 */
public class C11  implements java.io.Serializable {

	private static final long serialVersionUID = -2937590513046856869L;
	
	/*
    */
    private Integer id;
    /*
    */
    private Integer branchId;
    /*
    */
    private Integer contractId;
    /*
    */
    private Integer draftId;
    /*
    */
    private Integer endorsementCount;
    /*
    */
    private String endorsementValue;
    /*
    */
    private String misc0;
    /*
    */
    private String misc1;
    /*
    */
    private String lastUpdTime;
    /*
    * 预警表ID.
    */
    private String warnId;
    /*
    * 数据日期.
    */
    private String dataDt;

    public C11() {
    }

	/**
    */	
    public Integer getId() {
        return this.id;
    }
	/**
    */	
    public void setId(Integer id) {
        this.id = id;
    }
	/**
    */	
    public Integer getBranchId() {
        return this.branchId;
    }
	/**
    */	
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }
	/**
    */	
    public Integer getContractId() {
        return this.contractId;
    }
	/**
    */	
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }
	/**
    */	
    public Integer getDraftId() {
        return this.draftId;
    }
	/**
    */	
    public void setDraftId(Integer draftId) {
        this.draftId = draftId;
    }
	/**
    */	
    public Integer getEndorsementCount() {
        return this.endorsementCount;
    }
	/**
    */	
    public void setEndorsementCount(Integer endorsementCount) {
        this.endorsementCount = endorsementCount;
    }
	/**
    */	
    public String getEndorsementValue() {
        return this.endorsementValue;
    }
	/**
    */	
    public void setEndorsementValue(String endorsementValue) {
        this.endorsementValue = endorsementValue;
    }
	/**
    */	
    public String getMisc0() {
        return this.misc0;
    }
	/**
    */	
    public void setMisc0(String misc0) {
        this.misc0 = misc0;
    }
	/**
    */	
    public String getMisc1() {
        return this.misc1;
    }
	/**
    */	
    public void setMisc1(String misc1) {
        this.misc1 = misc1;
    }
	/**
    */	
    public String getLastUpdTime() {
        return this.lastUpdTime;
    }
	/**
    */	
    public void setLastUpdTime(String lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }
	/**
    * Get the 预警表ID
    */	
    public String getWarnId() {
        return this.warnId;
    }
	/**
    * Set the 预警表ID
    */	
    public void setWarnId(String warnId) {
        this.warnId = warnId;
    }
	/**
    * Get the 数据日期
    */	
    public String getDataDt() {
        return this.dataDt;
    }
	/**
    * Set the 数据日期
    */	
    public void setDataDt(String dataDt) {
        this.dataDt = dataDt;
    }
}