package com.gbicc.person.customer.entity;
// Generated 2016-1-18 10:20:15 by Hibernate Tools 3.2.2.GA



/**
 * TEdwPlsSocietalRelVId generated by hbm2java
 */
public class TEdwPlsSocietalRelV  implements java.io.Serializable {


	 /*
	    * 社会关系记录编号.
	    */
	    private String keyno;
	    /*
	    * 客户编号.
	    */
	    private String custid;
	    /*
	    * 与客户关系.
	    */
	    private String relasign;
	    /*
	    * 关系人编号.
	    */
	    private String familycustid;
	    /*
	    * 关系人.
	    */
	    private String familycustname;
	    /*
	    * 证件类型.
	    */
	    private String paperkind;
	    /*
	    * 证件号码.
	    */
	    private String paperid;
	    private String operid;

    public TEdwPlsSocietalRelV() {
    }

    public TEdwPlsSocietalRelV(String keyno, String custid, String relasign, String familycustid, String familycustname, String paperkind, String paperid, String operid) {
       this.keyno = keyno;
       this.custid = custid;
       this.relasign = relasign;
       this.familycustid = familycustid;
       this.familycustname = familycustname;
       this.paperkind = paperkind;
       this.paperid = paperid;
       this.operid = operid;
    }
   
    public String getKeyno() {
        return this.keyno;
    }
    
    public void setKeyno(String keyno) {
        this.keyno = keyno;
    }
    public String getCustid() {
        return this.custid;
    }
    
    public void setCustid(String custid) {
        this.custid = custid;
    }
    public String getRelasign() {
        return this.relasign;
    }
    
    public void setRelasign(String relasign) {
        this.relasign = relasign;
    }
    public String getFamilycustid() {
        return this.familycustid;
    }
    
    public void setFamilycustid(String familycustid) {
        this.familycustid = familycustid;
    }
    public String getFamilycustname() {
        return this.familycustname;
    }
    
    public void setFamilycustname(String familycustname) {
        this.familycustname = familycustname;
    }
    public String getPaperkind() {
        return this.paperkind;
    }
    
    public void setPaperkind(String paperkind) {
        this.paperkind = paperkind;
    }
    public String getPaperid() {
        return this.paperid;
    }
    
    public void setPaperid(String paperid) {
        this.paperid = paperid;
    }
    public String getOperid() {
        return this.operid;
    }
    
    public void setOperid(String operid) {
        this.operid = operid;
    }


 
}


