package com.gbicc.personCommon.entity;

import java.io.Serializable;

/**
 * Model class of 股东信息表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TEdwPlsPartner implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 法人客户编号. */
	private String corpcustid;

	/** 股东类型. */
	private String holdcusttype;

	/** 股东编号. */
	private String holdcustid;

	/** 股东名称. */
	private String holdcustname;

	/** 证件类型. */
	private String paperkind;

	/** 证件号码. */
	private String paperid;

	/** 持股比例. */
	private Double stockperc;

	/** 投资金额. */
	private Double inveamt;

	/** 是否最大股东. */
	private String ismax;

	/**
	 * Constructor.
	 */
	public TEdwPlsPartner() {
	}

	/**
	 * Set the 法人客户编号.
	 * 
	 * @param corpcustid
	 *            法人客户编号
	 */
	public void setCorpcustid(String corpcustid) {
		this.corpcustid = corpcustid;
	}

	/**
	 * Get the 法人客户编号.
	 * 
	 * @return 法人客户编号
	 */
	public String getCorpcustid() {
		return this.corpcustid;
	}

	/**
	 * Set the 股东类型.
	 * 
	 * @param holdcusttype
	 *            股东类型
	 */
	public void setHoldcusttype(String holdcusttype) {
		this.holdcusttype = holdcusttype;
	}

	/**
	 * Get the 股东类型.
	 * 
	 * @return 股东类型
	 */
	public String getHoldcusttype() {
		return this.holdcusttype;
	}

	/**
	 * Set the 股东编号.
	 * 
	 * @param holdcustid
	 *            股东编号
	 */
	public void setHoldcustid(String holdcustid) {
		this.holdcustid = holdcustid;
	}

	/**
	 * Get the 股东编号.
	 * 
	 * @return 股东编号
	 */
	public String getHoldcustid() {
		return this.holdcustid;
	}

	/**
	 * Set the 股东名称.
	 * 
	 * @param holdcustname
	 *            股东名称
	 */
	public void setHoldcustname(String holdcustname) {
		this.holdcustname = holdcustname;
	}

	/**
	 * Get the 股东名称.
	 * 
	 * @return 股东名称
	 */
	public String getHoldcustname() {
		return this.holdcustname;
	}

	/**
	 * Set the 证件类型.
	 * 
	 * @param paperkind
	 *            证件类型
	 */
	public void setPaperkind(String paperkind) {
		this.paperkind = paperkind;
	}

	/**
	 * Get the 证件类型.
	 * 
	 * @return 证件类型
	 */
	public String getPaperkind() {
		return this.paperkind;
	}

	/**
	 * Set the 证件号码.
	 * 
	 * @param paperid
	 *            证件号码
	 */
	public void setPaperid(String paperid) {
		this.paperid = paperid;
	}

	/**
	 * Get the 证件号码.
	 * 
	 * @return 证件号码
	 */
	public String getPaperid() {
		return this.paperid;
	}

	/**
	 * Set the 持股比例.
	 * 
	 * @param stockperc
	 *            持股比例
	 */
	public void setStockperc(Double stockperc) {
		this.stockperc = stockperc;
	}

	/**
	 * Get the 持股比例.
	 * 
	 * @return 持股比例
	 */
	public Double getStockperc() {
		return this.stockperc;
	}

	/**
	 * Set the 投资金额.
	 * 
	 * @param inveamt
	 *            投资金额
	 */
	public void setInveamt(Double inveamt) {
		this.inveamt = inveamt;
	}

	/**
	 * Get the 投资金额.
	 * 
	 * @return 投资金额
	 */
	public Double getInveamt() {
		return this.inveamt;
	}

	/**
	 * Set the 是否最大股东.
	 * 
	 * @param ismax
	 *            是否最大股东
	 */
	public void setIsmax(String ismax) {
		this.ismax = ismax;
	}

	/**
	 * Get the 是否最大股东.
	 * 
	 * @return 是否最大股东
	 */
	public String getIsmax() {
		return this.ismax;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((corpcustid == null) ? 0 : corpcustid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TEdwPlsPartner other = (TEdwPlsPartner) obj;
		if (corpcustid == null) {
			if (other.corpcustid != null) {
				return false;
			}
		} else if (!corpcustid.equals(other.corpcustid)) {
			return false;
		}
		return true;
	}

}
