package com.gbicc.job.entity;

// Generated 2016-3-17 12:35:41 by Hibernate Tools 3.2.2.GA

/**
 * TEtlJobErrorLog generated by hbm2java
 */
public class TEtlJobErrorLog implements java.io.Serializable {

	
	private static final long serialVersionUID = 698187014594937211L;

	
	public TEtlJobErrorLog() {
	}

	/*
    */
	private String etlErrorLogID;
	/*
    */
	private String etlScheduleID;
	/*
    */
	private String jobName;
	
	/*
    */
	private String errMsg;
	/*
    */
	private String errSql;
	/*
    */
	private String errTimestamp;
	/*
    */


	public String getEtlErrorLogID() {
		return etlErrorLogID;
	}

	public void setEtlErrorLogID(String etlErrorLogID) {
		this.etlErrorLogID = etlErrorLogID;
	}
	
	public String getEtlScheduleID() {
		return etlScheduleID;
	}
	
	public void setEtlScheduleID(String etlScheduleID) {
		this.etlScheduleID = etlScheduleID;
	}
	public String getJobName() {
		return jobName;
	}
	
	public void setJobName(String jobName) {
		this.jobName = jobName;
	}
	
	public String getErrMsg() {
		return errMsg;
	}
	
	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}
	
	public String getErrSql() {
		return errSql;
	}
	
	public void setErrSql(String errSql) {
		this.errSql = errSql;
	}
	
	public String getErrTimestamp() {
		return errTimestamp;
	}
	
	public void setErrTimestamp(String errTimestamp) {
		this.errTimestamp = errTimestamp;
	}

}
