package com.gbicc.warn.ComninationWarn.entity;
// Generated 2016-1-13 11:06:38 by Hibernate Tools 3.2.2.GA


import java.sql.Timestamp;
import java.util.Date;

/**
 * TCwCreditInexOptRecord generated by hbm2java
 */
public class TCwCreditInexOptRecord  implements java.io.Serializable {


    /*
    * 编号.
    */
   private int id;
    /*
    * 操作人.
    */
    private String username;
    /*
    * 成功行数.
    */
    private Integer sucesscount;
    /*
    * 失败行数.
    */
    private Integer errorcount;
    /*
    * 导入日期.
    */
    private Timestamp date;
    
    public TCwCreditInexOptRecord() {
    }

	
    public TCwCreditInexOptRecord(int id) {
        this.id = id;
    }
    public TCwCreditInexOptRecord(int id, String username, Integer sucesscount, Integer errorcount, Timestamp date) {
       this.id = id;
       this.username = username;
       this.sucesscount = sucesscount;
       this.errorcount = errorcount;
       this.date = date;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Integer getSucesscount() {
        return this.sucesscount;
    }
    
    public void setSucesscount(Integer sucesscount) {
        this.sucesscount = sucesscount;
    }
    public Integer getErrorcount() {
        return this.errorcount;
    }
    
    public void setErrorcount(Integer errorcount) {
        this.errorcount = errorcount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Timestamp date) {
        this.date = date;
    }




}


