package com.gbicc.company.view.zxinfo.entity;
// Generated 2015-12-8 10:24:58 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * TCmCompanyCreditIndex generated by hbm2java
 */
public class TCmCompanyCreditIndex  implements java.io.Serializable {


    /*
    */
    private String id;
    /*
    */
    private String acctId;
    /*
    */
    private String custId;
    /*
    * 注册资金.
    */
    private BigDecimal registAmt;
    /*
    * 资本集中度.
    */
    private BigDecimal capitalCent;
    /*
    * 平均出资金额 .
    */
    private BigDecimal capitalAvg;
    /*
    * 出资方数量.
    */
    private Integer capitalNum;
    /*
    * 未结清信用总余额（合计）.
    */
    private BigDecimal nosettTbal;
    /*
    * 未结清信用业务笔数（合计） .
    */
    private Integer nosettTnum;
    /*
    * 未结清关注类信用总余额（合计） .
    */
    private BigDecimal nosettGzTbal;
    /*
    * 未结清关注类信用业务笔数（合计） .
    */
    private Integer nosettGzTnum;
    /*
    * 未结清信用总余额（贷款） .
    */
    private BigDecimal nosettTloanbal;
    /*
    * 未结清信用业务笔数（贷款） .
    */
    private Integer nosettTloannum;
    /*
    * 未结清不良类信贷信用总余额（合计） .
    */
    private BigDecimal nosettBlTbal;
    /*
    * 未结清不良类信用业务笔数（合计） .
    */
    private Integer nosettBlTnum;
    /*
    * 未结清不良类信贷信用总余额（贷款） .
    */
    private BigDecimal nosettBlTloanbal;
    /*
    * 未结清不良类信用业务笔数（贷款） .
    */
    private Integer nosettBlTloannum;
    /*
    * 已结清关注类信用业务笔数（合计） .
    */
    private Integer settGzTnum;
    /*
    * 已结清信用业务笔数（合计） .
    */
    private Integer settTnum;
    /*
    * 已结清信用业务笔数（贷款） .
    */
    private Integer settTloannum;
    /*
    * 已结清关注类信用业务笔数（贷款） .
    */
    private Integer settGzTloannum;
    /*
    * 已结清不良信用业务笔数（合计） .
    */
    private Integer settBlTnum;
    /*
    * 已结清不良信用业务笔数（贷款） .
    */
    private Integer settBlTloannum;
    /*
    * 历史累计不良业务笔数（合计） .
    */
    private Integer hisBlTnum;
    /*
    * 历史累计不良业务笔数（贷款） .
    */
    private Integer hisBlTloannum;
    /*
    * 担保笔数合计 .
    */
    private Integer guatTnum;
    /*
    * 担保金额合计 .
    */
    private BigDecimal guatTamt;
    /*
    * 对外担保关注类业务余额 .
    */
    private BigDecimal guatGzTbal;
    /*
    * 对外担保不良类业务余额 .
    */
    private BigDecimal guatBlTbal;
    /*
    * 报告编号.
    */
    private String reportid;
    /*
    * 报告日期.
    */
    private Date reportdate;

    public TCmCompanyCreditIndex() {
    }

	
    public TCmCompanyCreditIndex(String id) {
        this.id = id;
    }
    public TCmCompanyCreditIndex(String id, String acctId, String custId, BigDecimal registAmt, BigDecimal capitalCent, BigDecimal capitalAvg, Integer capitalNum, BigDecimal nosettTbal, Integer nosettTnum, BigDecimal nosettGzTbal, Integer nosettGzTnum, BigDecimal nosettTloanbal, Integer nosettTloannum, BigDecimal nosettBlTbal, Integer nosettBlTnum, BigDecimal nosettBlTloanbal, Integer nosettBlTloannum, Integer settGzTnum, Integer settTnum, Integer settTloannum, Integer settGzTloannum, Integer settBlTnum, Integer settBlTloannum, Integer hisBlTnum, Integer hisBlTloannum, Integer guatTnum, BigDecimal guatTamt, BigDecimal guatGzTbal, BigDecimal guatBlTbal, String reportid, Date reportdate) {
       this.id = id;
       this.acctId = acctId;
       this.custId = custId;
       this.registAmt = registAmt;
       this.capitalCent = capitalCent;
       this.capitalAvg = capitalAvg;
       this.capitalNum = capitalNum;
       this.nosettTbal = nosettTbal;
       this.nosettTnum = nosettTnum;
       this.nosettGzTbal = nosettGzTbal;
       this.nosettGzTnum = nosettGzTnum;
       this.nosettTloanbal = nosettTloanbal;
       this.nosettTloannum = nosettTloannum;
       this.nosettBlTbal = nosettBlTbal;
       this.nosettBlTnum = nosettBlTnum;
       this.nosettBlTloanbal = nosettBlTloanbal;
       this.nosettBlTloannum = nosettBlTloannum;
       this.settGzTnum = settGzTnum;
       this.settTnum = settTnum;
       this.settTloannum = settTloannum;
       this.settGzTloannum = settGzTloannum;
       this.settBlTnum = settBlTnum;
       this.settBlTloannum = settBlTloannum;
       this.hisBlTnum = hisBlTnum;
       this.hisBlTloannum = hisBlTloannum;
       this.guatTnum = guatTnum;
       this.guatTamt = guatTamt;
       this.guatGzTbal = guatGzTbal;
       this.guatBlTbal = guatBlTbal;
       this.reportid = reportid;
       this.reportdate = reportdate;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getAcctId() {
        return this.acctId;
    }
    
    public void setAcctId(String acctId) {
        this.acctId = acctId;
    }
    public String getCustId() {
        return this.custId;
    }
    
    public void setCustId(String custId) {
        this.custId = custId;
    }
    public BigDecimal getRegistAmt() {
        return this.registAmt;
    }
    
    public void setRegistAmt(BigDecimal registAmt) {
        this.registAmt = registAmt;
    }
    public BigDecimal getCapitalCent() {
        return this.capitalCent;
    }
    
    public void setCapitalCent(BigDecimal capitalCent) {
        this.capitalCent = capitalCent;
    }
    public BigDecimal getCapitalAvg() {
        return this.capitalAvg;
    }
    
    public void setCapitalAvg(BigDecimal capitalAvg) {
        this.capitalAvg = capitalAvg;
    }
    public Integer getCapitalNum() {
        return this.capitalNum;
    }
    
    public void setCapitalNum(Integer capitalNum) {
        this.capitalNum = capitalNum;
    }
    public BigDecimal getNosettTbal() {
        return this.nosettTbal;
    }
    
    public void setNosettTbal(BigDecimal nosettTbal) {
        this.nosettTbal = nosettTbal;
    }
    public Integer getNosettTnum() {
        return this.nosettTnum;
    }
    
    public void setNosettTnum(Integer nosettTnum) {
        this.nosettTnum = nosettTnum;
    }
    public BigDecimal getNosettGzTbal() {
        return this.nosettGzTbal;
    }
    
    public void setNosettGzTbal(BigDecimal nosettGzTbal) {
        this.nosettGzTbal = nosettGzTbal;
    }
    public Integer getNosettGzTnum() {
        return this.nosettGzTnum;
    }
    
    public void setNosettGzTnum(Integer nosettGzTnum) {
        this.nosettGzTnum = nosettGzTnum;
    }
    public BigDecimal getNosettTloanbal() {
        return this.nosettTloanbal;
    }
    
    public void setNosettTloanbal(BigDecimal nosettTloanbal) {
        this.nosettTloanbal = nosettTloanbal;
    }
    public Integer getNosettTloannum() {
        return this.nosettTloannum;
    }
    
    public void setNosettTloannum(Integer nosettTloannum) {
        this.nosettTloannum = nosettTloannum;
    }
    public BigDecimal getNosettBlTbal() {
        return this.nosettBlTbal;
    }
    
    public void setNosettBlTbal(BigDecimal nosettBlTbal) {
        this.nosettBlTbal = nosettBlTbal;
    }
    public Integer getNosettBlTnum() {
        return this.nosettBlTnum;
    }
    
    public void setNosettBlTnum(Integer nosettBlTnum) {
        this.nosettBlTnum = nosettBlTnum;
    }
    public BigDecimal getNosettBlTloanbal() {
        return this.nosettBlTloanbal;
    }
    
    public void setNosettBlTloanbal(BigDecimal nosettBlTloanbal) {
        this.nosettBlTloanbal = nosettBlTloanbal;
    }
    public Integer getNosettBlTloannum() {
        return this.nosettBlTloannum;
    }
    
    public void setNosettBlTloannum(Integer nosettBlTloannum) {
        this.nosettBlTloannum = nosettBlTloannum;
    }
    public Integer getSettGzTnum() {
        return this.settGzTnum;
    }
    
    public void setSettGzTnum(Integer settGzTnum) {
        this.settGzTnum = settGzTnum;
    }
    public Integer getSettTnum() {
        return this.settTnum;
    }
    
    public void setSettTnum(Integer settTnum) {
        this.settTnum = settTnum;
    }
    public Integer getSettTloannum() {
        return this.settTloannum;
    }
    
    public void setSettTloannum(Integer settTloannum) {
        this.settTloannum = settTloannum;
    }
    public Integer getSettGzTloannum() {
        return this.settGzTloannum;
    }
    
    public void setSettGzTloannum(Integer settGzTloannum) {
        this.settGzTloannum = settGzTloannum;
    }
    public Integer getSettBlTnum() {
        return this.settBlTnum;
    }
    
    public void setSettBlTnum(Integer settBlTnum) {
        this.settBlTnum = settBlTnum;
    }
    public Integer getSettBlTloannum() {
        return this.settBlTloannum;
    }
    
    public void setSettBlTloannum(Integer settBlTloannum) {
        this.settBlTloannum = settBlTloannum;
    }
    public Integer getHisBlTnum() {
        return this.hisBlTnum;
    }
    
    public void setHisBlTnum(Integer hisBlTnum) {
        this.hisBlTnum = hisBlTnum;
    }
    public Integer getHisBlTloannum() {
        return this.hisBlTloannum;
    }
    
    public void setHisBlTloannum(Integer hisBlTloannum) {
        this.hisBlTloannum = hisBlTloannum;
    }
    public Integer getGuatTnum() {
        return this.guatTnum;
    }
    
    public void setGuatTnum(Integer guatTnum) {
        this.guatTnum = guatTnum;
    }
    public BigDecimal getGuatTamt() {
        return this.guatTamt;
    }
    
    public void setGuatTamt(BigDecimal guatTamt) {
        this.guatTamt = guatTamt;
    }
    public BigDecimal getGuatGzTbal() {
        return this.guatGzTbal;
    }
    
    public void setGuatGzTbal(BigDecimal guatGzTbal) {
        this.guatGzTbal = guatGzTbal;
    }
    public BigDecimal getGuatBlTbal() {
        return this.guatBlTbal;
    }
    
    public void setGuatBlTbal(BigDecimal guatBlTbal) {
        this.guatBlTbal = guatBlTbal;
    }
    public String getReportid() {
        return this.reportid;
    }
    
    public void setReportid(String reportid) {
        this.reportid = reportid;
    }
    public Date getReportdate() {
        return this.reportdate;
    }
    
    public void setReportdate(Date reportdate) {
        this.reportdate = reportdate;
    }




}


