package com.gbicc.personCommon.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 提前还款表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TEdwPlsPrePay implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 单据序号. */
	private String listid;

	/** 单据类型. */
	private String listtype;

	/** 业务类型. */
	private String busitype;

	/** 业务编号. */
	private String loanid;

	/** 客户编号. */
	private String custid;

	/** 客户名称. */
	private String custname;

	/** 实还本金. */
	private Double rcapi;

	/** 实还利息. */
	private Double rinte;

	/** 实还金额. */
	private Double sumamt;

	/** 提前还款类型. */
	private String aheakind;

	/** 归还期数. */
	private Integer term;

	/** 贷款账号. */
	private String loanacno;

	/** 实还日期. */
	private Date rdate;

	/** 产品代码. */
	private String prodid;

	/**
	 * Constructor.
	 */
	public TEdwPlsPrePay() {
	}

	/**
	 * Set the 单据序号.
	 * 
	 * @param listid
	 *            单据序号
	 */
	public void setListid(String listid) {
		this.listid = listid;
	}

	/**
	 * Get the 单据序号.
	 * 
	 * @return 单据序号
	 */
	public String getListid() {
		return this.listid;
	}

	/**
	 * Set the 单据类型.
	 * 
	 * @param listtype
	 *            单据类型
	 */
	public void setListtype(String listtype) {
		this.listtype = listtype;
	}

	/**
	 * Get the 单据类型.
	 * 
	 * @return 单据类型
	 */
	public String getListtype() {
		return this.listtype;
	}

	/**
	 * Set the 业务类型.
	 * 
	 * @param busitype
	 *            业务类型
	 */
	public void setBusitype(String busitype) {
		this.busitype = busitype;
	}

	/**
	 * Get the 业务类型.
	 * 
	 * @return 业务类型
	 */
	public String getBusitype() {
		return this.busitype;
	}

	/**
	 * Set the 业务编号.
	 * 
	 * @param loanid
	 *            业务编号
	 */
	public void setLoanid(String loanid) {
		this.loanid = loanid;
	}

	/**
	 * Get the 业务编号.
	 * 
	 * @return 业务编号
	 */
	public String getLoanid() {
		return this.loanid;
	}

	/**
	 * Set the 客户编号.
	 * 
	 * @param custid
	 *            客户编号
	 */
	public void setCustid(String custid) {
		this.custid = custid;
	}

	/**
	 * Get the 客户编号.
	 * 
	 * @return 客户编号
	 */
	public String getCustid() {
		return this.custid;
	}

	/**
	 * Set the 客户名称.
	 * 
	 * @param custname
	 *            客户名称
	 */
	public void setCustname(String custname) {
		this.custname = custname;
	}

	/**
	 * Get the 客户名称.
	 * 
	 * @return 客户名称
	 */
	public String getCustname() {
		return this.custname;
	}

	/**
	 * Set the 实还本金.
	 * 
	 * @param rcapi
	 *            实还本金
	 */
	public void setRcapi(Double rcapi) {
		this.rcapi = rcapi;
	}

	/**
	 * Get the 实还本金.
	 * 
	 * @return 实还本金
	 */
	public Double getRcapi() {
		return this.rcapi;
	}

	/**
	 * Set the 实还利息.
	 * 
	 * @param rinte
	 *            实还利息
	 */
	public void setRinte(Double rinte) {
		this.rinte = rinte;
	}

	/**
	 * Get the 实还利息.
	 * 
	 * @return 实还利息
	 */
	public Double getRinte() {
		return this.rinte;
	}

	/**
	 * Set the 实还金额.
	 * 
	 * @param sumamt
	 *            实还金额
	 */
	public void setSumamt(Double sumamt) {
		this.sumamt = sumamt;
	}

	/**
	 * Get the 实还金额.
	 * 
	 * @return 实还金额
	 */
	public Double getSumamt() {
		return this.sumamt;
	}

	/**
	 * Set the 提前还款类型.
	 * 
	 * @param aheakind
	 *            提前还款类型
	 */
	public void setAheakind(String aheakind) {
		this.aheakind = aheakind;
	}

	/**
	 * Get the 提前还款类型.
	 * 
	 * @return 提前还款类型
	 */
	public String getAheakind() {
		return this.aheakind;
	}

	/**
	 * Set the 归还期数.
	 * 
	 * @param term
	 *            归还期数
	 */
	public void setTerm(Integer term) {
		this.term = term;
	}

	/**
	 * Get the 归还期数.
	 * 
	 * @return 归还期数
	 */
	public Integer getTerm() {
		return this.term;
	}

	/**
	 * Set the 贷款账号.
	 * 
	 * @param loanacno
	 *            贷款账号
	 */
	public void setLoanacno(String loanacno) {
		this.loanacno = loanacno;
	}

	/**
	 * Get the 贷款账号.
	 * 
	 * @return 贷款账号
	 */
	public String getLoanacno() {
		return this.loanacno;
	}

	/**
	 * Set the 实还日期.
	 * 
	 * @param rdate
	 *            实还日期
	 */
	public void setRdate(Date rdate) {
		this.rdate = rdate;
	}

	/**
	 * Get the 实还日期.
	 * 
	 * @return 实还日期
	 */
	public Date getRdate() {
		return this.rdate;
	}

	/**
	 * Set the 产品代码.
	 * 
	 * @param prodid
	 *            产品代码
	 */
	public void setProdid(String prodid) {
		this.prodid = prodid;
	}

	/**
	 * Get the 产品代码.
	 * 
	 * @return 产品代码
	 */
	public String getProdid() {
		return this.prodid;
	}


}
