package com.gbicc.personCommon.entity;

import java.io.Serializable;

/**
 * Model class of 抵质押信息表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TEdwPlsMortgage implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 抵质押编号. */
	private String assuid;

	/** 抵质押物名称. */
	private String assuname;

	/** 抵质押人编号. */
	private String custid;

	/** 抵质押人. */
	private String custname;

	/** 抵质押物数量. */
	private Integer impanum;

	/** 权利证书类型. */
	private String impacertkind;

	/** 权利证书号码. */
	private String impacertno;

	/** 证件类型. */
	private String paperkind;

	/** 证件号码. */
	private String paperid;

	/** 抵质押类别. */
	private String impatype;

	/** 抵质押物价值. */
	private Double assuamt;

	/** 担保物原值. */
	private Double orgivalue;

	/** 担保物净值. */
	private Double netvalue;

	/** 评估价值. */
	private Double evalvalue;

	/** 市场价值. */
	private Double martvalue;

	/** 我行确认价值. */
	private Double confvalue;

	/** 抵质押率. */
	private Double assurate2;

	/**
	 * Constructor.
	 */
	public TEdwPlsMortgage() {
	}

	/**
	 * Set the 抵质押编号.
	 * 
	 * @param assuid
	 *            抵质押编号
	 */
	public void setAssuid(String assuid) {
		this.assuid = assuid;
	}

	/**
	 * Get the 抵质押编号.
	 * 
	 * @return 抵质押编号
	 */
	public String getAssuid() {
		return this.assuid;
	}

	/**
	 * Set the 抵质押物名称.
	 * 
	 * @param assuname
	 *            抵质押物名称
	 */
	public void setAssuname(String assuname) {
		this.assuname = assuname;
	}

	/**
	 * Get the 抵质押物名称.
	 * 
	 * @return 抵质押物名称
	 */
	public String getAssuname() {
		return this.assuname;
	}

	/**
	 * Set the 抵质押人编号.
	 * 
	 * @param custid
	 *            抵质押人编号
	 */
	public void setCustid(String custid) {
		this.custid = custid;
	}

	/**
	 * Get the 抵质押人编号.
	 * 
	 * @return 抵质押人编号
	 */
	public String getCustid() {
		return this.custid;
	}

	/**
	 * Set the 抵质押人.
	 * 
	 * @param custname
	 *            抵质押人
	 */
	public void setCustname(String custname) {
		this.custname = custname;
	}

	/**
	 * Get the 抵质押人.
	 * 
	 * @return 抵质押人
	 */
	public String getCustname() {
		return this.custname;
	}

	/**
	 * Set the 抵质押物数量.
	 * 
	 * @param impanum
	 *            抵质押物数量
	 */
	public void setImpanum(Integer impanum) {
		this.impanum = impanum;
	}

	/**
	 * Get the 抵质押物数量.
	 * 
	 * @return 抵质押物数量
	 */
	public Integer getImpanum() {
		return this.impanum;
	}

	/**
	 * Set the 权利证书类型.
	 * 
	 * @param impacertkind
	 *            权利证书类型
	 */
	public void setImpacertkind(String impacertkind) {
		this.impacertkind = impacertkind;
	}

	/**
	 * Get the 权利证书类型.
	 * 
	 * @return 权利证书类型
	 */
	public String getImpacertkind() {
		return this.impacertkind;
	}

	/**
	 * Set the 权利证书号码.
	 * 
	 * @param impacertno
	 *            权利证书号码
	 */
	public void setImpacertno(String impacertno) {
		this.impacertno = impacertno;
	}

	/**
	 * Get the 权利证书号码.
	 * 
	 * @return 权利证书号码
	 */
	public String getImpacertno() {
		return this.impacertno;
	}

	/**
	 * Set the 证件类型.
	 * 
	 * @param paperkind
	 *            证件类型
	 */
	public void setPaperkind(String paperkind) {
		this.paperkind = paperkind;
	}

	/**
	 * Get the 证件类型.
	 * 
	 * @return 证件类型
	 */
	public String getPaperkind() {
		return this.paperkind;
	}

	/**
	 * Set the 证件号码.
	 * 
	 * @param paperid
	 *            证件号码
	 */
	public void setPaperid(String paperid) {
		this.paperid = paperid;
	}

	/**
	 * Get the 证件号码.
	 * 
	 * @return 证件号码
	 */
	public String getPaperid() {
		return this.paperid;
	}

	/**
	 * Set the 抵质押类别.
	 * 
	 * @param impatype
	 *            抵质押类别
	 */
	public void setImpatype(String impatype) {
		this.impatype = impatype;
	}

	/**
	 * Get the 抵质押类别.
	 * 
	 * @return 抵质押类别
	 */
	public String getImpatype() {
		return this.impatype;
	}

	/**
	 * Set the 抵质押物价值.
	 * 
	 * @param assuamt
	 *            抵质押物价值
	 */
	public void setAssuamt(Double assuamt) {
		this.assuamt = assuamt;
	}

	/**
	 * Get the 抵质押物价值.
	 * 
	 * @return 抵质押物价值
	 */
	public Double getAssuamt() {
		return this.assuamt;
	}

	/**
	 * Set the 担保物原值.
	 * 
	 * @param orgivalue
	 *            担保物原值
	 */
	public void setOrgivalue(Double orgivalue) {
		this.orgivalue = orgivalue;
	}

	/**
	 * Get the 担保物原值.
	 * 
	 * @return 担保物原值
	 */
	public Double getOrgivalue() {
		return this.orgivalue;
	}

	/**
	 * Set the 担保物净值.
	 * 
	 * @param netvalue
	 *            担保物净值
	 */
	public void setNetvalue(Double netvalue) {
		this.netvalue = netvalue;
	}

	/**
	 * Get the 担保物净值.
	 * 
	 * @return 担保物净值
	 */
	public Double getNetvalue() {
		return this.netvalue;
	}

	/**
	 * Set the 评估价值.
	 * 
	 * @param evalvalue
	 *            评估价值
	 */
	public void setEvalvalue(Double evalvalue) {
		this.evalvalue = evalvalue;
	}

	/**
	 * Get the 评估价值.
	 * 
	 * @return 评估价值
	 */
	public Double getEvalvalue() {
		return this.evalvalue;
	}

	/**
	 * Set the 市场价值.
	 * 
	 * @param martvalue
	 *            市场价值
	 */
	public void setMartvalue(Double martvalue) {
		this.martvalue = martvalue;
	}

	/**
	 * Get the 市场价值.
	 * 
	 * @return 市场价值
	 */
	public Double getMartvalue() {
		return this.martvalue;
	}

	/**
	 * Set the 我行确认价值.
	 * 
	 * @param confvalue
	 *            我行确认价值
	 */
	public void setConfvalue(Double confvalue) {
		this.confvalue = confvalue;
	}

	/**
	 * Get the 我行确认价值.
	 * 
	 * @return 我行确认价值
	 */
	public Double getConfvalue() {
		return this.confvalue;
	}

	/**
	 * Set the 抵质押率.
	 * 
	 * @param assurate2
	 *            抵质押率
	 */
	public void setAssurate2(Double assurate2) {
		this.assurate2 = assurate2;
	}

	/**
	 * Get the 抵质押率.
	 * 
	 * @return 抵质押率
	 */
	public Double getAssurate2() {
		return this.assurate2;
	}


}
