package com.gbicc.company.single.outputentity;
// Generated 2016-1-15 16:51:03 by Hibernate Tools 3.2.2.GA


import java.sql.Clob;

/**
 * TRewL05CouJudgmentDetailId generated by hbm2java
 */
public class L05  implements java.io.Serializable {

	private static final long serialVersionUID = 6710307135777192415L;
	
	/*
    * ID.
    */
    private String id;
    /*
    * 企业名称/姓名.
    */
    private String companyAnme;
    /*
    * 案件大类.
    */
    private String caseType;
    /*
    * 文书编号.
    */
    private String writNo;
    /*
    * 文书标题.
    */
    private String writTitle;
    /*
    * 判决法院.
    */
    private String judgCourt;
    /*
    * 判决时间.
    */
    private String judgDate;
    /*
    * 原始文档.
    */
    private Clob content;
    /*
    * 原链接.
    */
    private String sourceLink;
    /*
    * 关联基本信息主键.
    */
    private String baseId;
    /*
    * 关联ID.
    */
    private String relaId;
    /*
    * 数据日期.
    */
    private String rowDate;
    /*
    * 预警表ID.
    */
    private String warnId;
    /*
    * 数据日期.
    */
    private String dataDt;

    public L05() {
    }

	/**
    * Get the ID
    */	
    public String getId() {
        return this.id;
    }
	/**
    * Set the ID
    */	
    public void setId(String id) {
        this.id = id;
    }
	/**
    * Get the 企业名称/姓名
    */	
    public String getCompanyAnme() {
        return this.companyAnme;
    }
	/**
    * Set the 企业名称/姓名
    */	
    public void setCompanyAnme(String companyAnme) {
        this.companyAnme = companyAnme;
    }
	/**
    * Get the 案件大类
    */	
    public String getCaseType() {
        return this.caseType;
    }
	/**
    * Set the 案件大类
    */	
    public void setCaseType(String caseType) {
        this.caseType = caseType;
    }
	/**
    * Get the 文书编号
    */	
    public String getWritNo() {
        return this.writNo;
    }
	/**
    * Set the 文书编号
    */	
    public void setWritNo(String writNo) {
        this.writNo = writNo;
    }
	/**
    * Get the 文书标题
    */	
    public String getWritTitle() {
        return this.writTitle;
    }
	/**
    * Set the 文书标题
    */	
    public void setWritTitle(String writTitle) {
        this.writTitle = writTitle;
    }
	/**
    * Get the 判决法院
    */	
    public String getJudgCourt() {
        return this.judgCourt;
    }
	/**
    * Set the 判决法院
    */	
    public void setJudgCourt(String judgCourt) {
        this.judgCourt = judgCourt;
    }
	/**
    * Get the 判决时间
    */	
    public String getJudgDate() {
        return this.judgDate;
    }
	/**
    * Set the 判决时间
    */	
    public void setJudgDate(String judgDate) {
        this.judgDate = judgDate;
    }
	/**
    * Get the 原始文档
    */	
    public Clob getContent() {
        return this.content;
    }
	/**
    * Set the 原始文档
    */	
    public void setContent(Clob content) {
        this.content = content;
    }
	/**
    * Get the 原链接
    */	
    public String getSourceLink() {
        return this.sourceLink;
    }
	/**
    * Set the 原链接
    */	
    public void setSourceLink(String sourceLink) {
        this.sourceLink = sourceLink;
    }
	/**
    * Get the 关联基本信息主键
    */	
    public String getBaseId() {
        return this.baseId;
    }
	/**
    * Set the 关联基本信息主键
    */	
    public void setBaseId(String baseId) {
        this.baseId = baseId;
    }
	/**
    * Get the 关联ID
    */	
    public String getRelaId() {
        return this.relaId;
    }
	/**
    * Set the 关联ID
    */	
    public void setRelaId(String relaId) {
        this.relaId = relaId;
    }
	/**
    * Get the 数据日期
    */	
    public String getRowDate() {
        return this.rowDate;
    }
	/**
    * Set the 数据日期
    */	
    public void setRowDate(String rowDate) {
        this.rowDate = rowDate;
    }
	/**
    * Get the 预警表ID
    */	
    public String getWarnId() {
        return this.warnId;
    }
	/**
    * Set the 预警表ID
    */	
    public void setWarnId(String warnId) {
        this.warnId = warnId;
    }
	/**
    * Get the 数据日期
    */	
    public String getDataDt() {
        return this.dataDt;
    }
	/**
    * Set the 数据日期
    */	
    public void setDataDt(String dataDt) {
        this.dataDt = dataDt;
    }
}