package com.gbicc.company.financial.analysis.entity;
// Generated 2015-12-5 15:32:56 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * TCmFinanceStatementData generated by hbm2java
 */
public class TCmFinanceStatementData  implements java.io.Serializable {


    /*
    * 财务报表数据ID .
    */
    private String financeStatementDataId;
    /*
    * 财务报表ID .
    */
    private String financeStatementId;
    /*
    * 客户财务信息ID .
    */
    private String customerFinanceId;
    /*
    * 项目值 .
    */
    private BigDecimal projectValue;
    /*
    */
    private String projectCd;
    /*
    * 项目累计值 .
    */
    private BigDecimal addUpProjectValue;

    public TCmFinanceStatementData() {
    }

	
    public TCmFinanceStatementData(String financeStatementDataId) {
        this.financeStatementDataId = financeStatementDataId;
    }
    public TCmFinanceStatementData(String financeStatementDataId, String financeStatementId, String customerFinanceId, BigDecimal projectValue, String projectCd, BigDecimal addUpProjectValue) {
       this.financeStatementDataId = financeStatementDataId;
       this.financeStatementId = financeStatementId;
       this.customerFinanceId = customerFinanceId;
       this.projectValue = projectValue;
       this.projectCd = projectCd;
       this.addUpProjectValue = addUpProjectValue;
    }
   
    public String getFinanceStatementDataId() {
        return this.financeStatementDataId;
    }
    
    public void setFinanceStatementDataId(String financeStatementDataId) {
        this.financeStatementDataId = financeStatementDataId;
    }
    public String getFinanceStatementId() {
        return this.financeStatementId;
    }
    
    public void setFinanceStatementId(String financeStatementId) {
        this.financeStatementId = financeStatementId;
    }
    public String getCustomerFinanceId() {
        return this.customerFinanceId;
    }
    
    public void setCustomerFinanceId(String customerFinanceId) {
        this.customerFinanceId = customerFinanceId;
    }
    public BigDecimal getProjectValue() {
        return this.projectValue;
    }
    
    public void setProjectValue(BigDecimal projectValue) {
        this.projectValue = projectValue;
    }
    public String getProjectCd() {
        return this.projectCd;
    }
    
    public void setProjectCd(String projectCd) {
        this.projectCd = projectCd;
    }
    public BigDecimal getAddUpProjectValue() {
        return this.addUpProjectValue;
    }
    
    public void setAddUpProjectValue(BigDecimal addUpProjectValue) {
        this.addUpProjectValue = addUpProjectValue;
    }




}


