package com.gbicc.company.single.outputentity;
// Generated 2016-3-17 12:40:17 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * TRewC02BorrAccountListInfoId generated by hbm2java
 */
public class C02  implements java.io.Serializable {

	private static final long serialVersionUID = -4677543423370395511L;
	
	/*
    * 信息ID                      .
    */
    private String infoId;
    /*
    * 借据号                      .
    */
    private String borrowNum;
    /*
    * 帐号                        .
    */
    private String accounts;
    /*
    * 交易日期                    .
    */
    private String exchangeDate;
    /*
    * 交易时间                    .
    */
    private String exchangeTime;
    /*
    * 交易码                      .
    */
    private String exchangeCode;
    /*
    * 借贷标识                    .
    */
    private String onLoanSign;
    /*
    * 交易金额                    .
    */
    private BigDecimal exchangeSum;
    /*
    * 帐户余额                    .
    */
    private BigDecimal accountsBalance;
    /*
    * 交易机构                    .
    */
    private String exchangeOrgan;
    /*
    * 交易柜员                    .
    */
    private String exchangeOp;
    /*
    * 授权柜员                    .
    */
    private String accreditOp;
    /*
    * 柜员交易号                  .
    */
    private String opExchangeSign;
    /*
    * 现转标识                    .
    */
    private String conversionSign;
    /*
    * 本网点交易号                .
    */
    private String organExchangeSign;
    /*
    * 摘要                        .
    */
    private String summary;
    /*
    * 冲补标识                    .
    */
    private String cbSign;
    /*
    * 记录状态                    .
    */
    private String recordState;
    /*
    * 日终登记日期                .
    */
    private String lastMaintainDate;
    /*
    * ETL日期                     .
    */
    private String etlDate;
    /*
    * 帐务明细标识                .
    */
    private String detailCd;
    /*
    * 拖欠本金（桶子P）           .
    */
    private BigDecimal bucketP;
    /*
    * 拖欠利息（桶子I）           .
    */
    private BigDecimal bocketI;
    /*
    * 欠本罚息（桶子W）           .
    */
    private BigDecimal bocketW;
    /*
    * 欠息罚息（桶子A）           .
    */
    private BigDecimal bocketA;
    /*
    * 复利（桶子E）               .
    */
    private BigDecimal bocketE;
    /*
    * 未知字段27                  .
    */
    private String ctaAccState;
    /*
    * 调整交易标志                .
    */
    private String adjustType;
    /*
    * 预警ID.
    */
    private String warnId;
    /*
    * 数据日期.
    */
    private String dataDt;

    public C02() {
    }

	/**
    * Get the 信息ID                      
    */	
    public String getInfoId() {
        return this.infoId;
    }
	/**
    * Set the 信息ID                      
    */	
    public void setInfoId(String infoId) {
        this.infoId = infoId;
    }
	/**
    * Get the 借据号                      
    */	
    public String getBorrowNum() {
        return this.borrowNum;
    }
	/**
    * Set the 借据号                      
    */	
    public void setBorrowNum(String borrowNum) {
        this.borrowNum = borrowNum;
    }
	/**
    * Get the 帐号                        
    */	
    public String getAccounts() {
        return this.accounts;
    }
	/**
    * Set the 帐号                        
    */	
    public void setAccounts(String accounts) {
        this.accounts = accounts;
    }
	/**
    * Get the 交易日期                    
    */	
    public String getExchangeDate() {
        return this.exchangeDate;
    }
	/**
    * Set the 交易日期                    
    */	
    public void setExchangeDate(String exchangeDate) {
        this.exchangeDate = exchangeDate;
    }
	/**
    * Get the 交易时间                    
    */	
    public String getExchangeTime() {
        return this.exchangeTime;
    }
	/**
    * Set the 交易时间                    
    */	
    public void setExchangeTime(String exchangeTime) {
        this.exchangeTime = exchangeTime;
    }
	/**
    * Get the 交易码                      
    */	
    public String getExchangeCode() {
        return this.exchangeCode;
    }
	/**
    * Set the 交易码                      
    */	
    public void setExchangeCode(String exchangeCode) {
        this.exchangeCode = exchangeCode;
    }
	/**
    * Get the 借贷标识                    
    */	
    public String getOnLoanSign() {
        return this.onLoanSign;
    }
	/**
    * Set the 借贷标识                    
    */	
    public void setOnLoanSign(String onLoanSign) {
        this.onLoanSign = onLoanSign;
    }
	/**
    * Get the 交易金额                    
    */	
    public BigDecimal getExchangeSum() {
        return this.exchangeSum;
    }
	/**
    * Set the 交易金额                    
    */	
    public void setExchangeSum(BigDecimal exchangeSum) {
        this.exchangeSum = exchangeSum;
    }
	/**
    * Get the 帐户余额                    
    */	
    public BigDecimal getAccountsBalance() {
        return this.accountsBalance;
    }
	/**
    * Set the 帐户余额                    
    */	
    public void setAccountsBalance(BigDecimal accountsBalance) {
        this.accountsBalance = accountsBalance;
    }
	/**
    * Get the 交易机构                    
    */	
    public String getExchangeOrgan() {
        return this.exchangeOrgan;
    }
	/**
    * Set the 交易机构                    
    */	
    public void setExchangeOrgan(String exchangeOrgan) {
        this.exchangeOrgan = exchangeOrgan;
    }
	/**
    * Get the 交易柜员                    
    */	
    public String getExchangeOp() {
        return this.exchangeOp;
    }
	/**
    * Set the 交易柜员                    
    */	
    public void setExchangeOp(String exchangeOp) {
        this.exchangeOp = exchangeOp;
    }
	/**
    * Get the 授权柜员                    
    */	
    public String getAccreditOp() {
        return this.accreditOp;
    }
	/**
    * Set the 授权柜员                    
    */	
    public void setAccreditOp(String accreditOp) {
        this.accreditOp = accreditOp;
    }
	/**
    * Get the 柜员交易号                  
    */	
    public String getOpExchangeSign() {
        return this.opExchangeSign;
    }
	/**
    * Set the 柜员交易号                  
    */	
    public void setOpExchangeSign(String opExchangeSign) {
        this.opExchangeSign = opExchangeSign;
    }
	/**
    * Get the 现转标识                    
    */	
    public String getConversionSign() {
        return this.conversionSign;
    }
	/**
    * Set the 现转标识                    
    */	
    public void setConversionSign(String conversionSign) {
        this.conversionSign = conversionSign;
    }
	/**
    * Get the 本网点交易号                
    */	
    public String getOrganExchangeSign() {
        return this.organExchangeSign;
    }
	/**
    * Set the 本网点交易号                
    */	
    public void setOrganExchangeSign(String organExchangeSign) {
        this.organExchangeSign = organExchangeSign;
    }
	/**
    * Get the 摘要                        
    */	
    public String getSummary() {
        return this.summary;
    }
	/**
    * Set the 摘要                        
    */	
    public void setSummary(String summary) {
        this.summary = summary;
    }
	/**
    * Get the 冲补标识                    
    */	
    public String getCbSign() {
        return this.cbSign;
    }
	/**
    * Set the 冲补标识                    
    */	
    public void setCbSign(String cbSign) {
        this.cbSign = cbSign;
    }
	/**
    * Get the 记录状态                    
    */	
    public String getRecordState() {
        return this.recordState;
    }
	/**
    * Set the 记录状态                    
    */	
    public void setRecordState(String recordState) {
        this.recordState = recordState;
    }
	/**
    * Get the 日终登记日期                
    */	
    public String getLastMaintainDate() {
        return this.lastMaintainDate;
    }
	/**
    * Set the 日终登记日期                
    */	
    public void setLastMaintainDate(String lastMaintainDate) {
        this.lastMaintainDate = lastMaintainDate;
    }
	/**
    * Get the ETL日期                     
    */	
    public String getEtlDate() {
        return this.etlDate;
    }
	/**
    * Set the ETL日期                     
    */	
    public void setEtlDate(String etlDate) {
        this.etlDate = etlDate;
    }
	/**
    * Get the 帐务明细标识                
    */	
    public String getDetailCd() {
        return this.detailCd;
    }
	/**
    * Set the 帐务明细标识                
    */	
    public void setDetailCd(String detailCd) {
        this.detailCd = detailCd;
    }
	/**
    * Get the 拖欠本金（桶子P）           
    */	
    public BigDecimal getBucketP() {
        return this.bucketP;
    }
	/**
    * Set the 拖欠本金（桶子P）           
    */	
    public void setBucketP(BigDecimal bucketP) {
        this.bucketP = bucketP;
    }
	/**
    * Get the 拖欠利息（桶子I）           
    */	
    public BigDecimal getBocketI() {
        return this.bocketI;
    }
	/**
    * Set the 拖欠利息（桶子I）           
    */	
    public void setBocketI(BigDecimal bocketI) {
        this.bocketI = bocketI;
    }
	/**
    * Get the 欠本罚息（桶子W）           
    */	
    public BigDecimal getBocketW() {
        return this.bocketW;
    }
	/**
    * Set the 欠本罚息（桶子W）           
    */	
    public void setBocketW(BigDecimal bocketW) {
        this.bocketW = bocketW;
    }
	/**
    * Get the 欠息罚息（桶子A）           
    */	
    public BigDecimal getBocketA() {
        return this.bocketA;
    }
	/**
    * Set the 欠息罚息（桶子A）           
    */	
    public void setBocketA(BigDecimal bocketA) {
        this.bocketA = bocketA;
    }
	/**
    * Get the 复利（桶子E）               
    */	
    public BigDecimal getBocketE() {
        return this.bocketE;
    }
	/**
    * Set the 复利（桶子E）               
    */	
    public void setBocketE(BigDecimal bocketE) {
        this.bocketE = bocketE;
    }
	/**
    * Get the 未知字段27                  
    */	
    public String getCtaAccState() {
        return this.ctaAccState;
    }
	/**
    * Set the 未知字段27                  
    */	
    public void setCtaAccState(String ctaAccState) {
        this.ctaAccState = ctaAccState;
    }
	/**
    * Get the 调整交易标志                
    */	
    public String getAdjustType() {
        return this.adjustType;
    }
	/**
    * Set the 调整交易标志                
    */	
    public void setAdjustType(String adjustType) {
        this.adjustType = adjustType;
    }
	/**
    * Get the 预警ID
    */	
    public String getWarnId() {
        return this.warnId;
    }
	/**
    * Set the 预警ID
    */	
    public void setWarnId(String warnId) {
        this.warnId = warnId;
    }
	/**
    * Get the 数据日期
    */	
    public String getDataDt() {
        return this.dataDt;
    }
	/**
    * Set the 数据日期
    */	
    public void setDataDt(String dataDt) {
        this.dataDt = dataDt;
    }
}