package com.gbicc.company.financial.analysis.entity;
// Generated 2015-12-5 15:32:56 by Hibernate Tools 3.2.2.GA



/**
 * TCmFinanceIndexCd generated by hbm2java
 */
public class TCmFinanceIndexCd  implements java.io.Serializable {


    /*
    * 指标代码 .
    */
    private String indexCd;
    /*
    * 指标名称 .
    */
    private String indexName;
    /*
    * 指标分类代码（字典） .
    */
    private String indexType;
    /*
    * 财务报表类别代码（字典 企业、事业、农） .
    */
    private String reportClass;
    /*
    * 是否属于财务诊断书 .
    */
    private String idCertificate;
    /*
    * 指标描述 .
    */
    private String remarks;

    public TCmFinanceIndexCd() {
    }

	
    public TCmFinanceIndexCd(String indexCd) {
        this.indexCd = indexCd;
    }
    public TCmFinanceIndexCd(String indexCd, String indexName, String indexType, String reportClass, String idCertificate, String remarks) {
       this.indexCd = indexCd;
       this.indexName = indexName;
       this.indexType = indexType;
       this.reportClass = reportClass;
       this.idCertificate = idCertificate;
       this.remarks = remarks;
    }
   
    public String getIndexCd() {
        return this.indexCd;
    }
    
    public void setIndexCd(String indexCd) {
        this.indexCd = indexCd;
    }
    public String getIndexName() {
        return this.indexName;
    }
    
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }
    public String getIndexType() {
        return this.indexType;
    }
    
    public void setIndexType(String indexType) {
        this.indexType = indexType;
    }
    public String getReportClass() {
        return this.reportClass;
    }
    
    public void setReportClass(String reportClass) {
        this.reportClass = reportClass;
    }
    public String getIdCertificate() {
        return this.idCertificate;
    }
    
    public void setIdCertificate(String idCertificate) {
        this.idCertificate = idCertificate;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


