package com.gbicc.company.financial.analysis.entity;
// Generated 2015-12-5 15:32:56 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * TCmCustomerFinance generated by hbm2java
 */
public class TCmCustomerFinance  implements java.io.Serializable {


    /*
    * 客户财务信息ID.
    */
    private String customerFinanceId;
    /*
    * 参与人ID.
    */
    private String partyId;
    /*
    * 客户编号.
    */
    private String customerNum;
    /*
    * 参与人类型代码.
    */
    private String participantTypeCd;
    /*
    * 财务报表类别代码.
    */
    private String customerTypeCd;
    /*
    * 财务报表截止日期.
    */
    private Date financeStatementDeadline;
    /*
    * 财务报表状态代码.
    */
    private String financeStatementStatusCd;
    /*
    * 财务报表类型代码.
    */
    private String financeStatementTypeCd;
    /*
    * 财务报表口径代码.
    */
    private String caliberCd;
    /*
    * 财务报表币种代码.
    */
    private String currencyCd;
    /*
    * 财务报表是否经过调整.
    */
    private String regulatedInd;
    /*
    * 财务报表调整原因.
    */
    private String regulationReason;
    /*
    * 财务报表会计准则.
    */
    private String accountingPrinciple;
    /*
    * 是否经过审计.
    */
    private String auditedInd;
    /*
    * 审计事务所审计意见类型代码.
    */
    private String auditCommentTypeCd;
    /*
    * 审计事务所名称.
    */
    private String auditCoName;
    /*
    * 审计事务所经营执照号码.
    */
    private String bizLicenseNum;
    /*
    * 审计部门.
    */
    private String auditDept;
    /*
    * 审计部门审计意见代码.
    */
    private String auditDeptCommentCd;
    /*
    * 审计时间.
    */
    private Date auditTime;
    /*
    * 是否生效.
    */
    private String validInd;
    /*
    * 财务报表录入人编号.
    */
    private String userNum;

    public TCmCustomerFinance() {
    }

	
    public TCmCustomerFinance(String customerFinanceId) {
        this.customerFinanceId = customerFinanceId;
    }
    public TCmCustomerFinance(String customerFinanceId, String partyId, String customerNum, String participantTypeCd, String customerTypeCd, Date financeStatementDeadline, String financeStatementStatusCd, String financeStatementTypeCd, String caliberCd, String currencyCd, String regulatedInd, String regulationReason, String accountingPrinciple, String auditedInd, String auditCommentTypeCd, String auditCoName, String bizLicenseNum, String auditDept, String auditDeptCommentCd, Date auditTime, String validInd, String userNum) {
       this.customerFinanceId = customerFinanceId;
       this.partyId = partyId;
       this.customerNum = customerNum;
       this.participantTypeCd = participantTypeCd;
       this.customerTypeCd = customerTypeCd;
       this.financeStatementDeadline = financeStatementDeadline;
       this.financeStatementStatusCd = financeStatementStatusCd;
       this.financeStatementTypeCd = financeStatementTypeCd;
       this.caliberCd = caliberCd;
       this.currencyCd = currencyCd;
       this.regulatedInd = regulatedInd;
       this.regulationReason = regulationReason;
       this.accountingPrinciple = accountingPrinciple;
       this.auditedInd = auditedInd;
       this.auditCommentTypeCd = auditCommentTypeCd;
       this.auditCoName = auditCoName;
       this.bizLicenseNum = bizLicenseNum;
       this.auditDept = auditDept;
       this.auditDeptCommentCd = auditDeptCommentCd;
       this.auditTime = auditTime;
       this.validInd = validInd;
       this.userNum = userNum;
    }
   
    public String getCustomerFinanceId() {
        return this.customerFinanceId;
    }
    
    public void setCustomerFinanceId(String customerFinanceId) {
        this.customerFinanceId = customerFinanceId;
    }
    public String getPartyId() {
        return this.partyId;
    }
    
    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }
    public String getCustomerNum() {
        return this.customerNum;
    }
    
    public void setCustomerNum(String customerNum) {
        this.customerNum = customerNum;
    }
    public String getParticipantTypeCd() {
        return this.participantTypeCd;
    }
    
    public void setParticipantTypeCd(String participantTypeCd) {
        this.participantTypeCd = participantTypeCd;
    }
    public String getCustomerTypeCd() {
        return this.customerTypeCd;
    }
    
    public void setCustomerTypeCd(String customerTypeCd) {
        this.customerTypeCd = customerTypeCd;
    }
    public Date getFinanceStatementDeadline() {
        return this.financeStatementDeadline;
    }
    
    public void setFinanceStatementDeadline(Date financeStatementDeadline) {
        this.financeStatementDeadline = financeStatementDeadline;
    }
    public String getFinanceStatementStatusCd() {
        return this.financeStatementStatusCd;
    }
    
    public void setFinanceStatementStatusCd(String financeStatementStatusCd) {
        this.financeStatementStatusCd = financeStatementStatusCd;
    }
    public String getFinanceStatementTypeCd() {
        return this.financeStatementTypeCd;
    }
    
    public void setFinanceStatementTypeCd(String financeStatementTypeCd) {
        this.financeStatementTypeCd = financeStatementTypeCd;
    }
    public String getCaliberCd() {
        return this.caliberCd;
    }
    
    public void setCaliberCd(String caliberCd) {
        this.caliberCd = caliberCd;
    }
    public String getCurrencyCd() {
        return this.currencyCd;
    }
    
    public void setCurrencyCd(String currencyCd) {
        this.currencyCd = currencyCd;
    }
    public String getRegulatedInd() {
        return this.regulatedInd;
    }
    
    public void setRegulatedInd(String regulatedInd) {
        this.regulatedInd = regulatedInd;
    }
    public String getRegulationReason() {
        return this.regulationReason;
    }
    
    public void setRegulationReason(String regulationReason) {
        this.regulationReason = regulationReason;
    }
    public String getAccountingPrinciple() {
        return this.accountingPrinciple;
    }
    
    public void setAccountingPrinciple(String accountingPrinciple) {
        this.accountingPrinciple = accountingPrinciple;
    }
    public String getAuditedInd() {
        return this.auditedInd;
    }
    
    public void setAuditedInd(String auditedInd) {
        this.auditedInd = auditedInd;
    }
    public String getAuditCommentTypeCd() {
        return this.auditCommentTypeCd;
    }
    
    public void setAuditCommentTypeCd(String auditCommentTypeCd) {
        this.auditCommentTypeCd = auditCommentTypeCd;
    }
    public String getAuditCoName() {
        return this.auditCoName;
    }
    
    public void setAuditCoName(String auditCoName) {
        this.auditCoName = auditCoName;
    }
    public String getBizLicenseNum() {
        return this.bizLicenseNum;
    }
    
    public void setBizLicenseNum(String bizLicenseNum) {
        this.bizLicenseNum = bizLicenseNum;
    }
    public String getAuditDept() {
        return this.auditDept;
    }
    
    public void setAuditDept(String auditDept) {
        this.auditDept = auditDept;
    }
    public String getAuditDeptCommentCd() {
        return this.auditDeptCommentCd;
    }
    
    public void setAuditDeptCommentCd(String auditDeptCommentCd) {
        this.auditDeptCommentCd = auditDeptCommentCd;
    }
    public Date getAuditTime() {
        return this.auditTime;
    }
    
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }
    public String getValidInd() {
        return this.validInd;
    }
    
    public void setValidInd(String validInd) {
        this.validInd = validInd;
    }
    public String getUserNum() {
        return this.userNum;
    }
    
    public void setUserNum(String userNum) {
        this.userNum = userNum;
    }




}


