package com.gbicc.company.warnDisposal.entity;
// Generated 2015-11-27 11:18:28 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * TCmWarnTaskRel generated by hbm2java
 */
public class TCmWarnTaskRel  implements java.io.Serializable {


    /**
	 * 
	 */
	private static final long serialVersionUID = -8692489883530114958L;
	/*
    * ID.
    */
    private String id;
    /*
    * 预警编号.
    */
    private String warnCode;
    /*
    * 客户ID.
    */
    private String customerId;
    /*
    * 任务编号.
    */
    private String taskId;
    /*
    * 预警规则主题.
    */
    private String warnSubject;
    /*
    * 预警规则名称.
    */
    private String warnName;
    /*
    * 预警时间.
    */
    private Date warnDate;
    /*
    * 是否排除.
    */
    private String warnElimIs;
    /*
    * 排除说明.
    */
    private String warnElimDesc;
    /*
    * 排除时间.
    */
    private Date warnElimDate;
    /*
    * 是否解除.
    */
    private String relieveIs;
    /*
    * 解除说明.
    */
    private String relieveDesc;
    /*
     * 解除时间
     */
    private Date relieveDate;
    /*
    * 预警等级.
    */
    private String warnLevel;
    /*
     * 预警状态.
     */
     private String warnStatus;
     /*
      * 预警类型
      */
     private String warnType;
     /*
      * 风险描述
      */
     private String riskDesc;
     /*
      * 审批等级
      */
     private String processLevel;
     /*
      * 规则描述
      */
     private String warnDesc;
     /*
      * 规则ID
      */
     private String warnId;
     /*
      *  输出
      */
     private String halfresult;
     
    public TCmWarnTaskRel() {
    }

	
    public TCmWarnTaskRel(String id) {
        this.id = id;
    }
    public TCmWarnTaskRel(String id, String warnCode, String customerId, String taskId, String warnSubject, String warnName, Date warnDate, String warnElimIs, String warnElimDesc, Date warnElimDate, String relieveIs, String relieveDesc, String warnLevel, String warnStatus, String warnType, String riskDesc, String processLevel, String warnDesc, String warnId, Date relieveDate) {
       this.id = id;
       this.warnCode = warnCode;
       this.customerId = customerId;
       this.taskId = taskId;
       this.warnSubject = warnSubject;
       this.warnName = warnName;
       this.warnDate = warnDate;
       this.warnElimIs = warnElimIs;
       this.warnElimDesc = warnElimDesc;
       this.warnElimDate = warnElimDate;
       this.relieveIs = relieveIs;
       this.relieveDesc = relieveDesc;
       this.warnLevel = warnLevel;
       this.warnStatus = warnStatus;
       this.warnType = warnType;
       this.riskDesc = riskDesc;
       this.processLevel = processLevel;
       this.warnDesc = warnDesc;
       this.warnId = warnId;
       this.relieveDate = relieveDate;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getWarnCode() {
        return this.warnCode;
    }
    
    public void setWarnCode(String warnCode) {
        this.warnCode = warnCode;
    }
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
    public String getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }
    public String getWarnSubject() {
        return this.warnSubject;
    }
    
    public void setWarnSubject(String warnSubject) {
        this.warnSubject = warnSubject;
    }
    public String getWarnName() {
        return this.warnName;
    }
    
    public void setWarnName(String warnName) {
        this.warnName = warnName;
    }
    public Date getWarnDate() {
        return this.warnDate;
    }
    
    public void setWarnDate(Date warnDate) {
        this.warnDate = warnDate;
    }
    public String getWarnElimIs() {
        return this.warnElimIs;
    }
    
    public void setWarnElimIs(String warnElimIs) {
        this.warnElimIs = warnElimIs;
    }
    public String getWarnElimDesc() {
        return this.warnElimDesc;
    }
    
    public void setWarnElimDesc(String warnElimDesc) {
        this.warnElimDesc = warnElimDesc;
    }
    public Date getWarnElimDate() {
        return this.warnElimDate;
    }
    
    public void setWarnElimDate(Date warnElimDate) {
        this.warnElimDate = warnElimDate;
    }
    public String getRelieveIs() {
        return this.relieveIs;
    }
    
    public void setRelieveIs(String relieveIs) {
        this.relieveIs = relieveIs;
    }
    public String getRelieveDesc() {
        return this.relieveDesc;
    }
    
    public void setRelieveDesc(String relieveDesc) {
        this.relieveDesc = relieveDesc;
    }
    public String getWarnLevel() {
        return this.warnLevel;
    }
    
    public void setWarnLevel(String warnLevel) {
        this.warnLevel = warnLevel;
    }

	public String getWarnStatus() {
		return warnStatus;
	}

	public void setWarnStatus(String warnStatus) {
		this.warnStatus = warnStatus;
	}

	public String getWarnType() {
		return warnType;
	}

	public void setWarnType(String warnType) {
		this.warnType = warnType;
	}


	public String getRiskDesc() {
		return riskDesc;
	}


	public void setRiskDesc(String riskDesc) {
		this.riskDesc = riskDesc;
	}


	public String getProcessLevel() {
		return processLevel;
	}


	public void setProcessLevel(String processLevel) {
		this.processLevel = processLevel;
	}


	public String getWarnDesc() {
		return warnDesc;
	}


	public void setWarnDesc(String warnDesc) {
		this.warnDesc = warnDesc;
	}


	public String getWarnId() {
		return warnId;
	}

	public void setWarnId(String warnId) {
		this.warnId = warnId;
	}


	public Date getRelieveDate() {
		return relieveDate;
	}


	public void setRelieveDate(Date relieveDate) {
		this.relieveDate = relieveDate;
	}


	public String getHalfresult() {
		return halfresult;
	}


	public void setHalfresult(String halfresult) {
		this.halfresult = halfresult;
	}




}


