package com.gbicc.company.view.entity;

import java.math.BigDecimal;
import java.util.Date;
// Generated 2015-11-30 17:00:32 by Hibernate Tools 3.2.2.GA



/**
 * TbConBorrAcctSummaryNew generated by hbm2java
 */
public class TbConBorrAcctSummaryNew  implements java.io.Serializable {
    /*

    */
	private static final long serialVersionUID = 1L;
	private String actCat;
	private String actType;
	private Date addPeriodDate;
	private String advAcctNo;
	private BigDecimal advAmt;
	private BigDecimal advBal;
	private BigDecimal advInt;
	private BigDecimal advOutBa;
	private String badDebtInd;
	private BigDecimal bailSum;
	private String balanceAccounts;
	private String bankGuaranteeState;
	private String bankGuaranteeType;
	private String billStatus;
	private BigDecimal bocketA;
	private BigDecimal bocketE;
	private BigDecimal bocketI;
	private BigDecimal bocketW;
	private String borrowNum;
	private String borrowStatus;
	private String brNo;
	private BigDecimal bucketP;
	private BigDecimal commissionChargeRatio;
	private String contractNum;
	private BigDecimal creditBalance;
	private String currencyCd;
	private String customerNum;
	private String discountSign;
	private Date expirationDate;
	private String financingInd;
	private Date firstBadDebtDate;
	private Date firstOvdueDate;
	private Date firstPrimnessDate;
	private String fiveLevel;
	private String fourLevel;
	private BigDecimal inOweAccounts;
	private Date lastMaintainDate;
	private BigDecimal lastRequitalSum;
	private String letterOfCreditState;
	private String loanAcct;
	private BigDecimal loanBal;
	private String operateBrch;
	private BigDecimal outOweAccounts;
	private String payoutAcctSummaryId;
	private String payoutAppFormNum;
	private String payoutInfoDetailId;
	private String postalOrderState;
	private Date qxRevertDate;
	private BigDecimal reSponsionWithodrawalSum;
	private String recState;
	private BigDecimal refundSum;
	private BigDecimal replacementBalance;
	private String replacementSign;
	private String stat;
	private String status;
	private BigDecimal storeRate;
	private BigDecimal theoLoanBal;
	private BigDecimal tmpAmt;
	private BigDecimal totalBadDebtAmt;
	private BigDecimal totalBefRetnPrp;
	private BigDecimal totalOvdueAmt;
	private BigDecimal totalPrimnessAmt;
	private BigDecimal totalRelRetnInt;
	private BigDecimal totalReturnPrp;
	private BigDecimal totalShouldRetnInt;
	private BigDecimal totalWriteoffInInt;
	private BigDecimal totalWriteoffOutInt;
	private BigDecimal totalWriteoffPrp;
	private BigDecimal undertakePaySum;
	private BigDecimal unpdBocketA;
	private BigDecimal unpdBocketE;
	private BigDecimal unpdBocketI;
	private BigDecimal unpdBocketW;
	private BigDecimal untreadSum;
	private Date writeOffDate;

	public TbConBorrAcctSummaryNew() {
	}

	public String getActCat() {
		return actCat;
	}

	public void setActCat(String actCat) {
		this.actCat = actCat;
	}

	public String getActType() {
		return actType;
	}

	public void setActType(String actType) {
		this.actType = actType;
	}

	public Date getAddPeriodDate() {
		return addPeriodDate;
	}

	public void setAddPeriodDate(Date addPeriodDate) {
		this.addPeriodDate = addPeriodDate;
	}

	public String getAdvAcctNo() {
		return advAcctNo;
	}

	public void setAdvAcctNo(String advAcctNo) {
		this.advAcctNo = advAcctNo;
	}

	public BigDecimal getAdvAmt() {
		return advAmt;
	}

	public void setAdvAmt(BigDecimal advAmt) {
		this.advAmt = advAmt;
	}

	public BigDecimal getAdvBal() {
		return advBal;
	}

	public void setAdvBal(BigDecimal advBal) {
		this.advBal = advBal;
	}

	public BigDecimal getAdvInt() {
		return advInt;
	}

	public void setAdvInt(BigDecimal advInt) {
		this.advInt = advInt;
	}

	public BigDecimal getAdvOutBa() {
		return advOutBa;
	}

	public void setAdvOutBa(BigDecimal advOutBa) {
		this.advOutBa = advOutBa;
	}

	public String getBadDebtInd() {
		return badDebtInd;
	}

	public void setBadDebtInd(String badDebtInd) {
		this.badDebtInd = badDebtInd;
	}

	public BigDecimal getBailSum() {
		return bailSum;
	}

	public void setBailSum(BigDecimal bailSum) {
		this.bailSum = bailSum;
	}

	public String getBalanceAccounts() {
		return balanceAccounts;
	}

	public void setBalanceAccounts(String balanceAccounts) {
		this.balanceAccounts = balanceAccounts;
	}

	public String getBankGuaranteeState() {
		return bankGuaranteeState;
	}

	public void setBankGuaranteeState(String bankGuaranteeState) {
		this.bankGuaranteeState = bankGuaranteeState;
	}

	public String getBankGuaranteeType() {
		return bankGuaranteeType;
	}

	public void setBankGuaranteeType(String bankGuaranteeType) {
		this.bankGuaranteeType = bankGuaranteeType;
	}

	public String getBillStatus() {
		return billStatus;
	}

	public void setBillStatus(String billStatus) {
		this.billStatus = billStatus;
	}

	public BigDecimal getBocketA() {
		return bocketA;
	}

	public void setBocketA(BigDecimal bocketA) {
		this.bocketA = bocketA;
	}

	public BigDecimal getBocketE() {
		return bocketE;
	}

	public void setBocketE(BigDecimal bocketE) {
		this.bocketE = bocketE;
	}

	public BigDecimal getBocketI() {
		return bocketI;
	}

	public void setBocketI(BigDecimal bocketI) {
		this.bocketI = bocketI;
	}

	public BigDecimal getBocketW() {
		return bocketW;
	}

	public void setBocketW(BigDecimal bocketW) {
		this.bocketW = bocketW;
	}

	public String getBorrowNum() {
		return borrowNum;
	}

	public void setBorrowNum(String borrowNum) {
		this.borrowNum = borrowNum;
	}

	public String getBorrowStatus() {
		return borrowStatus;
	}

	public void setBorrowStatus(String borrowStatus) {
		this.borrowStatus = borrowStatus;
	}

	public String getBrNo() {
		return brNo;
	}

	public void setBrNo(String brNo) {
		this.brNo = brNo;
	}

	public BigDecimal getBucketP() {
		return bucketP;
	}

	public void setBucketP(BigDecimal bucketP) {
		this.bucketP = bucketP;
	}

	public BigDecimal getCommissionChargeRatio() {
		return commissionChargeRatio;
	}

	public void setCommissionChargeRatio(BigDecimal commissionChargeRatio) {
		this.commissionChargeRatio = commissionChargeRatio;
	}

	public String getContractNum() {
		return contractNum;
	}

	public void setContractNum(String contractNum) {
		this.contractNum = contractNum;
	}

	public BigDecimal getCreditBalance() {
		return creditBalance;
	}

	public void setCreditBalance(BigDecimal creditBalance) {
		this.creditBalance = creditBalance;
	}

	public String getCurrencyCd() {
		return currencyCd;
	}

	public void setCurrencyCd(String currencyCd) {
		this.currencyCd = currencyCd;
	}

	public String getCustomerNum() {
		return customerNum;
	}

	public void setCustomerNum(String customerNum) {
		this.customerNum = customerNum;
	}

	public String getDiscountSign() {
		return discountSign;
	}

	public void setDiscountSign(String discountSign) {
		this.discountSign = discountSign;
	}

	public Date getExpirationDate() {
		return expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	public String getFinancingInd() {
		return financingInd;
	}

	public void setFinancingInd(String financingInd) {
		this.financingInd = financingInd;
	}

	public Date getFirstBadDebtDate() {
		return firstBadDebtDate;
	}

	public void setFirstBadDebtDate(Date firstBadDebtDate) {
		this.firstBadDebtDate = firstBadDebtDate;
	}

	public Date getFirstOvdueDate() {
		return firstOvdueDate;
	}

	public void setFirstOvdueDate(Date firstOvdueDate) {
		this.firstOvdueDate = firstOvdueDate;
	}

	public Date getFirstPrimnessDate() {
		return firstPrimnessDate;
	}

	public void setFirstPrimnessDate(Date firstPrimnessDate) {
		this.firstPrimnessDate = firstPrimnessDate;
	}

	public String getFiveLevel() {
		return fiveLevel;
	}

	public void setFiveLevel(String fiveLevel) {
		this.fiveLevel = fiveLevel;
	}

	public String getFourLevel() {
		return fourLevel;
	}

	public void setFourLevel(String fourLevel) {
		this.fourLevel = fourLevel;
	}

	public BigDecimal getInOweAccounts() {
		return inOweAccounts;
	}

	public void setInOweAccounts(BigDecimal inOweAccounts) {
		this.inOweAccounts = inOweAccounts;
	}

	public Date getLastMaintainDate() {
		return lastMaintainDate;
	}

	public void setLastMaintainDate(Date lastMaintainDate) {
		this.lastMaintainDate = lastMaintainDate;
	}

	public BigDecimal getLastRequitalSum() {
		return lastRequitalSum;
	}

	public void setLastRequitalSum(BigDecimal lastRequitalSum) {
		this.lastRequitalSum = lastRequitalSum;
	}

	public String getLetterOfCreditState() {
		return letterOfCreditState;
	}

	public void setLetterOfCreditState(String letterOfCreditState) {
		this.letterOfCreditState = letterOfCreditState;
	}

	public String getLoanAcct() {
		return loanAcct;
	}

	public void setLoanAcct(String loanAcct) {
		this.loanAcct = loanAcct;
	}

	public BigDecimal getLoanBal() {
		return loanBal;
	}

	public void setLoanBal(BigDecimal loanBal) {
		this.loanBal = loanBal;
	}

	public String getOperateBrch() {
		return operateBrch;
	}

	public void setOperateBrch(String operateBrch) {
		this.operateBrch = operateBrch;
	}

	public BigDecimal getOutOweAccounts() {
		return outOweAccounts;
	}

	public void setOutOweAccounts(BigDecimal outOweAccounts) {
		this.outOweAccounts = outOweAccounts;
	}

	public String getPayoutAcctSummaryId() {
		return payoutAcctSummaryId;
	}

	public void setPayoutAcctSummaryId(String payoutAcctSummaryId) {
		this.payoutAcctSummaryId = payoutAcctSummaryId;
	}

	public String getPayoutAppFormNum() {
		return payoutAppFormNum;
	}

	public void setPayoutAppFormNum(String payoutAppFormNum) {
		this.payoutAppFormNum = payoutAppFormNum;
	}

	public String getPayoutInfoDetailId() {
		return payoutInfoDetailId;
	}

	public void setPayoutInfoDetailId(String payoutInfoDetailId) {
		this.payoutInfoDetailId = payoutInfoDetailId;
	}

	public String getPostalOrderState() {
		return postalOrderState;
	}

	public void setPostalOrderState(String postalOrderState) {
		this.postalOrderState = postalOrderState;
	}

	public Date getQxRevertDate() {
		return qxRevertDate;
	}

	public void setQxRevertDate(Date qxRevertDate) {
		this.qxRevertDate = qxRevertDate;
	}

	public BigDecimal getReSponsionWithodrawalSum() {
		return reSponsionWithodrawalSum;
	}

	public void setReSponsionWithodrawalSum(BigDecimal reSponsionWithodrawalSum) {
		this.reSponsionWithodrawalSum = reSponsionWithodrawalSum;
	}

	public String getRecState() {
		return recState;
	}

	public void setRecState(String recState) {
		this.recState = recState;
	}

	public BigDecimal getRefundSum() {
		return refundSum;
	}

	public void setRefundSum(BigDecimal refundSum) {
		this.refundSum = refundSum;
	}

	public BigDecimal getReplacementBalance() {
		return replacementBalance;
	}

	public void setReplacementBalance(BigDecimal replacementBalance) {
		this.replacementBalance = replacementBalance;
	}

	public String getReplacementSign() {
		return replacementSign;
	}

	public void setReplacementSign(String replacementSign) {
		this.replacementSign = replacementSign;
	}

	public String getStat() {
		return stat;
	}

	public void setStat(String stat) {
		this.stat = stat;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public BigDecimal getStoreRate() {
		return storeRate;
	}

	public void setStoreRate(BigDecimal storeRate) {
		this.storeRate = storeRate;
	}

	public BigDecimal getTheoLoanBal() {
		return theoLoanBal;
	}

	public void setTheoLoanBal(BigDecimal theoLoanBal) {
		this.theoLoanBal = theoLoanBal;
	}

	public BigDecimal getTmpAmt() {
		return tmpAmt;
	}

	public void setTmpAmt(BigDecimal tmpAmt) {
		this.tmpAmt = tmpAmt;
	}

	public BigDecimal getTotalBadDebtAmt() {
		return totalBadDebtAmt;
	}

	public void setTotalBadDebtAmt(BigDecimal totalBadDebtAmt) {
		this.totalBadDebtAmt = totalBadDebtAmt;
	}

	public BigDecimal getTotalBefRetnPrp() {
		return totalBefRetnPrp;
	}

	public void setTotalBefRetnPrp(BigDecimal totalBefRetnPrp) {
		this.totalBefRetnPrp = totalBefRetnPrp;
	}

	public BigDecimal getTotalOvdueAmt() {
		return totalOvdueAmt;
	}

	public void setTotalOvdueAmt(BigDecimal totalOvdueAmt) {
		this.totalOvdueAmt = totalOvdueAmt;
	}

	public BigDecimal getTotalPrimnessAmt() {
		return totalPrimnessAmt;
	}

	public void setTotalPrimnessAmt(BigDecimal totalPrimnessAmt) {
		this.totalPrimnessAmt = totalPrimnessAmt;
	}

	public BigDecimal getTotalRelRetnInt() {
		return totalRelRetnInt;
	}

	public void setTotalRelRetnInt(BigDecimal totalRelRetnInt) {
		this.totalRelRetnInt = totalRelRetnInt;
	}

	public BigDecimal getTotalReturnPrp() {
		return totalReturnPrp;
	}

	public void setTotalReturnPrp(BigDecimal totalReturnPrp) {
		this.totalReturnPrp = totalReturnPrp;
	}

	public BigDecimal getTotalShouldRetnInt() {
		return totalShouldRetnInt;
	}

	public void setTotalShouldRetnInt(BigDecimal totalShouldRetnInt) {
		this.totalShouldRetnInt = totalShouldRetnInt;
	}

	public BigDecimal getTotalWriteoffInInt() {
		return totalWriteoffInInt;
	}

	public void setTotalWriteoffInInt(BigDecimal totalWriteoffInInt) {
		this.totalWriteoffInInt = totalWriteoffInInt;
	}

	public BigDecimal getTotalWriteoffOutInt() {
		return totalWriteoffOutInt;
	}

	public void setTotalWriteoffOutInt(BigDecimal totalWriteoffOutInt) {
		this.totalWriteoffOutInt = totalWriteoffOutInt;
	}

	public BigDecimal getTotalWriteoffPrp() {
		return totalWriteoffPrp;
	}

	public void setTotalWriteoffPrp(BigDecimal totalWriteoffPrp) {
		this.totalWriteoffPrp = totalWriteoffPrp;
	}

	public BigDecimal getUndertakePaySum() {
		return undertakePaySum;
	}

	public void setUndertakePaySum(BigDecimal undertakePaySum) {
		this.undertakePaySum = undertakePaySum;
	}

	public BigDecimal getUnpdBocketA() {
		return unpdBocketA;
	}

	public void setUnpdBocketA(BigDecimal unpdBocketA) {
		this.unpdBocketA = unpdBocketA;
	}

	public BigDecimal getUnpdBocketE() {
		return unpdBocketE;
	}

	public void setUnpdBocketE(BigDecimal unpdBocketE) {
		this.unpdBocketE = unpdBocketE;
	}

	public BigDecimal getUnpdBocketI() {
		return unpdBocketI;
	}

	public void setUnpdBocketI(BigDecimal unpdBocketI) {
		this.unpdBocketI = unpdBocketI;
	}

	public BigDecimal getUnpdBocketW() {
		return unpdBocketW;
	}

	public void setUnpdBocketW(BigDecimal unpdBocketW) {
		this.unpdBocketW = unpdBocketW;
	}

	public BigDecimal getUntreadSum() {
		return untreadSum;
	}

	public void setUntreadSum(BigDecimal untreadSum) {
		this.untreadSum = untreadSum;
	}

	public Date getWriteOffDate() {
		return writeOffDate;
	}

	public void setWriteOffDate(Date writeOffDate) {
		this.writeOffDate = writeOffDate;
	}


}


