package com.gbicc.person.eliminate.entity;
// Generated 2015-11-12 17:49:33 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * TPlTriggerRuleAcct generated by hbm2java
 */
public class TPlTriggerRuleAcct  implements java.io.Serializable {

	private static final long serialVersionUID = 8160820341919565083L;
	
	/*
    */
    private String id;
    /*
    * 贷款账号.
    */
    private String loanAcct;
    /*
    * 客户名称.
    */
    private String custName;
    /*
    * 预警等级.
    */
    private String warnLevel;
    /*
    * 预警时间.
    */
    private Date warnDate;
    /*
    * 贷款产品.
    */
    private String loanVariety;
    /*
    * 贷款金额.
    */
    private Double loanAmt;
    /*
    * 贷款余额.
    */
    private Double loanBalance;
    /*
    * 贷款期限.
    */
    private String loanTerm;

    public TPlTriggerRuleAcct() {
    }

	
    public TPlTriggerRuleAcct(String id) {
        this.id = id;
    }
    public TPlTriggerRuleAcct(String id, String loanAcct, String custName, String warnLevel, Date warnDate, String loanVariety, Double loanAmt, Double loanBalance, String loanTerm) {
       this.id = id;
       this.loanAcct = loanAcct;
       this.custName = custName;
       this.warnLevel = warnLevel;
       this.warnDate = warnDate;
       this.loanVariety = loanVariety;
       this.loanAmt = loanAmt;
       this.loanBalance = loanBalance;
       this.loanTerm = loanTerm;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getLoanAcct() {
        return this.loanAcct;
    }
    
    public void setLoanAcct(String loanAcct) {
        this.loanAcct = loanAcct;
    }
    public String getCustName() {
        return this.custName;
    }
    
    public void setCustName(String custName) {
        this.custName = custName;
    }
    public String getWarnLevel() {
        return this.warnLevel;
    }
    
    public void setWarnLevel(String warnLevel) {
        this.warnLevel = warnLevel;
    }
    public Date getWarnDate() {
        return this.warnDate;
    }
    
    public void setWarnDate(Date warnDate) {
        this.warnDate = warnDate;
    }
    public String getLoanVariety() {
        return this.loanVariety;
    }
    
    public void setLoanVariety(String loanVariety) {
        this.loanVariety = loanVariety;
    }
    public Double getLoanAmt() {
        return this.loanAmt;
    }
    
    public void setLoanAmt(Double loanAmt) {
        this.loanAmt = loanAmt;
    }
    public Double getLoanBalance() {
        return this.loanBalance;
    }
    
    public void setLoanBalance(Double loanBalance) {
        this.loanBalance = loanBalance;
    }
    public String getLoanTerm() {
        return this.loanTerm;
    }
    
    public void setLoanTerm(String loanTerm) {
        this.loanTerm = loanTerm;
    }
}