package com.gbicc.company.single.outputentity;
// Generated 2016-1-12 19:22:04 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * TRewJ17SubcontractId generated by hbm2java
 */
public class J17  implements java.io.Serializable {

	private static final long serialVersionUID = 4858051553085100014L;
	
	/*
    */
    private String subcontractId;
    /*
    */
    private String contractId;
    /*
    */
    private String contractNum;
    /*
    */
    private String subcontractNum;
    /*
    */
    private String customerNum;
    /*
    */
    private String currencyCd;
    /*
    */
    private BigDecimal guarantyAmt;
    /*
    */
    private String superTopGuarantyId;
    /*
    */
    private String topGuarantyStartDate;
    /*
    */
    private String topGuarantyExpirationDate;
    /*
    */
    private String subContractSignDate;
    /*
    */
    private String subContractSignPlace;
    /*
    */
    private String subcontractTypeCd;
    /*
    */
    private String startDate;
    /*
    */
    private String subcontractStatusCd;
    /*
    */
    private String expirationDate;
    /*
    */
    private String handlingOrgCd;
    /*
    */
    private String otherPromise;
    /*
    */
    private String handlingUserNum;
    /*
    */
    private BigDecimal subContractAmt;
    /*
    */
    private BigDecimal guarantyUseAmtCount;
    /*
    */
    private BigDecimal subContRate;
    /*
    */
    private BigDecimal topGuarantyAmt;
    /*
    */
    private BigDecimal topCumulateGuarantyAmt;
    /*
    */
    private String guarantCustomerNum;
    /*
    */
    private BigDecimal guarantyRate;
    /*
    */
    private String debtCustomerNum;
    /*
    */
    private String guaranteeTypeCd;
    /*
    */
    private String subcontractManualNum;
    /*
    */
    private String warrantorName;
    /*
    */
    private String debtPersonName;
    /*
    */
    private BigDecimal topUseGuarantyAmt;
    /*
    */
    private String ifTopGuaranty;
    /*
    */
    private String collateralTypeCd;
    /*
    */
    private String registerOrg;
    /*
    */
    private String collateralRemark;
    /*
    */
    private String importInd;
    /*
    */
    private String printSubcontractType;
    /*
     */
    private String fdCustName;
    /*
    * 预警表ID.
    */
    private String warnId;
    /*
    * 数据日期.
    */
    private String dataDt;

    public J17() {
    }

	/**
    */	
    public String getSubcontractId() {
        return this.subcontractId;
    }
	/**
    */	
    public void setSubcontractId(String subcontractId) {
        this.subcontractId = subcontractId;
    }
	/**
    */	
    public String getContractId() {
        return this.contractId;
    }
	/**
    */	
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }
	/**
    */	
    public String getContractNum() {
        return this.contractNum;
    }
	/**
    */	
    public void setContractNum(String contractNum) {
        this.contractNum = contractNum;
    }
	/**
    */	
    public String getSubcontractNum() {
        return this.subcontractNum;
    }
	/**
    */	
    public void setSubcontractNum(String subcontractNum) {
        this.subcontractNum = subcontractNum;
    }
	/**
    */	
    public String getCustomerNum() {
        return this.customerNum;
    }
	/**
    */	
    public void setCustomerNum(String customerNum) {
        this.customerNum = customerNum;
    }
	/**
    */	
    public String getCurrencyCd() {
        return this.currencyCd;
    }
	/**
    */	
    public void setCurrencyCd(String currencyCd) {
        this.currencyCd = currencyCd;
    }
	/**
    */	
    public BigDecimal getGuarantyAmt() {
        return this.guarantyAmt;
    }
	/**
    */	
    public void setGuarantyAmt(BigDecimal guarantyAmt) {
        this.guarantyAmt = guarantyAmt;
    }
	/**
    */	
    public String getSuperTopGuarantyId() {
        return this.superTopGuarantyId;
    }
	/**
    */	
    public void setSuperTopGuarantyId(String superTopGuarantyId) {
        this.superTopGuarantyId = superTopGuarantyId;
    }
	/**
    */	
    public String getTopGuarantyStartDate() {
        return this.topGuarantyStartDate;
    }
	/**
    */	
    public void setTopGuarantyStartDate(String topGuarantyStartDate) {
        this.topGuarantyStartDate = topGuarantyStartDate;
    }
	/**
    */	
    public String getTopGuarantyExpirationDate() {
        return this.topGuarantyExpirationDate;
    }
	/**
    */	
    public void setTopGuarantyExpirationDate(String topGuarantyExpirationDate) {
        this.topGuarantyExpirationDate = topGuarantyExpirationDate;
    }
	/**
    */	
    public String getSubContractSignDate() {
        return this.subContractSignDate;
    }
	/**
    */	
    public void setSubContractSignDate(String subContractSignDate) {
        this.subContractSignDate = subContractSignDate;
    }
	/**
    */	
    public String getSubContractSignPlace() {
        return this.subContractSignPlace;
    }
	/**
    */	
    public void setSubContractSignPlace(String subContractSignPlace) {
        this.subContractSignPlace = subContractSignPlace;
    }
	/**
    */	
    public String getSubcontractTypeCd() {
        return this.subcontractTypeCd;
    }
	/**
    */	
    public void setSubcontractTypeCd(String subcontractTypeCd) {
        this.subcontractTypeCd = subcontractTypeCd;
    }
	/**
    */	
    public String getStartDate() {
        return this.startDate;
    }
	/**
    */	
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }
	/**
    */	
    public String getSubcontractStatusCd() {
        return this.subcontractStatusCd;
    }
	/**
    */	
    public void setSubcontractStatusCd(String subcontractStatusCd) {
        this.subcontractStatusCd = subcontractStatusCd;
    }
	/**
    */	
    public String getExpirationDate() {
        return this.expirationDate;
    }
	/**
    */	
    public void setExpirationDate(String expirationDate) {
        this.expirationDate = expirationDate;
    }
	/**
    */	
    public String getHandlingOrgCd() {
        return this.handlingOrgCd;
    }
	/**
    */	
    public void setHandlingOrgCd(String handlingOrgCd) {
        this.handlingOrgCd = handlingOrgCd;
    }
	/**
    */	
    public String getOtherPromise() {
        return this.otherPromise;
    }
	/**
    */	
    public void setOtherPromise(String otherPromise) {
        this.otherPromise = otherPromise;
    }
	/**
    */	
    public String getHandlingUserNum() {
        return this.handlingUserNum;
    }
	/**
    */	
    public void setHandlingUserNum(String handlingUserNum) {
        this.handlingUserNum = handlingUserNum;
    }
	/**
    */	
    public BigDecimal getSubContractAmt() {
        return this.subContractAmt;
    }
	/**
    */	
    public void setSubContractAmt(BigDecimal subContractAmt) {
        this.subContractAmt = subContractAmt;
    }
	/**
    */	
    public BigDecimal getGuarantyUseAmtCount() {
        return this.guarantyUseAmtCount;
    }
	/**
    */	
    public void setGuarantyUseAmtCount(BigDecimal guarantyUseAmtCount) {
        this.guarantyUseAmtCount = guarantyUseAmtCount;
    }
	/**
    */	
    public BigDecimal getSubContRate() {
        return this.subContRate;
    }
	/**
    */	
    public void setSubContRate(BigDecimal subContRate) {
        this.subContRate = subContRate;
    }
	/**
    */	
    public BigDecimal getTopGuarantyAmt() {
        return this.topGuarantyAmt;
    }
	/**
    */	
    public void setTopGuarantyAmt(BigDecimal topGuarantyAmt) {
        this.topGuarantyAmt = topGuarantyAmt;
    }
	/**
    */	
    public BigDecimal getTopCumulateGuarantyAmt() {
        return this.topCumulateGuarantyAmt;
    }
	/**
    */	
    public void setTopCumulateGuarantyAmt(BigDecimal topCumulateGuarantyAmt) {
        this.topCumulateGuarantyAmt = topCumulateGuarantyAmt;
    }
	/**
    */	
    public String getGuarantCustomerNum() {
        return this.guarantCustomerNum;
    }
	/**
    */	
    public void setGuarantCustomerNum(String guarantCustomerNum) {
        this.guarantCustomerNum = guarantCustomerNum;
    }
	/**
    */	
    public BigDecimal getGuarantyRate() {
        return this.guarantyRate;
    }
	/**
    */	
    public void setGuarantyRate(BigDecimal guarantyRate) {
        this.guarantyRate = guarantyRate;
    }
	/**
    */	
    public String getDebtCustomerNum() {
        return this.debtCustomerNum;
    }
	/**
    */	
    public void setDebtCustomerNum(String debtCustomerNum) {
        this.debtCustomerNum = debtCustomerNum;
    }
	/**
    */	
    public String getGuaranteeTypeCd() {
        return this.guaranteeTypeCd;
    }
	/**
    */	
    public void setGuaranteeTypeCd(String guaranteeTypeCd) {
        this.guaranteeTypeCd = guaranteeTypeCd;
    }
	/**
    */	
    public String getSubcontractManualNum() {
        return this.subcontractManualNum;
    }
	/**
    */	
    public void setSubcontractManualNum(String subcontractManualNum) {
        this.subcontractManualNum = subcontractManualNum;
    }
	/**
    */	
    public String getWarrantorName() {
        return this.warrantorName;
    }
	/**
    */	
    public void setWarrantorName(String warrantorName) {
        this.warrantorName = warrantorName;
    }
	/**
    */	
    public String getDebtPersonName() {
        return this.debtPersonName;
    }
	/**
    */	
    public void setDebtPersonName(String debtPersonName) {
        this.debtPersonName = debtPersonName;
    }
	/**
    */	
    public BigDecimal getTopUseGuarantyAmt() {
        return this.topUseGuarantyAmt;
    }
	/**
    */	
    public void setTopUseGuarantyAmt(BigDecimal topUseGuarantyAmt) {
        this.topUseGuarantyAmt = topUseGuarantyAmt;
    }
	/**
    */	
    public String getIfTopGuaranty() {
        return this.ifTopGuaranty;
    }
	/**
    */	
    public void setIfTopGuaranty(String ifTopGuaranty) {
        this.ifTopGuaranty = ifTopGuaranty;
    }
	/**
    */	
    public String getCollateralTypeCd() {
        return this.collateralTypeCd;
    }
	/**
    */	
    public void setCollateralTypeCd(String collateralTypeCd) {
        this.collateralTypeCd = collateralTypeCd;
    }
	/**
    */	
    public String getRegisterOrg() {
        return this.registerOrg;
    }
	/**
    */	
    public void setRegisterOrg(String registerOrg) {
        this.registerOrg = registerOrg;
    }
	/**
    */	
    public String getCollateralRemark() {
        return this.collateralRemark;
    }
	/**
    */	
    public void setCollateralRemark(String collateralRemark) {
        this.collateralRemark = collateralRemark;
    }
	/**
    */	
    public String getImportInd() {
        return this.importInd;
    }
	/**
    */	
    public void setImportInd(String importInd) {
        this.importInd = importInd;
    }
	/**
    */	
    public String getPrintSubcontractType() {
        return this.printSubcontractType;
    }
	/**
    */	
    public void setPrintSubcontractType(String printSubcontractType) {
        this.printSubcontractType = printSubcontractType;
    }
	/**
    * Get the 预警表ID
    */	
    public String getWarnId() {
        return this.warnId;
    }
	/**
    * Set the 预警表ID
    */	
    public void setWarnId(String warnId) {
        this.warnId = warnId;
    }
	/**
    * Get the 数据日期
    */	
    public String getDataDt() {
        return this.dataDt;
    }
	/**
    * Set the 数据日期
    */	
    public void setDataDt(String dataDt) {
        this.dataDt = dataDt;
    }
	public String getFdCustName() {
		return fdCustName;
	}
	public void setFdCustName(String fdCustName) {
		this.fdCustName = fdCustName;
	}
}